/*cspell:disable*/
/*
 * C program generated by CDL2 v1.0.0 for PROGRAM c sort at 2025-12-22 18:25:46.
 */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define BOOL long
#define VALUE long
/* CDL2 Standard Macros for Lists */
#define CDL2_DECLARE_LIST(name, lwb, upb) \
    VALUE name##_array[(upb) - (lwb) + 1]; \
    VALUE name##_lwb = (lwb); \
    VALUE name##_upb = (upb)

#define CDL2_LIST_GET(name, i) \
    ((i) < name##_lwb || (i) > name##_upb ? \
        (fprintf(stderr, "Index out of bounds: %ld not in [%ld..%ld]\\n", (VALUE)(i), name##_lwb, name##_upb), exit(1), 0) : \
        name##_array[(i) - name##_lwb])

#define CDL2_LIST_SET(name, i, value) \
    do { \
        if ((i) < name##_lwb || (i) > name##_upb) { \
            fprintf(stderr, "Index out of bounds: %ld not in [%ld..%ld]\\n", (VALUE)(i), name##_lwb, name##_upb); \
            exit(1); \
        } \
        name##_array[(i) - name##_lwb] = (value); \
    } while(0)

#define CDL2_LIST_SWAP(name, i, j) \
    do { \
        VALUE temp; \
        if ((i) < name##_lwb || (i) > name##_upb || (j) < name##_lwb || (j) > name##_upb) { \
            fprintf(stderr, "Index out of bounds in swap\\n"); \
            exit(1); \
        } \
        temp = name##_array[(i) - name##_lwb]; \
        name##_array[(i) - name##_lwb] = name##_array[(j) - name##_lwb]; \
        name##_array[(j) - name##_lwb] = temp; \
    } while(0)


# ===============================================================================

# Begin PROG c sort


/* ##### 6 Consts ##### */

#define ckernel_kernel_arithmetic_constx 1
#define quicksort_base_parametrization_upb 10000
#define quicksort_base_parametrization_lwb 1
#define quicksort_base_parametrization_minrandom 0
#define quicksort_base_parametrization_maxrandom 200
#define quicksort_base_parametrization_maxsizeoflisttoshow 100

/* ##### 3 Vars ##### */

VALUE v_ckernel_kernel_data_datasize = 1747477110  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
VALUE v_ckernel_kernel_timer_start = 1640883809  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
VALUE v_ckernel_kernel_timer_stop = 2051015223  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;

/* ##### 1 LIST ##### */

CDL2_DECLARE_LIST(ckernel_kernel_data_data, quicksort_base_parametrization_lwb, quicksort_base_parametrization_upb);

/* ##### 23 Macros ##### */



// FUNCTION add+>a+>b+c> =
//    c " = " a " + " b ";".
void ckernel_kernel_arithmetic_add(VALUE a_a, VALUE a_b, VALUE *a_c) {
   *a_c = a_a + a_b;
}


// FUNCTION subtract+>a+>b+c> =
//    c " = " a " - " b ";".
void ckernel_kernel_arithmetic_subtract(VALUE a_a, VALUE a_b, VALUE *a_c) {
   *a_c = a_a - a_b;
}


// FUNCTION incr+>a> =
//    a "++;".
void ckernel_kernel_arithmetic_incr(VALUE *a_a) {
   *a_a++;
}


// FUNCTION make+a>+>b =
//    a " = " b ";".
void ckernel_kernel_arithmetic_make(VALUE *a_a, VALUE a_b) {
   *a_a = a_b;
}


// TEST le+>a+>b =
//    a " <= " b.
BOOL ckernel_kernel_arithmetic_le(VALUE a_a, VALUE a_b) {
   return a_a <= a_b;
}


// FUNCTION random+>min+>max+r> =
//    r " = " min " + rand() % ((" max ") - (" min ") + 1);".
void ckernel_kernel_arithmetic_random(VALUE a_min, VALUE a_max, VALUE *a_r) {
   *a_r = a_min + rand() % ((a_max) - (a_min) + 1);
}


// ACTION set element+>i+>v =
//    "CDL2_LIST_SET(" data ", " i ", " v ");".
void ckernel_kernel_data_setelement(VALUE a_i, VALUE a_v) {
   CDL2_LIST_SET(ckernel_kernel_data_data, a_i, a_v);
}


// ACTION show msg no newline*string =
//    "printf($"%s$", " string ");".
void ckernel_kernel_messages_showmsgnonewline(char *a_string) {
   printf("%s", a_string);
}


// ACTION dump list =
//    "$Lfor (long i = " lwb "; i <= " upb "; i++)" 
//    "$L   printf($"%ld $", CDL2_LIST_GET(" data ", i));".
void ckernel_kernel_data_dumplist() {
   for (long i = quicksort_base_parametrization_lwb; i <= quicksort_base_parametrization_upb; i++)
      printf("%ld ", CDL2_LIST_GET(ckernel_kernel_data_data, i));
}


// ACTION show msg*string =
//    "printf($"%s\n$", " string ");".
void ckernel_kernel_messages_showmsg(char *a_string) {
   printf("%s\n", a_string);
}


// FUNCTION touch out+v> =
//    "".
void quicksort_base_touch_touchout(VALUE *a_v) {
   }


// FUNCTION touch in+>v =
//    "".
void quicksort_base_touch_touchin(VALUE a_v) {
   }


// TEST is data sorted macro -i -r =
//    r " = 1;" 
//    "$Lfor (" i " = " lwb "; " i " < " upb "; " i "++) {" 
//    "$L   if (CDL2_LIST_GET(" data ", " i ") > CDL2_LIST_GET(" data ", " i " + 1)) {" 
//    "$L      " r " = 0;" 
//    "$L      break;" 
//    "$L   }" 
//    "$L}" 
//    "$L" r " == 1".
BOOL ckernel_kernel_data_isdatasortedmacro() {
   VALUE l_i = 1388008070  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   VALUE l_r = 1147749092  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   l_r = 1;
   for (l_i = quicksort_base_parametrization_lwb; l_i < quicksort_base_parametrization_upb; l_i++) {
      if (CDL2_LIST_GET(ckernel_kernel_data_data, l_i) > CDL2_LIST_GET(ckernel_kernel_data_data, l_i + 1)) {
         l_r = 0;
         break;
      }
   }
   return l_r == 1;
}


// ACTION show number+>number =
//    "printf($"%ld$", " number ");".
void ckernel_kernel_messages_shownumber(VALUE a_number) {
   printf("%ld", a_number);
}


// ACTION start timer =
//    start " = clock();".
void ckernel_kernel_timer_starttimer() {
   v_ckernel_kernel_timer_start = clock();
}


// TEST lt+>a+>b =
//    a " < " b.
BOOL ckernel_kernel_arithmetic_lt(VALUE a_a, VALUE a_b) {
   return a_a < a_b;
}


// FUNCTION halve+>a> =
//    a " /= 2;".
void ckernel_kernel_arithmetic_halve(VALUE *a_a) {
   *a_a /= 2;
}


// TEST smaller element+>p+>q =
//    "CDL2_LIST_GET(" data ", " p ") < CDL2_LIST_GET(" data ", " q ")".
BOOL ckernel_kernel_data_smallerelement(VALUE a_p, VALUE a_q) {
   return CDL2_LIST_GET(ckernel_kernel_data_data, a_p) < CDL2_LIST_GET(ckernel_kernel_data_data, a_q);
}


// FUNCTION decr+>a> =
//    a "--;".
void ckernel_kernel_arithmetic_decr(VALUE *a_a) {
   *a_a--;
}


// ACTION swap element+>i+>j =
//    "CDL2_LIST_SWAP(" data ", " i ", " j ");".
void ckernel_kernel_data_swapelement(VALUE a_i, VALUE a_j) {
   CDL2_LIST_SWAP(ckernel_kernel_data_data, a_i, a_j);
}


// ACTION stop timer =
//    stop " = clock();".
void ckernel_kernel_timer_stoptimer() {
   v_ckernel_kernel_timer_stop = clock();
}


// ACTION show elapsed time =
//    "printf($"Elapsed time: %.0f milliseconds\n$", (double)(" stop " - " start 
//    ") * 1000.0 / CLOCKS_PER_SEC);".
void ckernel_kernel_timer_showelapsedtime() {
   printf("Elapsed time: %.0f milliseconds\n", (double)(v_ckernel_kernel_timer_stop - v_ckernel_kernel_timer_start) * 1000.0 / CLOCKS_PER_SEC);
}


// ACTION sort data =
//    "$Lint cmp(const void *a, const void *b) { return (*(long*)a - *(long*)b); }" 
//    "$Lqsort(" data "_array, " upb " - " lwb " + 1, sizeof(long), cmp);".
void ckernel_kernel_data_sortdata() {
   int cmp(const void *a, const void *b) { return (*(long*)a - *(long*)b); }
   qsort(ckernel_kernel_data_data_array, quicksort_base_parametrization_upb - quicksort_base_parametrization_lwb + 1, sizeof(long), cmp);
}

/* ##### 12 Procedures ##### */



// ACTION initialize data -i -r -z :
//    add+const x+const x+z, subtract+upb+lwb+data size, incr+data size, make+i+lwb, 
//       (le+i+upb, random+min random+max random+r, set element+i+r, incr+i, *;
//        +).
void ckernel_kernel_data_initializedata() {
   VALUE l_i = 1380591523  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   VALUE l_r = 1484115349  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   VALUE l_z = 643234966  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   /* Alternative 1 */
   ckernel_kernel_arithmetic_add(ckernel_kernel_