/*cspell:disable*/
/*
 * C program generated by CDL2 v1.0.0 for PROGRAM c sort at 2025-12-21 19:43:18.
 */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define BOOL long
#define VALUE long
/* CDL2 Standard Macros for Lists */
#define CDL2_DECLARE_LIST(name, lwb, upb) \
    VALUE name##_array[(upb) - (lwb) + 1]; \
    VALUE name##_lwb = (lwb); \
    VALUE name##_upb = (upb)

#define CDL2_LIST_GET(name, i) \
    ((i) < name##_lwb || (i) > name##_upb ? \
        (fprintf(stderr, "Index out of bounds: %ld not in [%ld..%ld]\\n", (VALUE)(i), name##_lwb, name##_upb), exit(1), 0) : \
        name##_array[(i) - name##_lwb])

#define CDL2_LIST_SET(name, i, value) \
    do { \
        if ((i) < name##_lwb || (i) > name##_upb) { \
            fprintf(stderr, "Index out of bounds: %ld not in [%ld..%ld]\\n", (VALUE)(i), name##_lwb, name##_upb); \
            exit(1); \
        } \
        name##_array[(i) - name##_lwb] = (value); \
    } while(0)

#define CDL2_LIST_SWAP(name, i, j) \
    do { \
        VALUE temp; \
        if ((i) < name##_lwb || (i) > name##_upb || (j) < name##_lwb || (j) > name##_upb) { \
            fprintf(stderr, "Index out of bounds in swap\\n"); \
            exit(1); \
        } \
        temp = name##_array[(i) - name##_lwb]; \
        name##_array[(i) - name##_lwb] = name##_array[(j) - name##_lwb]; \
        name##_array[(j) - name##_lwb] = temp; \
    } while(0)


# ===============================================================================

# Begin PROG c sort


/* ##### 6 Consts ##### */

#define ckernel_kernel_arithmetic_constx 1
#define quicksort_base_parametrization_upb 10000
#define quicksort_base_parametrization_lwb 1
#define quicksort_base_parametrization_minrandom 0
#define quicksort_base_parametrization_maxrandom 200
#define quicksort_base_parametrization_maxsizeoflisttoshow 100

/* ##### 3 Vars ##### */

VALUE v_ckernel_kernel_data_datasize = 779716623  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
VALUE v_ckernel_kernel_timer_start = 1838068738  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
VALUE v_ckernel_kernel_timer_stop = 1367788213  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;

/* ##### 1 LIST ##### */

CDL2_DECLARE_LIST(ckernel_kernel_data_data, quicksort_base_parametrization_lwb, quicksort_base_parametrization_upb);

/* ##### 23 Macros ##### */



// FUNCTION add+>a+>b+c> =
//    c " = " a " + " b ";".
void ckernel_kernel_arithmetic_add(VALUE a_a, VALUE a_b, VALUE *a_c) {
   *a_c = a_a + a_b;
}


// FUNCTION subtract+>a+>b+c> =
//    c " = " a " - " b ";".
void ckernel_kernel_arithmetic_subtract(VALUE a_a, VALUE a_b, VALUE *a_c) {
   *a_c = a_a - a_b;
}


// FUNCTION incr+>a> =
//    a "++;".
void ckernel_kernel_arithmetic_incr(VALUE *a_a) {
   *a_a++;
}


// FUNCTION make+a>+>b =
//    a " = " b ";".
void ckernel_kernel_arithmetic_make(VALUE *a_a, VALUE a_b) {
   *a_a = a_b;
}


// TEST le+>a+>b =
//    a " <= " b.
BOOL ckernel_kernel_arithmetic_le(VALUE a_a, VALUE a_b) {
   return a_a <= a_b;
}


// FUNCTION random+>min+>max+r> =
//    r " = " min " + rand() % ((" max ") - (" min ") + 1);".
void ckernel_kernel_arithmetic_random(VALUE a_min, VALUE a_max, VALUE *a_r) {
   *a_r = a_min + rand() % ((a_max) - (a_min) + 1);
}


// ACTION set element+>i+>v =
//    "CDL2_LIST_SET(" data ", " i ", " v ");".
void ckernel_kernel_data_setelement(VALUE a_i, VALUE a_v) {
   CDL2_LIST_SET(ckernel_kernel_data_data, a_i, a_v);
}


// ACTION show msg no newline*string =
//    "printf($"%s$", " string ");".
void ckernel_kernel_messages_showmsgnonewline(char *a_string) {
   printf("%s", a_string);
}


// ACTION dump list =
//    "$Lfor (long i = " lwb "; i <= " upb "; i++)" 
//    "$L   printf($"%ld $", CDL2_LIST_GET(" data ", i));".
void ckernel_kernel_data_dumplist() {
   for (long i = quicksort_base_parametrization_lwb; i <= quicksort_base_parametrization_upb; i++)
      printf("%ld ", CDL2_LIST_GET(ckernel_kernel_data_data, i));
}


// ACTION show msg*string =
//    "printf($"%s\n$", " string ");".
void ckernel_kernel_messages_showmsg(char *a_string) {
   printf("%s\n", a_string);
}


// FUNCTION touch out+v> =
//    "".
void quicksort_base_touch_touchout(VALUE *a_v) {
   }


// FUNCTION touch in+>v =
//    "".
void quicksort_base_touch_touchin(VALUE a_v) {
   }


// TEST is data sorted macro -i -r =
//    r " = 1;" 
//    "$Lfor (" i " = " lwb "; " i " < " upb "; " i "++) {" 
//    "$L   if (CDL2_LIST_GET(" data ", " i ") > CDL2_LIST_GET(" data ", " i " + 1)) {" 
//    "$L      " r " = 0;" 
//    "$L      break;" 
//    "$L   }" 
//    "$L}" 
//    "$L" r " == 1".
BOOL ckernel_kernel_data_isdatasortedmacro() {
   VALUE l_i = 785170419  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   VALUE l_r = 1353987001  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   l_r = 1;
   for (l_i = quicksort_base_parametrization_lwb; l_i < quicksort_base_parametrization_upb; l_i++) {
      if (CDL2_LIST_GET(ckernel_kernel_data_data, l_i) > CDL2_LIST_GET(ckernel_kernel_data_data, l_i + 1)) {
         l_r = 0;
         break;
      }
   }
   return l_r == 1;
}


// ACTION show number+>number =
//    "printf($"%ld$", " number ");".
void ckernel_kernel_messages_shownumber(VALUE a_number) {
   printf("%ld", a_number);
}


// ACTION start timer =
//    start " = clock();".
void ckernel_kernel_timer_starttimer() {
   v_ckernel_kernel_timer_start = clock();
}


// TEST lt+>a+>b =
//    a " < " b.
BOOL ckernel_kernel_arithmetic_lt(VALUE a_a, VALUE a_b) {
   return a_a < a_b;
}


// FUNCTION halve+>a> =
//    a " /= 2;".
void ckernel_kernel_arithmetic_halve(VALUE *a_a) {
   *a_a /= 2;
}


// TEST smaller element+>p+>q =
//    "CDL2_LIST_GET(" data ", " p ") < CDL2_LIST_GET(" data ", " q ")".
BOOL ckernel_kernel_data_smallerelement(VALUE a_p, VALUE a_q) {
   return CDL2_LIST_GET(ckernel_kernel_data_data, a_p) < CDL2_LIST_GET(ckernel_kernel_data_data, a_q);
}


// FUNCTION decr+>a> =
//    a "--;".
void ckernel_kernel_arithmetic_decr(VALUE *a_a) {
   *a_a--;
}


// ACTION swap element+>i+>j =
//    "CDL2_LIST_SWAP(" data ", " i ", " j ");".
void ckernel_kernel_data_swapelement(VALUE a_i, VALUE a_j) {
   CDL2_LIST_SWAP(ckernel_kernel_data_data, a_i, a_j);
}


// ACTION stop timer =
//    stop " = clock();".
void ckernel_kernel_timer_stoptimer() {
   v_ckernel_kernel_timer_stop = clock();
}


// ACTION show elapsed time =
//    "printf($"Elapsed time: %.0f milliseconds\n$", (double)(" stop " - " start 
//    ") * 1000.0 / CLOCKS_PER_SEC);".
void ckernel_kernel_timer_showelapsedtime() {
   printf("Elapsed time: %.0f milliseconds\n", (double)(v_ckernel_kernel_timer_stop - v_ckernel_kernel_timer_start) * 1000.0 / CLOCKS_PER_SEC);
}


// ACTION sort data =
//    "$Lint cmp(const void *a, const void *b) { return (*(long*)a - *(long*)b); }" 
//    "$Lqsort(" data "_array, " upb " - " lwb " + 1, sizeof(long), cmp);".
void ckernel_kernel_data_sortdata() {
   int cmp(const void *a, const void *b) { return (*(long*)a - *(long*)b); }
   qsort(ckernel_kernel_data_data_array, quicksort_base_parametrization_upb - quicksort_base_parametrization_lwb + 1, sizeof(long), cmp);
}

/* ##### 12 Procedures ##### */



// ACTION initialize data -i -r -z :
//    add+const x+const x+z, subtract+upb+lwb+data size, incr+data size, make+i+lwb, 
//       (le+i+upb, random+min random+max random+r, set element+i+r, incr+i, *;
//        +).
void ckernel_kernel_data_initializedata() {
   VALUE l_i = 429518958  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   VALUE l_r = 1733181912  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   VALUE l_z = 905394972  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   /* Alternative 1 */
   ckernel_kernel_arithmetic_add(ckernel_kernel_arithmetic_constx, ckernel_kernel_arithmetic_constx, &l_z);
   ckernel_kernel_arithmetic_subtract(quicksort_base_parametrization_upb, quicksort_base_parametrization_lwb, &v_ckernel_kernel_data_datasize);
   ckernel_kernel_arithmetic_incr(&v_ckernel_kernel_data_datasize);
   ckernel_kernel_arithmetic_make(&l_i, quicksort_base_parametrization_lwb);
   /* Group */
   while (1) {
      /* Alternative 1 */
      if (!ckernel_kernel_arithmetic_le(l_i, quicksort_base_parametrization_upb)) return 0;
      ckernel_kernel_arithmetic_random(quicksort_base_parametrization_minrandom, quicksort_base_parametrization_maxrandom, &l_r);
      ckernel_kernel_data_setelement(l_i, l_r);
      ckernel_kernel_arithmetic_incr(&l_i);
      continue;
      /* End Alternative 1 */
      /* Alternative 2 */
      return 1;
      /* End Alternative 2 */
      break;
   }
   /* End Group */
   /* End Alternative 1 */
return;
}


// ACTION run demo -data size :
//    initialize data, dump data+"Data before sorting: ", verify data sorted+"Random", 
//       get data size+data size, show msg no newline+"Running quicksort on list of ", 
//          show number+data size, show msg+" elements.", start timer, quicksort+lwb+upb, stop timer, 
//             show elapsed time, dump data+"Data after sorting: ", verify data sorted+"Quicksort-ed", 
//             initialize data, show msg+"Running .NET sort on list.", start timer, sort data, 
//             stop timer, show elapsed time.
void quicksort_sort_sorter_rundemo() {
   VALUE l_datasize = 1922300791  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   /* Alternative 1 */
   ckernel_kernel_data_initializedata();
   ckernel_kernel_data_dumpdata("Data before sorting: ");
   quicksort_sort_sorter_verifydatasorted("Random");
   ckernel_kernel_data_getdatasize(&l_datasize);
   ckernel_kernel_messages_showmsgnonewline("Running quicksort on list of ");
   ckernel_kernel_messages_shownumber(l_datasize);
   ckernel_kernel_messages_showmsg(" elements.");
   ckernel_kernel_timer_starttimer();
   quicksort_sort_sorter_quicksort(quicksort_base_parametrization_lwb, quicksort_base_parametrization_upb);
   ckernel_kernel_timer_stoptimer();
   ckernel_kernel_timer_showelapsedtime();
   ckernel_kernel_data_dumpdata("Data after sorting: ");
   quicksort_sort_sorter_verifydatasorted("Quicksort-ed");
   ckernel_kernel_data_initializedata();
   ckernel_kernel_messages_showmsg("Running .NET sort on list.");
   ckernel_kernel_timer_starttimer();
   ckernel_kernel_data_sortdata();
   ckernel_kernel_timer_stoptimer();
   ckernel_kernel_timer_showelapsedtime();
   /* End Alternative 1 */
return;
}


// ACTION dump data*msg :
//    show msg no newline+msg, 
//       (le+data size+max size of list to show, dump list;
//        show msg+"too many elements to show.").
void ckernel_kernel_data_dumpdata(char *a_msg) {
   /* Alternative 1 */
   ckernel_kernel_messages_showmsgnonewline(a_msg);
   /* Group */
   while (1) {
      /* Alternative 1 */
      if (!ckernel_kernel_arithmetic_le(v_ckernel_kernel_data_datasize, quicksort_base_parametrization_maxsizeoflisttoshow)) return 0;
      ckernel_kernel_data_dumplist();
      /* End Alternative 1 */
      /* Alternative 2 */
      ckernel_kernel_messages_showmsg("too many elements to show.");
      /* End Alternative 2 */
      break;
   }
   /* End Group */
   /* End Alternative 1 */
return;
}


// ACTION verify data sorted*which :
//    is data sorted, show msg no newline+which, show msg+" data is sorted.";
//    show msg no newline+which, show msg+" data is not sorted.".
void quicksort_sort_sorter_verifydatasorted(char *a_which) {
   /* Alternative 1 */
   if (!quicksort_sort_sorter_isdatasorted()) return 0;
   ckernel_kernel_messages_showmsgnonewline(a_which);
   ckernel_kernel_messages_showmsg(" data is sorted.");
   /* End Alternative 1 */
   /* Alternative 2 */
   ckernel_kernel_messages_showmsgnonewline(a_which);
   ckernel_kernel_messages_showmsg(" data is not sorted.");
   /* End Alternative 2 */
return;
}


// PREDICATE is data sorted -where :
//    use macro for sortedness test, touch out+where, touch in+where, is data sorted macro;
//    is data unsorted procedure+where, show msg no newline+"Unsorted at ", show number+where, 
//       show msg+".", -;
//    +.
BOOL quicksort_sort_sorter_isdatasorted() {
   VALUE l_where = 2127565799  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   /* Alternative 1 */
   quicksort_base_touch_touchout(&l_where);
   quicksort_base_touch_touchin(l_where);
   if (!ckernel_kernel_data_isdatasortedmacro()) return 0;
   /* End Alternative 1 */
   /* Alternative 2 */
   /* Alternative suppressed by previous conditional compilation ON */
   /* End Alternative 2 */
   /* Alternative 3 */
   /* Alternative suppressed by previous conditional compilation ON */
   /* End Alternative 3 */
return 0;
}

// TEST use macro for sortedness test :
//    +.


// FUNCTION get data size+size> :
//    make+size+data size.
void ckernel_kernel_data_getdatasize(VALUE *a_size) {
   /* Alternative 1 */
   ckernel_kernel_arithmetic_make(&a_size, v_ckernel_kernel_data_datasize);
   /* End Alternative 1 */
return;
}


// ACTION quicksort+>from+>to -p -q :
//    less+from+to, split+from+to+p+q, quicksort+from+q, quicksort+p+to;
//    +.
void quicksort_sort_sorter_quicksort(VALUE a_from, VALUE a_to) {
   VALUE l_p = 27776622  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   VALUE l_q = 1744403178  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   /* Alternative 1 */
   if (!quicksort_base_arithmetic_less(a_from, a_to)) return 0;
   quicksort_sort_sorter_split(a_from, a_to, &l_p, &l_q);
   quicksort_sort_sorter_quicksort(a_from, l_q);
   quicksort_sort_sorter_quicksort(l_p, a_to);
   /* End Alternative 1 */
   /* Alternative 2 */
   return 1;
   /* End Alternative 2 */
return;
}


// TEST less+>a+>b :
//    lt+a+b.
BOOL quicksort_base_arithmetic_less(VALUE a_a, VALUE a_b) {
   /* Alternative 1 */
   if (!ckernel_kernel_arithmetic_lt(a_a, a_b)) return 0;
   /* End Alternative 1 */
return 0;
}


// ACTION split+>i+>j+p>+q> -m :
//    make+p+i, make+q+j, add+i+j+m, halve+m, 
//       (again:move p up+j+p+m, move q down+i+q+m, 
//          (less+p+q, swap element+p+q, incr+p, decr+q, *again;
//           less+p+m, swap element+p+m,  incr+p;
//           less+m+q, swap element+q+m,  decr+q;
//           +)).
void quicksort_sort_sorter_split(VALUE a_i, VALUE a_j, VALUE *a_p, VALUE *a_q) {
   VALUE l_m = 1540257566  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   /* Alternative 1 */
   ckernel_kernel_arithmetic_make(&a_p, a_i);
   ckernel_kernel_arithmetic_make(&a_q, a_j);
   ckernel_kernel_arithmetic_add(a_i, a_j, &l_m);
   ckernel_kernel_arithmetic_halve(&l_m);
   /* Group */
   while (1) {
      /* Alternative 1 */
      quicksort_sort_sorter_movepup(a_j, &a_p, l_m);
      quicksort_sort_sorter_moveqdown(a_i, &a_q, l_m);
      /* Group */
      while (1) {
         /* Alternative 1 */
         if (!quicksort_base_arithmetic_less(*a_p, *a_q)) return 0;
         ckernel_kernel_data_swapelement(*a_p, *a_q);
         ckernel_kernel_arithmetic_incr(&a_p);
         ckernel_kernel_arithmetic_decr(&a_q);
         continue;
         /* End Alternative 1 */
         /* Alternative 2 */
         if (!quicksort_base_arithmetic_less(*a_p, l_m)) return 0;
         ckernel_kernel_data_swapelement(*a_p, l_m);
         ckernel_kernel_arithmetic_incr(&a_p);
         /* End Alternative 2 */
         /* Alternative 3 */
         if (!quicksort_base_arithmetic_less(l_m, *a_q)) return 0;
         ckernel_kernel_data_swapelement(*a_q, l_m);
         ckernel_kernel_arithmetic_decr(&a_q);
         /* End Alternative 3 */
         /* Alternative 4 */
         return 1;
         /* End Alternative 4 */
         break;
      }
      /* End Group */
      /* End Alternative 1 */
      break;
   }
   /* End Group */
   /* End Alternative 1 */
return;
}


// FUNCTION move p up+>j+>p>+>m :
//    less+j+p;
//    smaller element+m+p;
//    incr+p, *.
void quicksort_sort_sorter_movepup(VALUE a_j, VALUE *a_p, VALUE a_m) {
   /* Alternative 1 */
   if (!quicksort_base_arithmetic_less(a_j, *a_p)) return 0;
   /* End Alternative 1 */
   /* Alternative 2 */
   if (!ckernel_kernel_data_smallerelement(a_m, *a_p)) return 0;
   /* End Alternative 2 */
   /* Alternative 3 */
   ckernel_kernel_arithmetic_incr(&a_p);
   continue;
   /* End Alternative 3 */
return;
}


// FUNCTION move q down+>i+>q>+>m :
//    less+q+i;
//    smaller element+q+m;
//    decr+q, *.
void quicksort_sort_sorter_moveqdown(VALUE a_i, VALUE *a_q, VALUE a_m) {
   /* Alternative 1 */
   if (!quicksort_base_arithmetic_less(*a_q, a_i)) return 0;
   /* End Alternative 1 */
   /* Alternative 2 */
   if (!ckernel_kernel_data_smallerelement(*a_q, a_m)) return 0;
   /* End Alternative 2 */
   /* Alternative 3 */
   ckernel_kernel_arithmetic_decr(&a_q);
   continue;
   /* End Alternative 3 */
return;
}

/* ##### 2 Synthetic Procedures ##### */


/* MOD c kernel LAY kernel SEC data ACTION PRELUDE */
void ckernel_kernel_data__PRELUDE() {
   /* Alternative 1 */
   ckernel_kernel_data_initializedata();
   /* End Alternative 1 */
return;
}

/* MOD quicksort LAY sort SEC sorter ACTION ROOT */
void quicksort_sort_sorter__ROOT() {
   /* Alternative 1 */
   quicksort_sort_sorter_rundemo();
   /* End Alternative 1 */
return;
}

// PROGRAM c sort.
//    PART c kernel, quicksort.
//    PRELUDE c kernel.
//    ROOT quicksort.
// ENDPROG c sort.
// 

int main(int argc, char *argv[])
{
   /* Program Ludes */
   /* Program Ludes */
   /* MOD c kernel PRELUDE */
   ckernel_kernel_data__PRELUDE();
   /* MOD quicksort ROOT */
   quicksort_sort_sorter__ROOT();
return 0;
}

# End PROG c sort
