//=============================================================================
// CDLTrace2.h - Provides the CDL2 debugger.
// This file is part of the CDL2 project and is included in 
// code generated by the C code genrator when-backtrace or -trace
// are set when generating code.
//=============================================================================
// cspell:ignore spypoint spypoints steppoint skippoint going jumping honour

#ifndef CDL2H
#include "CDL2.h"
#endif

#ifdef _WIN32
    #include <conio.h>
#else
    #include <termios.h>
    #include <unistd.h>
    #include <sys/select.h>
#endif

#include <string.h>
#include <signal.h>

#undef RETURNV
#undef RETURN
#define RETURNV(res) return c2TraceExit(res)
#define RETURN {c2TraceExit(TRUE);return;}

// #undef DECLARE_VAR
// #define DECLARE_VAR(sourceName,name,value) \
//    VALUE name = value;\
//    c2AddVar(sourceName,&name)

// #undef DECLARE_LIST
// #define DECLARE_LIST(sourceName,name, lwb, upb) \
//    VALUE name##_array[(upb) - (lwb) + 1]; \
//    VALUE name##_lwb = (lwb); \
//    VALUE name##_upb = (upb); \
//    c2AddList(sourceName,name##_array,lwb,upb)
    

#define VAL(aff) {.val=aff}
#define PTR(aff) {.ptr=aff}
#define STR(aff) {.str=aff}

/////////////////////////////////////////////////////////////////////////////////
// Types and data structures
/////////////////////////////////////////////////////////////////////////////////
typedef enum { C2_ALG_PREDICATE, C2_ALG_TEST, C2_ALG_ACTION, C2_ALG_FUNCTION } C2AlgType;
typedef enum { C2_DATA_VAR, C2_DATA_LIST } C2DataType;
typedef enum { C2_AFF_INPUT, C2_AFF_OUTPUT, C2_AFF_TRANSPUT, C2_AFF_STRING } C2AffType;
typedef enum { TRACE_ENTER, TRACE_EXIT, TRACE_FAIL, TRACE_ABORT } TraceExitType;

typedef union { VALUE val; VALUE* ptr; char* str; } C2DataValue;

typedef struct {
   C2AlgType type;
   char* name;
   int nargs;
   C2DataValue* args;
   char** argnames;
   C2AffType* affTypes;
   int nlocals;
   VALUE** locals;
   char** localnames;
   BOOL spypoint;
} C2StackFrame;

typedef struct C2ProcInfo {
   char* container;
   char* name;
   char* code;
   BOOL spypoint;
   BOOL steppoint;
} C2ProcInfo;

typedef struct C2VarInfo {
   char* name;
   VALUE* value;
} C2VarInfo;
typedef struct C2ListInfo {
   char* name;
   VALUE* value;
   int lwb;
   int upb;
   struct C2ListInfo* next;
} C2ListInfo;

/////////////////////////////////////////////////////////////////////////////////
// Globals
/////////////////////////////////////////////////////////////////////////////////
C2ProcInfo* C2Procs = NULL;
C2VarInfo* C2Vars = NULL;
C2ListInfo* C2Lists = NULL;

#define CALL_STACK_MAX_DEPTH 10000
C2StackFrame C2Stack[CALL_STACK_MAX_DEPTH];
int C2SP = -1;

BOOL C2HonorSpyPoints = FALSE;      // Whther to honour spy points while skipping.
int C2Skippoint= -1;                // The index of the stack frame we are skipping to (used to know when to stop skipping)
BOOL C2TraceWhileJumping = FALSE;   // Used to show trace output for intermediate calls while jumping or ...
BOOL C2Jumping = FALSE;             // Jumping means run until the next spy point
BOOL C2Going = FALSE;               // Going means run without further debugging


/////////////////////////////////////////////////////////////////////////////////
// Forward declarations
/////////////////////////////////////////////////////////////////////////////////
void c2PrintStackFrame(int depth, BOOL indent, char* marker, BOOL newline, TraceExitType type);
void c2TraceEnter();
int  c2TraceExit(int v);
void c2TraceExitAbort();
void c2traceREPL(int depth,TraceExitType type);
void c2PrintAff(int depth,int i, TraceExitType type);
void c2Backtrace();
void c2AddProc(const char* name, char* code);
void c2AddList(const char* name, VALUE* array, int lwb, int upb);
void c2AddVar(const char* name, VALUE* var);
C2ProcInfo* c2FindProc(char* name);
C2VarInfo* c2FindVar(char* name);
C2ListInfo* c2FindList(char* list);
BOOL c2SetSpyPoint(char* procName, BOOL set);

BOOL c2StartsWith(char* str, char* prefix);
BOOL c2MatchName(char* name1, char* name2);
char* c2RemoveBlanks(char* str);
BOOL c2IsemptyOrWhitespace(char* str);
void c2SignalHandler(int sig);
void c2InitTrace();
void c2Exit(int code);
char * c2ReadLine();

/////////////////////////////////////////////////////////////////////////////////
// Signal handler and exit wrapper - defined early so ALL code uses them
/////////////////////////////////////////////////////////////////////////////////
void c2SignalHandler(int sig) {
   fprintf(stderr, "\n*** CDL2 Runtime Error: Caught signal %d ***\n", sig);
   c2Backtrace();
   _Exit(sig);  // Use _Exit directly to avoid recursion
}

void c2InitTrace() {
   // Set up signal handlers to catch runtime errors
   signal(SIGSEGV, c2SignalHandler);  // Segmentation fault
   signal(SIGABRT, c2SignalHandler);  // Abort
   signal(SIGFPE,  c2SignalHandler);  // Floating point exception
   signal(SIGILL,  c2SignalHandler);  // Illegal instruction
#ifndef _WIN32
   signal(SIGBUS,  c2SignalHandler);  // Bus error (POSIX)
#endif
}

static void c2Exit(int code) {
   static BOOL exiting = FALSE;
   if (!exiting && code != 0 && C2SP >= 0) {
      exiting = TRUE;
      fprintf(stderr, "\n*** CDL2 Program exiting with code %d ***\n", code);
      c2Backtrace();
   }
   _Exit(code);
}

// Redefine exit() so all code below shows backtraces on errors
#define exit(code) c2Exit(code)

/////////////////////////////////////////////////////////////////////////////////
// Implementation
/////////////////////////////////////////////////////////////////////////////////
void c2AddProc(const char* name, char* code) {
   C2ProcInfo* newNode = malloc(sizeof(C2ProcInfo));
   if (newNode == NULL) {
      fprintf(stderr, "Out of memory\n");
      exit(1);
   }

   newNode->name = name;
   newNode->code = code;
   newNode->spypoint = FALSE;
   newNode->steppoint = FALSE;
   newNode->next = NULL;

   if (C2Procs == NULL) {
      C2Procs = newNode;
   } else {
      C2ProcInfo* p = C2Procs;
      while (p->next != NULL) p = p->next;
      p->next = newNode;
   }
}

void c2AddList(const char* name, VALUE* value, int lwb, int upb) {
   C2ListInfo* newNode = malloc(sizeof(C2ListInfo));
   if (newNode == NULL) {
      fprintf(stderr, "Out of memory\n");
      exit(1);
   }

   newNode->name = name;
   newNode->value = value;
   newNode->lwb = lwb;
   newNode->upb = upb;
   newNode->next = NULL;

   if (C2Lists == NULL) {
      C2Lists = newNode;
   } else {
      C2ListInfo* p = C2Lists;
      while (p->next != NULL) p = p->next;
      p->next = newNode;
   }
}

void c2AddVar(const char* name, VALUE* value) {
   C2VarInfo* newNode = malloc(sizeof(C2VarInfo));
   if (newNode == NULL) {
      fprintf(stderr, "Out of memory\n");
      exit(1);
   }

   newNode->name = name;
   newNode->value = value;
   newNode->next = NULL;

   if (C2Vars == NULL) {
      C2Vars = newNode;
   } else {
      C2VarInfo* p = C2Vars;
      while (p->next != NULL) p = p->next;
      p->next = newNode;
   }
}

C2ProcInfo* c2FindProc(char* name) {
   if (C2Procs == NULL) {
      fprintf(stderr, "C2Procs==NULL ... this is not possible");
      exit(1);
   }
   for (C2ProcInfo* p = C2Procs; p != NULL; p = p->next) {
      if (c2MatchName(name, p->name)) return p;
   }
   return NULL;
}

C2VarInfo* c2FindVar(char* name) {
   if (C2Vars == NULL) {
      fprintf(stderr, "C2Vars==NULL ... this is not possible");
      exit(1);
   }
   for (C2VarInfo* p = C2Vars; p != NULL; p = p->next) {
      if (c2MatchName(name, p->name)) return p;
   }
   return NULL;
}

C2ListInfo* c2FindList(char* name) {
   if (C2Lists == NULL) {
      fprintf(stderr, "C2Lists==NULL ... this is not possible");
      exit(1);
   }
   for (C2ListInfo* p = C2Lists; p != NULL; p = p->next) {
      if (c2MatchName(name, p->name)) return p;
   }
   return NULL;
}

BOOL c2StartsWith(char* str, char* prefix) {
   while (*prefix != '\0') {
      if (*str != *prefix) {
         return FALSE;
      }
      str++;
      prefix++;
   }
   return TRUE;
}

BOOL c2MatchName(char* name1, char* name2) {
   char* clean1 = c2RemoveBlanks(name1);
   char* clean2 = c2RemoveBlanks(name2);
   BOOL result = c2StartsWith(clean1, clean2);
   free(clean1);
   free(clean2);
   return result;
}

char* c2RemoveBlanks(char* str) {
   // First pass: count non-blank characters
   int count = 0;
   for (char* src = str; *src != '\0'; src++) {
      if (*src != ' ') count++;
   }

   // Allocate exactly what we need
   char* result = (char*)malloc(count + 1);
   if (result == NULL) {
      return NULL; // Memory allocation failed
   }

   // Second pass: copy non-blank characters
   char* dst = result;
   for (char* src = str; *src != '\0'; src++) {
      if (*src != ' ') *dst++ = *src;
   }
   *dst = '\0';
   return result;
}

BOOL c2IsemptyOrWhitespace(char* str) {
   for (char* p = str; *p != '\0'; p++) {
      if (*p != ' ' && *p != '\t' && *p != '\n' && *p != '\r') {
         return FALSE;
      }
   }
   return TRUE;
}

// Read line until Enter
char* c2ReadLine() {
    static char buffer[256];
    int i = 0;
    int ch;
    while (i < 255 && (ch = getchar()) != '\n' && ch != '\r' && ch != EOF) {
        buffer[i++] = ch;
    }
    buffer[i] = '\0';
    return buffer;
}

// Cross-platform immediate character input
char c2_getch() {
#ifdef _WIN32
    return _getch();
#else
    struct termios oldattr, newattr;
    char ch;
    tcgetattr(STDIN_FILENO, &oldattr);
    newattr = oldattr;
    newattr.c_lflag &= ~(ICANON | ECHO);
    tcsetattr(STDIN_FILENO, TCSANOW, &newattr);
    ch = getchar();
    tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
    return ch;
#endif
}

// Special key codes
#define KEY_END 1001
#define KEY_HOME 1002
#define KEY_UP 1003
#define KEY_DOWN 1004
#define KEY_LEFT 1005
#define KEY_RIGHT 1006
#define KEY_ESC 27

// Cross-platform special key detection
int c2_get_special_key() {
#ifdef _WIN32
    int ch = _getch();
    if (ch == 224) { // Extended key prefix on Windows
        ch = _getch();
        switch (ch) {
            case 79: return KEY_END;     // END key
            case 71: return KEY_HOME;    // HOME key
            case 72: return KEY_UP;      // UP arrow
            case 80: return KEY_DOWN;    // DOWN arrow
            case 75: return KEY_LEFT;    // LEFT arrow
            case 77: return KEY_RIGHT;   // RIGHT arrow
        }
    }
    return ch; // Regular character
#else
    struct termios oldattr, newattr;
    int ch;
    tcgetattr(STDIN_FILENO, &oldattr);
    newattr = oldattr;
    newattr.c_lflag &= ~(ICANON | ECHO);
    tcsetattr(STDIN_FILENO, TCSANOW, &newattr);
    
    ch = getchar();
    if (ch == 27) { // ESC sequence
        // Set a short timeout to check if more characters are coming
        fd_set readfds;
        struct timeval timeout;
        FD_ZERO(&readfds);
        FD_SET(STDIN_FILENO, &readfds);
        timeout.tv_sec = 0;
        timeout.tv_usec = 100000; // 100ms timeout
        
        if (select(STDIN_FILENO + 1, &readfds, NULL, NULL, &timeout) > 0) {
            // More characters available - it's an escape sequence
            ch = getchar();
            if (ch == '[') {
                ch = getchar();
                switch (ch) {
                    case 'F': 
                        tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
                        return KEY_END;    // END key
                    case 'H': 
                        tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
                        return KEY_HOME;   // HOME key  
                    case 'A': 
                        tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
                        return KEY_UP;     // UP arrow
                    case 'B': 
                        tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
                        return KEY_DOWN;   // DOWN arrow
                    case 'D': 
                        tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
                        return KEY_LEFT;   // LEFT arrow
                    case 'C': 
                        tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
                        return KEY_RIGHT;  // RIGHT arrow
                    case '4': 
                        if (select(STDIN_FILENO + 1, &readfds, NULL, NULL, &timeout) > 0 && getchar() == '~') {
                            tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
                            return KEY_END; // Alternative END key sequence
                        }
                        break;
                }
            }
        } else {
            // Timeout - it's just ESC pressed alone
            tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
            return KEY_ESC;
        }
    }
    tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
    return ch; // Regular character
#endif
}


char* c2AlgType(int depth) {
   switch (C2Stack[depth].type) {
      case C2_ALG_PREDICATE: return "PREDICATE";
      case C2_ALG_TEST: return "TEST";
      case C2_ALG_ACTION: return "ACTION";
      case C2_ALG_FUNCTION: return "FUNCTION";
      default: return "UNKNOWN";
   }
}  

void c2push_callstack_frame(C2AlgType type, char* name, 
   int nargs, C2DataValue args[], char* argnames[], C2AffType affTypes[],
   int nlocals, VALUE* locals[], char* localnames[]) {
      if (C2SP >= CALL_STACK_MAX_DEPTH-1) {
         fprintf(stderr, "Call stack overflow\n");
         exit(1);
      }
      C2SP++;
      C2Stack[C2SP].type = type;
      C2Stack[C2SP].name = name;
      C2Stack[C2SP].nargs = nargs;
      C2Stack[C2SP].args = args;
      C2Stack[C2SP].argnames = argnames;
      C2Stack[C2SP].affTypes = affTypes;
      C2Stack[C2SP].nlocals = nlocals;
      C2Stack[C2SP].locals = locals;
      C2Stack[C2SP].localnames = localnames;
}

void c2pop_callstack_frame() {
   if (C2SP < 0) {
      fprintf(stderr, "Call stack underflow\n");
      exit(1);
   }
   C2SP--;
}
   
#define ENTER_MARKER ">"
#define SUCCEED_MARKER "+"
#define FAIL_MARKER "-"
#define NO_MARKER ""

char * C2Marker(TraceExitType type) {
   switch (type) {
      case TRACE_ENTER: return ENTER_MARKER;
      case TRACE_EXIT: return SUCCEED_MARKER;
      case TRACE_FAIL: return FAIL_MARKER;
      default: return NO_MARKER;
   }
}

void c2Backtrace() {
   fprintf(stderr, "Call stack (most recent call last):\n");
   for (int i = C2SP - 1; i >= 0; i--) {
      c2PrintStackFrame(i,FALSE,NO_MARKER,TRUE,TRACE_EXIT);
   }
}   
   
void c2PrintStackFrame(int depth,BOOL indent, char* marker,BOOL newline,TraceExitType type) {
   static char indentation_buffer[256];
   char * indentation = "";
   if (indent) {
      sprintf(indentation_buffer, "%*s", depth, "");
      indentation = indentation_buffer;
   }
   if (!newline) fprintf(stderr,"\n"); // Print a newline before the stack frame when used as debugger prompt
   fprintf(stderr, "%s%s%s %s",indentation,marker,c2AlgType(depth),C2Stack[depth].name);
   if (type != TRACE_FAIL) for (int i = 0; i < C2Stack[depth].nargs; i++) c2PrintAff(depth, i,type);
   fprintf(stderr,newline ? "\n" : ": ");
}

void c2PrintAff(int depth,int i, TraceExitType type) {
   char* name = C2Stack[depth].argnames[i];
      switch (C2Stack[depth].affTypes[i]) {
      case C2_AFF_INPUT:    fprintf(stderr, "+>%s=%ld", name,C2Stack[depth].args[i].val); break;
      case C2_AFF_OUTPUT:   
         if (type == TRACE_ENTER) {
            fprintf(stderr, "+%s>",name);
         } else {
            fprintf(stderr, "+%s>=%ld",name,*C2Stack[depth].args[i].ptr);
         }
         break;
      case C2_AFF_TRANSPUT: fprintf(stderr, "+>%s>=%ld",name,*C2Stack[depth].args[i].ptr); break;
      case C2_AFF_STRING:   fprintf(stderr, "*%s=%s",   name,C2Stack[depth].args[i].str); break;
      default: fprintf(stderr, "+??");
   }
}

// Called after c2_push_callstack_frame so call information is on the stack.
BOOL firstEntry = TRUE;
void c2TraceEnter() {
   if (firstEntry) {
      c2InitTrace();  // Initialize signal handlers on first entry
      fprintf(stderr, "CDL2 debugger v1.0, h for help\n");
      firstEntry = FALSE;
   }
   if (C2Going) {
      // If we are going, just return without showing trace output
      return;
   }
   if (C2Skippoint >=0) {
      // We are skipping
      if (C2HonorSpyPoints && C2Stack[C2SP].spypoint) {
         // Skipping, but we are honouring spy points and this is a spy point: need to stop
         C2Skippoint = -1; // Stop skipping when we hit a spy point
         C2HonorSpyPoints= FALSE; // Because spypoint honouring applies only to skipping and is irrelevant otherwise.
      } else {
         // Otherwise, just continue without stopping
         return; 
      }
   } else if (C2Stack[C2SP].spypoint) {
      // We are not skipping, and this is a spy point.
      C2HonorSpyPoints= FALSE; // Should already be false as we are not skipping.
      C2Jumping = FALSE; // Because we are stopping at the spy point, we are no longer jumping.
      return; 
   }
   if (C2Jumping) {
      // We are jumping, but this is not a spy point.
      return;
   }
   // Not skipping
   c2traceREPL(C2SP, TRACE_ENTER);
}
// Called without popping the stack, so it must do it.
int c2TraceExit(int v) {
   if (C2Going) {
      // If we are going, just return without showing trace output
      return v;
   }
   if (C2Skippoint >=0) {
      // We are skipping
      if (C2Skippoint == C2SP) {
         // We have reached the point we wanted to skip to, so stop skipping
         C2Skippoint = -1;
         C2HonorSpyPoints = FALSE; // Because spypoint honouring applies only to skipping and is irrelevant otherwise.
         c2traceREPL(C2SP, v==FALSE ? TRACE_FAIL : TRACE_EXIT);
      }
   //} else if (C2Stack[C2SP].spypoint) {
      // Do spypoints apply to exits? for now, no.
   }
   if (!C2Jumping) {
      // We are not jumping, so stop
      c2traceREPL(C2SP, v==FALSE ? TRACE_FAIL : TRACE_EXIT);
   }
   c2pop_callstack_frame();
   return v;
}
// Called for the abort operator
void c2TraceExitAbort() {
   fprintf(stderr, "Abort operator reached\n");
   c2Backtrace();
   exit(1);
}

void c2traceREPL(int depth,TraceExitType type) {
   c2PrintStackFrame(depth,TRUE,C2Marker(type),FALSE,type);
   char command = c2_getch();
   switch (command) {
      case 'h':
         fprintf(stderr, "Commands:\n");
         fprintf(stderr, "  ENTER - continue until the next trace point\n");
         fprintf(stderr, "  j SPC - continue until the next spy point\n");
         fprintf(stderr, "  g END - continue until the end\n");
         fprintf(stderr, "  s TAB - step to the next trace point\n");
         fprintf(stderr, "  b     - show a backtrace of the call stack\n");
         fprintf(stderr, "  + -   - set or clear a spy point\n");
         fprintf(stderr, "  q ESC - quit the program\n");
         c2traceREPL(depth,type); // After showing help, ask for command again
         break;
      case '+':
      case '-':
         char* procName = c2ReadLine();
         if (c2IsemptyOrWhitespace(procName)) {
            fprintf(stderr, "Procedure name cannot be empty\n");
         } else if (c2SetSpyPoint(procName, command == '+')) {
            fprintf(stderr, "Spy point %s %s\n", command == '+' ? "set on" : "cleared from", procName);
         } else {
            fprintf(stderr, "No such procedure %s\n", procName);
         }
         c2traceREPL(depth,type); // After setting spy point, ask for command again
         break;
      case '\r':
         break;
      case KEY_END:
      case 'g':
         C2Going = TRUE;
         break;
      case ' ':
      case 'j':
         C2Jumping = TRUE;
         break;
      case '\t':
      case 's':
         // skip
         C2Skippoint = depth; // Skip until we return to the current stack frame
         break;
      case 'b':
         c2Backtrace();
         c2traceREPL(depth,type); // After showing backtrace, ask for command again
         break;
      case KEY_ESC:
      case 'q':
         exit(0);
         break;
      default:
         fprintf(stderr, "Invalid command. enter 'h' for help.\n");
         c2traceREPL(depth,type); // After invalid command, ask for command again
         break;
   }
}
