//=============================================================================
// CDLTrace2.h - Provides the CDL2 debugger.
// This file is part of the CDL2 project and is included in 
// code generated by the C code genrator when-backtrace or -trace
// are set when generating code.
//=============================================================================
// cspell:ignore spypoint spypoints steppoint skippoint going jumping honour

#define _CRT_SECURE_NO_WARNINGS
// #define SHOW_STACK_RESIZE
#ifndef CDL2H
#include "CDL2.h"
#endif

#ifdef _WIN32
    #include <conio.h>
    // Declare Windows API function to avoid including windows.h which conflicts with BOOL
    #ifdef __cplusplus
    extern "C" {
    #endif
    __declspec(dllimport) unsigned long __stdcall GetModuleFileNameA(void* hModule, char* lpFilename, unsigned long nSize);
    #ifdef __cplusplus
    }
    #endif
#else
    #include <termios.h>
    #include <unistd.h>
    #include <sys/select.h>
#endif

#include <string.h>
#include <signal.h>
#include <ctype.h>

#undef ENTER
#undef RETURNV
#undef RETURN
// Redefine control constructs to hook into trace.
// If code was generated with -trace call c2trace exit which takes care of poping the stack.
// Otherwise code was generated with backtrace only, so the stack must be poped.
#ifdef CDL2TRACE
   #define ENTER(index,affixes,locals) { c2push_callstack_frame(index,affixes,locals); c2TraceEnter(); }
#elif defined(CDL2PROFILE)
   #define ENTER(index,affixes,locals) { c2push_callstack_frame(index,affixes,locals); c2DebugInfo->procs[index].callCount++; }
#else
   #define ENTER(index,affixes,locals) c2push_callstack_frame(index,affixes,locals);
#endif
#ifdef CDL2TRACE
   #define RETURNV(v)                  { c2TraceExit(v);    c2pop_callstack_frame(); return v; }
   #define RETURN                      { c2TraceExit(TRUE); c2pop_callstack_frame(); return;   }

   #undef ABORT
   #define ABORT(msg,index) c2TraceExitAbort(msg)
#else
   #define RETURNV(v) { c2pop_callstack_frame(); return v; }
   #define RETURN     { c2pop_callstack_frame(); return;   }
#endif


// Cross-platform warning suppression macros for use inside functions
#define STRINGIFY_HELPER(x) #x
#define STRINGIFY(x) STRINGIFY_HELPER(x)

#if defined(_MSC_VER)
#define WARNING_SUPPRESS(msvc_num, gcc_name) __pragma(warning(push)) __pragma(warning(disable:msvc_num))
#define WARNING_RESTORE(msvc_num, gcc_name) __pragma(warning(pop))
#elif defined(__clang__)
#define WARNING_SUPPRESS(msvc_num, gcc_name) _Pragma("clang diagnostic push") _Pragma(STRINGIFY(clang diagnostic ignored gcc_name))
#define WARNING_RESTORE(msvc_num, gcc_name) _Pragma("clang diagnostic pop")
#elif defined(__GNUC__)
#define WARNING_SUPPRESS(msvc_num, gcc_name) _Pragma("GCC diagnostic push") _Pragma(STRINGIFY(GCC diagnostic ignored gcc_name))
#define WARNING_RESTORE(msvc_num, gcc_name) _Pragma("GCC diagnostic pop")
#else
#define WARNING_SUPPRESS(msvc_num, gcc_name)
#define WARNING_RESTORE(msvc_num, gcc_name)
#endif

#define VAL(aff) {.val=aff}
#define PTR(aff) {.ptr=aff}
#define STR(aff) {.str=aff}

// Special key codes
#define KEY_END 1001
#define KEY_HOME 1002
#define KEY_UP 1003
#define KEY_DOWN 1004
#define KEY_LEFT 1005
#define KEY_RIGHT 1006
#define KEY_DELETE 1007
#define KEY_F1 1008
#define KEY_ESC 27

#define bool char
#define true 1
#define false 0

/////////////////////////////////////////////////////////////////////////////////
// Types and data structures
/////////////////////////////////////////////////////////////////////////////////
typedef enum { C2_ALG_PREDICATE, C2_ALG_TEST, C2_ALG_ACTION, C2_ALG_FUNCTION } C2AlgType;
typedef enum { C2_AFF_INPUT, C2_AFF_OUTPUT, C2_AFF_TRANSPUT, C2_AFF_STRING } C2AffType;
typedef enum { TRACE_ENTER, TRACE_EXIT, TRACE_FAIL, TRACE_ABORT } TraceExitType;

typedef enum {
   BLACK = 30, RED = 31, GREEN = 32, YELLOW = 33, BLUE = 34, MAGENTA = 35, CYAN = 36, WHITE = 37, RESET = 38, 
   BRIGHT_BLACK = 90, BRIGHT_RED = 91, BRIGHT_GREEN = 92, BRIGHT_YELLOW = 93, BRIGHT_BLUE = 94, BRIGHT_MAGENTA = 95, BRIGHT_CYAN = 96, BRIGHT_WHITE = 97
} AnsiColor;


typedef union { VALUE val; VALUE* ptr; char* str; } C2DataValue;

typedef struct {
   int            procInfoIndex;
   C2DataValue*   args;
   VALUE**        locals;
   bool           spypoint;
} C2StackFrame;

typedef struct C2ProcInfo {
   char*       container;
   char*       name;
   C2AlgType   type;                                                                                               
   int         nargs;
   char**      argnames;
   C2AffType*  affTypes;
   int         nlocals;
   char**      localnames;
   char*       code;
   bool        spypoint;
   bool        steppoint;
   VALUE       callCount;
} C2ProcInfo;

typedef struct C2VarInfo {
   char*    container;
   char*    name;
   VALUE*   value;
} C2VarInfo;
typedef struct C2ListInfo {
   char*    container;
   char*    name;
   VALUE*   value;
   int      lwb;
   int      upb;
} C2ListInfo;

typedef struct C2DebugInfo {
   int         procCount;
   C2ProcInfo* procs;
   int         varCount;
   C2VarInfo*  vars;
   int         listCount;
   C2ListInfo* lists;
} C2DebugInfo;

typedef struct {
   VALUE* values;
   int count;
   bool needsFree;
   bool onePerLine;
   int startIndex;
   char* listName;
   int lwb;
   int upb;
   bool freeListName;
} C2EvalResult;

/////////////////////////////////////////////////////////////////////////////////
// Globals
/////////////////////////////////////////////////////////////////////////////////
C2DebugInfo* c2DebugInfo;

#ifndef CALL_STACK_MAX_DEPTH
#define CALL_STACK_MAX_DEPTH 10000
#endif
C2StackFrame* C2Stack = NULL;
VALUE C2SP = -1;
VALUE C2StackCapacity = 0;

bool C2HonorSpyPoints = false;      // Whether to honour spy points while skipping.
VALUE C2Skippoint= -1;              // The index of the stack frame we are skipping to (used to know when to stop skipping)
bool C2TraceWhileJumping = false;   // Used to show trace output for intermediate calls while jumping or ...
bool C2Jumping = false;             // Jumping means run until the next spy point
bool C2Going = false;               // Going means run without further debugging
// Temporary spy points for 'r' command
#define C2_MAX_TEMP_SPYPOINTS 100
int C2TempSpyPoints[C2_MAX_TEMP_SPYPOINTS];  // Indices of procedures with temporary spy points
int C2TempSpyPointCount = 0;        // Number of temporary spy points set
// Saved settings
bool C2StepOverSuccess = true;      // Whether to step over the next exit
bool C2StepOverFailure = true;      // Whether to step over the next fail
bool C2FullNames = false;           // Whether to show full procedure names (including container) in stack frames, or just the procedure name
int  C2DefaultListElements = 10;    // Default number of LIST elements to display
int  C2Radix = 10;                  // The default radix for displaying numbers
int  C2BacktracePauseInterval = 20; // Number of stack frames to display before pausing

// Command history
#define C2_HISTORY_SIZE 100
char* C2CommandHistory[C2_HISTORY_SIZE];
int C2HistoryCount = 0;
int C2HistoryIndex = 0;


/////////////////////////////////////////////////////////////////////////////////
// Forward declarations
/////////////////////////////////////////////////////////////////////////////////
void c2push_callstack_frame(int procIndex, C2DataValue args[], VALUE** locals);
void c2pop_callstack_frame();
void c2PrintStackFrame(VALUE depth, bool indent, char* marker, char* lineEnd, TraceExitType type);
void c2TraceEnter();
void c2TraceExit(int v);
void c2TraceExitAbort(char* algName);
void c2traceREPL(VALUE depth,TraceExitType type);
void c2PrintAffixes(VALUE depth, TraceExitType type);
void c2PrintAff(VALUE depth,int i, TraceExitType type);
void c2PrintLocals(VALUE depth);
void c2Backtrace();
int c2GenericFind(char* name, int count, char* (*getNameFunc)(int index));
int* c2GenericFindAll(char* name, int count, char* (*getNameFunc)(int index), int* outCount);
C2ProcInfo* c2FindProc(char* name);
C2ProcInfo** c2FindProcs(char* name, int* outCount);
C2VarInfo* c2FindVar(char* name);
C2VarInfo** c2FindVars(char* name, int* outCount);
C2ListInfo* c2FindList(char* list);
C2ListInfo** c2FindLists(char* name, int* outCount);
bool c2SetSpyPoint(char* procName, bool set);
bool c2IsSpyPoint(int procIndex);

bool c2StartsWith(char* str, char* prefix);
bool c2MatchName(char* name1, char* name2);
char* c2RemoveBlanks(char* str);
bool c2IsemptyOrWhitespace(char* str);
C2EvalResult c2EvaluateExpr(VALUE depth, char* expr);
void c2PrintValues(C2EvalResult* result, char format);
void c2FreeEvalResult(C2EvalResult* result);
void c2SignalHandler(int sig);
void c2InitTrace();
void c2Exit(int code);
char * c2ReadLine();
char* c2ReadLineWithHistory();
char* c2ReadFullCommand();
void c2AddToHistory(char* cmd);
void c2SaveDebugState();
void c2LoadDebugState();
char* c2GetExecutablePath();
char c2_getch();
int c2_get_special_key();
char* ansi_fg(AnsiColor color);
char* ansi_bg(AnsiColor color);
bool c2IsLude(char* name);
char* c2FormatContainer(char* container);



/////////////////////////////////////////////////////////////////////////////////
// Redefine exit() so all code below shows backtraces on errors
/////////////////////////////////////////////////////////////////////////////////
#define exit(code) c2Exit(code)

/////////////////////////////////////////////////////////////////////////////////
// Implementation
/////////////////////////////////////////////////////////////////////////////////

char* c2AlgType(VALUE depth) {
   switch (c2DebugInfo->procs[C2Stack[depth].procInfoIndex].type) {
      case C2_ALG_PREDICATE: return "PREDICATE";
      case C2_ALG_TEST: return "TEST";
      case C2_ALG_ACTION: return "ACTION";
      case C2_ALG_FUNCTION: return "FUNCTION";
      default: return "UNKNOWN";
   }
}  

void c2push_callstack_frame(int procIndex,C2DataValue args[],VALUE** locals) {
   C2SP++;

   if (C2SP >= (int)C2StackCapacity) {
      VALUE newCapacity = C2StackCapacity == 0 ? CALL_STACK_MAX_DEPTH : C2StackCapacity * 2;

      VALUE bytesNeeded = newCapacity * sizeof(C2StackFrame);
      if (((VALUE)bytesNeeded / (VALUE)sizeof(C2StackFrame)) != newCapacity) {
         fprintf(stderr, "Call stack size overflow detected (would exceed addressable memory)\n");
         exit(1);
      }

      WARNING_SUPPRESS(4244, "-Wcast-function-type")
      C2StackFrame* newStack = (C2StackFrame*)realloc(C2Stack, bytesNeeded);
      WARNING_RESTORE(4244, "-Wcast-function-type")
      if (newStack == NULL) {
         fprintf(stderr, "Call stack allocation failed, attempted %llu frames (%llu bytes)\n", newCapacity, bytesNeeded);
         exit(1);
#ifdef SHOW_STACK_RESIZE
      } else {
         fprintf(stderr, "Call stack reallocated to %zu frames (%zu bytes) (%llu bytes)\n", newCapacity,sizeof(C2StackFrame),bytesNeeded);
#endif
      }
      C2Stack = newStack;
      C2StackCapacity = newCapacity;
   }

   C2Stack[C2SP].procInfoIndex = procIndex;
   C2Stack[C2SP].args = args;
   C2Stack[C2SP].locals = locals;
   C2Stack[C2SP].spypoint = false;
}

void c2pop_callstack_frame() {
   if (C2SP < 0) {
      fprintf(stderr, "Call stack underflow\n");
      exit(1);
   }
   C2SP--;
}

bool c2SetSpyPoint(char* procName, bool set) {
   int count = 0;
   C2ProcInfo** procs = c2FindProcs(procName, &count);
   if (procs != NULL) {
      for (int i = 0; i < count; i++) {
         procs[i]->spypoint = set;
         fprintf(stderr, "Spy point %s %s%s%s\n", set ? "set on" : "cleared from", ansi_fg(YELLOW), procs[i]->name, ansi_fg(RESET));
      }
      free(procs);
      return true;
   } else {
      return false;
   }
}

bool c2IsSpyPoint(int procIndex) {
   return c2DebugInfo->procs[procIndex].spypoint;
}
   
#define ENTER_MARKER ">"
#define SUCCEED_MARKER "+"
#define FAIL_MARKER "-"
#define NO_MARKER ""

char * C2Marker(TraceExitType type) {
   static char buffer[8];
   
   switch (type) {
   case TRACE_ENTER:   sprintf(buffer, "%s%s", ansi_fg(CYAN), ENTER_MARKER); break;
      case TRACE_EXIT: sprintf(buffer, "%s%s", ansi_fg(GREEN), SUCCEED_MARKER); break;
      case TRACE_FAIL: sprintf(buffer, "%s%s", ansi_fg(RED), FAIL_MARKER); break;
      default: return NO_MARKER;
   }
   return buffer;
}

void c2Backtrace() {
   fprintf(stderr, "\n===== Stack backtrace (most recent call to last):\n");
   int frameCount = 0;
   for (VALUE i = C2SP ; i >= 0 ; i--) {
      c2PrintStackFrame(i,false,NO_MARKER,"\n", TRACE_ENTER);
      frameCount++;
      if (frameCount % C2BacktracePauseInterval == 0 && i > 0) {
         VALUE remaining = i;
         fprintf(stderr, "\n--- " VALUE_DEC_FORMAT " more frame % s.Continue(y, n) ? ", remaining, remaining == 1 ? "" : "s");
         char response = c2_getch();
         fprintf(stderr, "%c\n", response);
         if (response == 'n' || response == 'N') break;
      }
   }
   fprintf(stderr, "===== Backtrace ends\n\n");
}
   
void c2PrintStackFrame(VALUE depth,bool indent, char* marker,char* lineEnd,TraceExitType type) {
   C2StackFrame frame = C2Stack[depth];
   C2ProcInfo procInfo = c2DebugInfo->procs[frame.procInfoIndex];
   char* name= procInfo.name;
   if (C2FullNames || isupper(name[0])) {
      // If the procedure name starts with an uppercase letter, also show the container for better disambiguation of ludes.
      static char name_buffer[256];
      name = name_buffer;
      sprintf(name, "%s.%s", procInfo.container, procInfo.name);
   }
   static char indentation_buffer[256];
   char * indentation = "";
   if (indent) {
      sprintf(indentation_buffer, "%*s", depth < 20 ? (int)depth : 20, "");
      indentation = indentation_buffer;
   }
   fprintf(stderr, "%s%s%s %s",indentation,marker,c2AlgType(depth),name);
   if (type != TRACE_FAIL) {
      c2PrintAffixes(depth, type);
      c2PrintLocals(depth);
   }
   fprintf(stderr,"%s%s", ansi_fg(RESET), lineEnd);
}

void c2PrintAffixes(VALUE depth, TraceExitType type) {
   C2ProcInfo procInfo = c2DebugInfo->procs[C2Stack[depth].procInfoIndex];
   for (int i = 0; i < procInfo.nargs; i++) {
      c2PrintAff(depth, i, type);
   }
}

void c2PrintLocals(VALUE depth) {
   C2StackFrame frame = C2Stack[depth];
   C2ProcInfo procInfo = c2DebugInfo->procs[frame.procInfoIndex];
   for (int i = 0; i < procInfo.nlocals; i++) {
      VALUE value = *(VALUE*)frame.locals[i];
      if (value == VALUE_UNDEFINED) {
         fprintf(stderr, " -%s=?",procInfo.localnames[i]);
      } else {
         fprintf(stderr, C2Radix == 16 ? FMT(" -%s=" VALUE_HEX_FORMAT) : FMT(" -%s=" VALUE_DEC_FORMAT), procInfo.localnames[i], value);
      }
   }
}

void c2PrintAff(VALUE depth,int i, TraceExitType type) {
   C2StackFrame frame = C2Stack[depth];
   C2ProcInfo procInfo = c2DebugInfo->procs[frame.procInfoIndex];
   char* name = procInfo.argnames[i];
   switch (procInfo.affTypes[i]) {
      case C2_AFF_INPUT:    fprintf(stderr, C2Radix == 16 ? FMT(" +>%s=" VALUE_HEX_FORMAT) : FMT(" +>%s=" VALUE_DEC_FORMAT), name,frame.args[i].val); break;
      case C2_AFF_OUTPUT:   
         if (type == TRACE_ENTER) {
            fprintf(stderr, " +%s>=?",name);
         } else {
            fprintf(stderr, C2Radix == 16 ? FMT(" +%s>=" VALUE_HEX_FORMAT) : FMT(" +%s>=" VALUE_DEC_FORMAT) ,name,*frame.args[i].ptr);
         }
         break;
      case C2_AFF_TRANSPUT: fprintf(stderr, C2Radix == 16 ? FMT(" +>%s>=" VALUE_HEX_FORMAT) : FMT(" +>%s>=" VALUE_DEC_FORMAT),name,*frame.args[i].ptr); break;
      case C2_AFF_STRING:   fprintf(stderr, " *%s=\"%s\"",   name,frame.args[i].str); break;
      default: fprintf(stderr, " +??");
   }
}

bool firstEntry = true;
/////////////////////////////////////////////////////////////////////////////
void c2TraceEnter() {
/////////////////////////////////////////////////////////////////////////////
// Called after c2_push_callstack_frame so call information is on the stack.
   if (firstEntry) {
      c2InitTrace();  // Initialize signal handlers on first entry
      c2LoadDebugState();  // Load saved debugger state
      fprintf(stderr, "%sCDL2 debugger v1.0, press %sh%s or %sF1%s for help%s\n\n", 
         ansi_fg(BRIGHT_MAGENTA), ansi_fg(YELLOW), ansi_fg(BRIGHT_MAGENTA), ansi_fg(YELLOW), ansi_fg(BRIGHT_MAGENTA), ansi_fg(RESET));
      firstEntry = false;
   }
#ifdef CDL2PROFILE
   c2DebugInfo->procs[C2Stack[C2SP].procInfoIndex].callCount++;
#endif
   if (C2Going) {
      // If we are going, just return without showing trace output
      return;
   }
   if (C2Skippoint >= 0) {
      if (C2Skippoint > C2SP) {
         // If we unwound past the skip point, cancel skipping
         C2Skippoint = -1;
      } else if (C2Skippoint == C2SP) {
         // We have reached the skip target, stop skipping and show REPL
         C2Skippoint = -1;
         C2HonorSpyPoints = false;
      } else if (C2HonorSpyPoints && C2Stack[C2SP].spypoint) {
         C2Skippoint = -1;
         C2HonorSpyPoints = false;
      } else {
         // Still skipping, do not show REPL
         return;
      }
   } else if (C2Jumping) {
      if (c2IsSpyPoint(C2Stack[C2SP].procInfoIndex)) {
         // We are not skipping, and this is a spy point.
         C2HonorSpyPoints = false; // Should already be false as we are not skipping.
         C2Jumping = false; // Because we are stopping at the spy point, we are no longer jumping.
         // Clear temporary spy points that were set by 'r' command
         for (int i = 0; i < C2TempSpyPointCount; i++) {
            c2DebugInfo->procs[C2TempSpyPoints[i]].spypoint = false;
         }
         C2TempSpyPointCount = 0;
      }else {
         // Jumping, but have not arrived yet
         return;
      }
   }
   // Not skipping
   c2traceREPL(C2SP, TRACE_ENTER);
}
/////////////////////////////////////////////////////////////////////////////
void c2TraceExit(int v) {
/////////////////////////////////////////////////////////////////////////////
// Called before  popping the stack.
   if (C2Going || C2Jumping) {
      // If we are going, just return without showing trace output
   } else if (C2Skippoint >=0) {
      // We are skipping
      if (C2Skippoint == C2SP) {
         // We have reached the point we wanted to skip to, so stop skipping
         C2Skippoint = -1;
         C2HonorSpyPoints = false; // Because spypoint honouring applies only to skipping and is irrelevant otherwise.
         if (v && C2StepOverSuccess) {
            c2PrintStackFrame(C2SP, true, C2Marker(TRACE_EXIT), "\n", TRACE_EXIT);
         } else if (!v && C2StepOverFailure) {
            c2PrintStackFrame(C2SP, true, C2Marker(TRACE_FAIL), "\n", TRACE_FAIL);
         } else {
            // We are stepping over, but this exit does not match our criteria to step over, so stop
            c2traceREPL(C2SP, v == false ? TRACE_FAIL : TRACE_EXIT);
         }
      }
   //} else if (C2Stack[C2SP].spypoint) {
      // Do spypoints apply to exits? for now, no.
   } else if (v && C2StepOverSuccess) {
      c2PrintStackFrame(C2SP, true, C2Marker(TRACE_EXIT), "\n", TRACE_EXIT);
   } else if (!v && C2StepOverFailure) {
      c2PrintStackFrame(C2SP, true, C2Marker(TRACE_FAIL), "\n", TRACE_FAIL);
   } else if (!C2Jumping) {
      // We are not jumping, so stop
      c2traceREPL(C2SP, v==false ? TRACE_FAIL : TRACE_EXIT);
   } else {
      // We are stepping over, but this exit does not match our criteria to step over, so stop
      c2traceREPL(C2SP, v==false ? TRACE_FAIL : TRACE_EXIT);
   }
}

// Called for the abort operator
void c2TraceExitAbort(char *algName) {
   fprintf(stderr, "\x1b[31mABORT in %s\x1b[0m\n", algName);
   c2Backtrace();
   exit(1);
}

// Helper function to check if a name is a lude (ludes have uppercase letters, normal algorithms are all lowercase)
bool c2IsLude(char* name) {
   return (bool)isupper(name[0]);
}

// Format container from "M.L.S" to "MOD M LAY L SEC S"
char* c2FormatContainer(char* container) {
   static char buffer[512];
   char temp[256];
   strncpy(temp, container, 255);
   temp[255] = '\0';

   char* parts[3] = {NULL, NULL, NULL};
   int partCount = 0;

   char* token = strtok(temp, ".");
   while (token != NULL && partCount < 3) {
      parts[partCount++] = token;
      token = strtok(NULL, ".");
   }

   buffer[0] = '\0';
   if (partCount >= 1) {
      strcat(buffer, "MOD ");
      strcat(buffer, parts[0]);
   }
   if (partCount >= 2) {
      strcat(buffer, " LAY ");
      strcat(buffer, parts[1]);
   }
   if (partCount >= 3) {
      strcat(buffer, " SEC ");
      strcat(buffer, parts[2]);
   }

   char* result = (char*)malloc(strlen(buffer) + 1);
   if (result != NULL) strcpy(result, buffer);
   return result;
}

void c2traceREPL(VALUE depth,TraceExitType type) {
   bool skipPrompt = false;
   while (1) {
      if (!skipPrompt) {
         c2PrintStackFrame(depth, true, C2Marker(type), ": ", type);
      }
      skipPrompt = false;

      // Read command (supports single keys AND history recall with up/down)
      char* fullCmd = c2ReadFullCommand();

      // Skip leading whitespace
      while (*fullCmd == ' ' || *fullCmd == '\t') fullCmd++;

      // First character is the command
      int command = fullCmd[0];
      char* arg = fullCmd + 1;
      // Skip space after command
      while (*arg == ' ' || *arg == '\t') arg++;

      // Add full commands to history (but not single-key navigation commands)
      if (command != '>' && command != 'g' && command != 'j' && 
          command != 's' && command != '<' && command != 'b' && command != 'q' && command != 'h') {
         c2AddToHistory(fullCmd);
      }

      switch (command) {
      case 'h': {
         // Erase the 'h' that was just typed
         fprintf(stderr, "\b \b");

#ifndef _WIN32
         // On Linux, save terminal state before entering help screen
         struct termios saved_termios;
         tcgetattr(STDIN_FILENO, &saved_termios);
#endif

         // Switch to alternate screen buffer
         fprintf(stderr, "\x1b[?1049h\x1b[H\x1b[2J");

         fprintf(stderr, "%sCDL2 Debugger Commands%s\n", ansi_fg(BRIGHT_MAGENTA), ansi_fg(RESET));
         fprintf(stderr, "================================================================================\n\n");

         fprintf(stderr, "%sNavigation Commands:%s\n", ansi_fg(BRIGHT_BLUE), ansi_fg(RESET));
         fprintf(stderr, "  %s>%s ENTER - continue until the next trace point (step into)\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "  %ss%s TAB   - continue to the exit of the current call (step over)\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "  %s<%s LEFT  - continue to the exit of the parent call (step out of parent)\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "  %sj%s SPC   - continue until the next spy point\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "  %sr%s       - run to algorithm prefix (temp spy point + jump) or dots to step out\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "            %s.%s (dot): step to current exit (like s)\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            %s..%s (two dots): step to parent exit (like <)\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            %s...%s (three dots): step to grandparent exit, etc.\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            %s<prefix>%s: run to algorithms matching prefix\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "  %sg%s END   - continue until the end\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "  %sb%s       - show a backtrace of the call stack\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "    %sUP/DN%s - at main prompt recall previous commands in history\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "  %sq%s ESC   - quit the program\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "  %sh%s F1    - show this help screen\n\n", ansi_fg(CYAN), ansi_fg(RESET));

         fprintf(stderr, "%sInspection Commands:%s\n", ansi_fg(BRIGHT_BLUE), ansi_fg(RESET));
         fprintf(stderr, "  %sd%s       - show arg in decimal\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "  %sx%s       - show arg in hex\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "  %sc%s       - show arg as character\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "            arg can be an affix, local, VAR, or LIST name\n");
         fprintf(stderr, "            %sLIST:%s [idx] [start:n] [start-end] [start:] [start-] [:end] [-end]\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "                  [] () - show %d elements (default count)\n", C2DefaultListElements);
         fprintf(stderr, "                  [start:] [start-] - show %d elements from start\n", C2DefaultListElements);
         fprintf(stderr, "                  [:end] [-end] - show %d elements up to end\n", C2DefaultListElements);
         fprintf(stderr, "                  [-] [:] - show ALL elements\n");
         fprintf(stderr, "                  (-) (:) - show ALL elements, one per line\n");
         fprintf(stderr, "                  [] for terse, () for one-per-line display\n");
         fprintf(stderr, "            %sPointer indirection:%s *ptr - dereference pointer\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            %sPointer indexing:%s *ptr[idx] *ptr(idx) - same syntax as LISTs (lwb=0)\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            %sSized pointer:%s >ptr[idx] >ptr(idx) - size from *ptr[-1], clamped\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "                           >ptr[-] >ptr[:] - show ALL elements\n");
         fprintf(stderr, "                           >ptr(-) >ptr(:) - show ALL elements, one per line\n\n");

         fprintf(stderr, "%sListing Commands:%s\n", ansi_fg(BRIGHT_BLUE), ansi_fg(RESET));
         fprintf(stderr, "  %sl%s       - list with 'a <prefix>' algorithms, 'v <prefix>' VARs,\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "            'l <prefix>' LISTs, 's <prefix>' spypoints, 'o' options, 'h' history\n");
         fprintf(stderr, "  %st%s       - show CDL2 source code of algorithm(s)\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "            no arg: current algorithm\n");
         fprintf(stderr, "            %s.%s (dot): current algorithm\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            %s..%s (two dots): parent caller\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            %s...%s (three dots): grandparent, etc.\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            %s<prefix>%s: algorithms matching prefix\n\n", ansi_fg(YELLOW), ansi_fg(RESET));

         fprintf(stderr, "%sConfiguration Commands:%s\n", ansi_fg(BRIGHT_BLUE), ansi_fg(RESET));
         fprintf(stderr, "  %s+/-%s     - set(+) or clear (-) a spy point, enter prefix(es) of algorithm name(s)\n", ansi_fg(CYAN), ansi_fg(RESET));
         fprintf(stderr, "            with argument %s+%s or %s-%s: stop or not at that exit (default: don't stop)\n", ansi_fg(YELLOW), ansi_fg(RESET), ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            with argument %s=%s: show or not show full names (default: don't show, except ludes)\n", ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            with argument %s# <N>%s: set default list elements count; %s- #%s reset to 10\n", ansi_fg(YELLOW), ansi_fg(RESET), ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            with argument %s^%s: toggle radix (10/16); %s- ^%s reset to 10\n", ansi_fg(YELLOW), ansi_fg(RESET), ansi_fg(YELLOW), ansi_fg(RESET));
         fprintf(stderr, "            with argument %s.%s: %s- .%s clears command history\n\n", ansi_fg(YELLOW), ansi_fg(RESET), ansi_fg(YELLOW), ansi_fg(RESET));

         fprintf(stderr, "================================================================================\n");
         fprintf(stderr, "%sPress %sany key%s to return to the debugger prompt...%s", ansi_fg(BRIGHT_MAGENTA), ansi_fg(BRIGHT_YELLOW), ansi_fg(BRIGHT_MAGENTA), ansi_fg(RESET));
         fflush(stderr);

         // Wait for any key
#ifdef _WIN32
         _getch();
#else
         // Ensure terminal is in raw mode (non-canonical, no echo)
         struct termios help_termios;
         tcgetattr(STDIN_FILENO, &help_termios);
         help_termios.c_lflag &= ~(ICANON | ECHO);
         help_termios.c_cc[VMIN] = 1;
         help_termios.c_cc[VTIME] = 0;
         tcsetattr(STDIN_FILENO, TCSANOW, &help_termios);

         int ch = getchar();

         // If it's ESC, consume any following escape sequence characters
         if (ch == 27) {
            // Switch to non-blocking to check for more characters
            help_termios.c_cc[VMIN] = 0;
            help_termios.c_cc[VTIME] = 1; // 100ms timeout
            tcsetattr(STDIN_FILENO, TCSANOW, &help_termios);

            // Consume the rest of the escape sequence
            while ((ch = getchar()) != EOF) {
               // Keep reading until timeout or end of sequence
            }
         }
#endif

         // Switch back to main screen buffer
         fprintf(stderr, "\x1b[?1049l");

#ifndef _WIN32
         // On Linux, restore the saved terminal state from before help screen
         tcsetattr(STDIN_FILENO, TCSANOW, &saved_termios);
#endif
         skipPrompt = true;
         continue;
      }
      case '+':
      case '-':
         // Print newline for all other commands
         fprintf(stderr, "\n");
         if (c2IsemptyOrWhitespace(arg)) {
            fprintf(stderr, "Procedure name or option cannot be empty\n");
         } else if (arg[0] == '+') {
            C2StepOverSuccess = command == '-';
            fprintf(stderr, "Will %s stop at success ports\n", C2StepOverSuccess ? "not" : "");
         } else if (arg[0] == '-') {
            C2StepOverFailure = command == '-';
            fprintf(stderr, "Will %s stop at failure ports\n", C2StepOverFailure ? "not" : "");
         } else if (arg[0] == '=') {
            C2FullNames = command == '+';
            fprintf(stderr, "Will %s show full algorithm names\n", C2FullNames ? "now" : "no longer");
         } else if (arg[0] == '#') {
            if (command == '+') {
               // Parse the number after '#'
               char* numStr = arg + 1;
               while (*numStr == ' ' || *numStr == '\t') numStr++;
               if (*numStr == '\0') {
                  fprintf(stderr, "Number required after '#'\n");
               }
               else {
                  int newCount = atoi(numStr);
                  if (newCount <= 0) {
                     fprintf(stderr, "Invalid count: %d (must be positive)\n", newCount);
                  }
                  else {
                     C2DefaultListElements = newCount;
                     fprintf(stderr, "Default list elements set to %d\n", C2DefaultListElements);
                  }
               }
            } else {
               // Reset to default
               C2DefaultListElements = 10;
               fprintf(stderr, "Default list elements reset to 10\n");
            }
         } else if (arg[0] == '^') {
            if (command == '+') {
               // Toggle between 10 and 16
               C2Radix = (C2Radix == 10) ? 16 : 10;
               fprintf(stderr, "Default display radix set to %d\n", C2Radix);
            } else {
               // Reset to default
               C2Radix = 10;
               fprintf(stderr, "Default display radix set to 10\n");
            }
         } else if (arg[0] == '.' && command == '-') {
            // Clear command history
            for (int i = 0; i < C2HistoryCount; i++) {
               free(C2CommandHistory[i]);
               C2CommandHistory[i] = NULL;
            }
            C2HistoryCount = 0;
            fprintf(stderr, "Command history cleared\n");
         } else if (!c2SetSpyPoint(arg, command == '+')) {
            fprintf(stderr, "No such procedure %s\n", arg);
         }
         c2SaveDebugState();
         continue;
      case '>':
         fprintf(stderr, "\n");
         break;
      case 'g':
         fprintf(stderr, "\n");
         C2Going = true;
         break;
      case 'j':
         fprintf(stderr, "\n");
         C2Jumping = true;
         break;
      case 'r':
         fprintf(stderr, "\n");
         if (c2IsemptyOrWhitespace(arg)) {
            fprintf(stderr, "Algorithm prefix or dots cannot be empty\n");
            continue;
         } else {
            // Check if argument is a sequence of dots (for stepping out)
            char* p = arg;
            while (*p == ' ' || *p == '\t') p++;
            int dotCount = 0;
            while (*p == '.') {
               dotCount++;
               p++;
            }
            while (*p == ' ' || *p == '\t') p++;

            if (dotCount > 0 && *p == '\0') {
               // Argument is only dots - step out
               VALUE targetDepth = depth - (dotCount - 1);
               if (targetDepth < 0) {
                  fprintf(stderr, "Not enough call stack depth (only " VALUE_DEC_FORMAT " level(s) available)\n", depth + 1);
                  continue;
               } else if (type == TRACE_ENTER) {
                  C2Skippoint = targetDepth;
               } else {
                  fprintf(stderr, "Can only step out from ENTER points\n");
                  continue;
               }
            } else {
               // Regular argument - find matching procedures
               int count = 0;
               C2ProcInfo** procs = c2FindProcs(arg, &count);
               if (procs != NULL && count > 0) {
                  // Clear any previous temporary spy points
                  C2TempSpyPointCount = 0;

                  // Set spy points, tracking which are new
                  for (int i = 0; i < count; i++) {
                     int procIdx = (int)(procs[i] - c2DebugInfo->procs);
                     if (!procs[i]->spypoint) {
                        // This procedure didn't have a spy point, so set one temporarily
                        procs[i]->spypoint = true;
                        if (C2TempSpyPointCount < C2_MAX_TEMP_SPYPOINTS) {
                           C2TempSpyPoints[C2TempSpyPointCount++] = procIdx;
                        }
                     }
                  }
                  free(procs);

                  fprintf(stderr, "Running to '%s' (%d algorithm(s), %d temporary spy point(s))\n", 
                     arg, count, C2TempSpyPointCount);
                  C2Jumping = true;
               } else {
                  fprintf(stderr, "No algorithms found matching '%s'\n", arg);
                  continue;
               }
            }
         }
         break;
      case 's':
         fprintf(stderr, "\n");
         if (type == TRACE_ENTER) {
            C2Skippoint = depth;
         }
         break;
      case '<':
         fprintf(stderr, "\n");
         if (depth > 0) {
            C2Skippoint = depth - 1;
         } else {
            fprintf(stderr, "Already at top level\n");
            continue;
         }
         break;
      case 'b':
         fprintf(stderr, "\n");
         c2Backtrace();
         continue;
      case 'l':
         fprintf(stderr, "\n");
         if (c2IsemptyOrWhitespace(arg)) {
            // No argument - show summary with commands
            int spyCount = 0;
            for (int i = 0; i < c2DebugInfo->procCount; i++) {
               if (c2DebugInfo->procs[i].spypoint) spyCount++;
            }
            fprintf(stderr, "Summary:                 (Command to list)\n");
            fprintf(stderr, "  Algorithms: %-6d     l a <prefix>\n", c2DebugInfo->procCount);
            fprintf(stderr, "  VARs:       %-6d     l v <prefix>\n", c2DebugInfo->varCount);
            fprintf(stderr, "  LISTs:      %-6d     l l <prefix>\n", c2DebugInfo->listCount);
            fprintf(stderr, "  Spypoints:  %-6d     l s <prefix>\n", spyCount);
            fprintf(stderr, "  Options:               l o\n");
            fprintf(stderr, "  History:    %-6d     l h\n", C2HistoryCount);
         } else {
            char listType = arg[0];
            char* prefix = arg + 1;
            while (*prefix == ' ') prefix++;
            if (*prefix == '\0') prefix = "";

            if (listType == 'a') {
               int count = 0;
               C2ProcInfo** procs = c2FindProcs(prefix, &count);
               if (procs != NULL && count > 0) {
                  fprintf(stderr, "Found %d algorithm(s):\n", count);

                  // First pass: find maximum algorithm name length AND container component widths for alignment
                  int maxNameLen = 0;
                  int maxModLen = 0;
                  int maxLayLen = 0;
                  for (int i = 0; i < count; i++) {
                     int nameLen = (int)strlen(procs[i]->name);
                     if (nameLen > maxNameLen) maxNameLen = nameLen;

                     // Parse container to find max widths
                     char temp[256];
                     strncpy(temp, procs[i]->container, 255);
                     temp[255] = '\0';

                     char* parts[3] = {NULL, NULL, NULL};
                     int partCount = 0;
                     char* token = strtok(temp, ".");
                     while (token != NULL && partCount < 3) {
                        parts[partCount++] = token;
                        token = strtok(NULL, ".");
                     }

                     if (partCount >= 1 && (int)strlen(parts[0]) > maxModLen) maxModLen = (int)strlen(parts[0]);
                     if (partCount >= 2 && (int)strlen(parts[1]) > maxLayLen) maxLayLen = (int)strlen(parts[1]);
                  }

                  // Second pass: display with aligned columns, adding blank lines after ludes and between modules
                  char prevModule[256] = "";
                  bool wasLude = true; // Start assuming we're in ludes
                  for (int i = 0; i < count; i++) {
                     bool currentIsLude = c2IsLude(procs[i]->name);

                     // Add blank line when transitioning from ludes to non-ludes
                     if (i > 0 && wasLude && !currentIsLude) {
                        fprintf(stderr, "\n");
                     }

                     // Extract module name (part before first period) for non-ludes
                     if (!currentIsLude) {
                        char moduleName[256];
                        char* dot = strchr(procs[i]->container, '.');
                        if (dot != NULL) {
                           int len = (int)(dot - procs[i]->container);
                           if (len >= 256) len = 255;
                           strncpy(moduleName, procs[i]->container, len);
                           moduleName[len] = '\0';
                        } else {
                           strncpy(moduleName, procs[i]->container, 255);
                           moduleName[255] = '\0';
                        }

                        // Add blank line when module changes (only for non-ludes)
                        if (i > 0 && prevModule[0] != '\0' && strcmp(prevModule, moduleName) != 0) {
                           fprintf(stderr, "\n");
                        }

                        // Update prevModule
                        strncpy(prevModule, moduleName, 255);
                        prevModule[255] = '\0';
                     }

                     // Parse container and format with alignment
                     char temp[256];
                     strncpy(temp, procs[i]->container, 255);
                     temp[255] = '\0';

                     char* parts[3] = {NULL, NULL, NULL};
                     int partCount = 0;
                     char* token = strtok(temp, ".");
                     while (token != NULL && partCount < 3) {
                        parts[partCount++] = token;
                        token = strtok(NULL, ".");
                     }

                     char* typeName = 
                        procs[i]->type == C2_ALG_PREDICATE ? "PREDICATE" :
                        procs[i]->type == C2_ALG_TEST ? "TEST" :
                        procs[i]->type == C2_ALG_ACTION ? "ACTION" : "FUNCTION ";

                     // Format with aligned components
                     fprintf(stderr, "  %-9s %-*s  ", typeName, maxNameLen, procs[i]->name);

                     if (partCount >= 1) {
                        fprintf(stderr, "MOD %-*s", maxModLen, parts[0]);
                     }
                     if (partCount >= 2) {
                        fprintf(stderr, " LAY %-*s", maxLayLen, parts[1]);
                     }
                     if (partCount >= 3) {
                        fprintf(stderr, " SEC %s", parts[2]);
                     }
                     fprintf(stderr, "\n");

                     wasLude = currentIsLude;
                  }
                  free(procs);
               } else {
                  fprintf(stderr, "No algorithms found matching '%s'\n", prefix);
               }
            } else if (listType == 'v') {
               int count = 0;
               C2VarInfo** vars = c2FindVars(prefix, &count);
               if (vars != NULL && count > 0) {
                  fprintf(stderr, "Found %d VAR(s):\n", count);
                  for (int i = 0; i < count; i++) {
                     VALUE value = *vars[i]->value;
                     if (value == VALUE_UNDEFINED) {
                        fprintf(stderr, "  VAR %s.%s = ?\n",vars[i]->container, vars[i]->name);
                     } else if (C2Radix == 16) {
                        fprintf(stderr, FMT("  VAR %s.%s = " VALUE_HEX_FORMAT "\n"),vars[i]->container, vars[i]->name, value);
                     } else {
                        fprintf(stderr, FMT("  VAR %s.%s = " VALUE_DEC_FORMAT "\n"), vars[i]->container, vars[i]->name,value);
                     }
                  }
                  free(vars);
               } else {
                  fprintf(stderr, "No VARs found matching '%s'\n", prefix);
               }
            } else if (listType == 'l') {
               int count = 0;
               C2ListInfo** lists = c2FindLists(prefix, &count);
               if (lists != NULL && count > 0) {
                  fprintf(stderr, "Found %d LIST(s):\n", count);
                  for (int i = 0; i < count; i++) {
                     fprintf(stderr, "  LIST %s.%s[%d:%d]\n", 
                        lists[i]->container, lists[i]->name, lists[i]->lwb, lists[i]->upb);
                  }
                  free(lists);
               } else {
                  fprintf(stderr, "No LISTs found matching '%s'\n", prefix);
               }
            } else if (listType == 's') {
               int count = 0;
               C2ProcInfo** procs = c2FindProcs(prefix, &count);
               int spyCount = 0;
               if (procs != NULL && count > 0) {
                  // First pass to count spypoints
                  for (int i = 0; i < count; i++) {
                     if (procs[i]->spypoint) spyCount++;
                  }
                  if (spyCount > 0) {
                     fprintf(stderr, "Found %d spypoint(s):\n", spyCount);
                     for (int i = 0; i < count; i++) {
                        if (procs[i]->spypoint) {
                           fprintf(stderr, "  %s %s.%s\n", 
                              procs[i]->type == C2_ALG_PREDICATE ? "PREDICATE" :
                              procs[i]->type == C2_ALG_TEST ? "TEST" :
                              procs[i]->type == C2_ALG_ACTION ? "ACTION" : "FUNCTION",
                              procs[i]->container, procs[i]->name);
                        }
                     }
                  } else {
                     fprintf(stderr, "No spy points found matching '%s'\n", prefix);
                  }
                  free(procs);
               } else {
                  fprintf(stderr, "No algorithms found matching '%s'\n", prefix);
               }
            } else if (listType == 'o') {
               fprintf(stderr, "Debugger options:\n");
               fprintf(stderr, "  StepOverSuccess      = %-4s (+ + or - + to change)\n", C2StepOverSuccess ? "yes" : "no");
               fprintf(stderr, "  StepOverFailure      = %-4s (+ - or - - to change)\n", C2StepOverFailure ? "yes" : "no");
               fprintf(stderr, "  FullNames            = %-4s (+ = or - = to change)\n", C2FullNames ? "yes" : "no");
               fprintf(stderr, "  DefaultListElements  = %-4d (+ # N or - # to change)\n", C2DefaultListElements);
               fprintf(stderr, "  Radix                = %-4d (+ ^ or - ^ to change)\n", C2Radix);
            } else if (listType == 'h') {
               if (C2HistoryCount == 0) {
                  fprintf(stderr, "No command history\n");
               } else {
                  fprintf(stderr, "Command history (%d command(s)):\n", C2HistoryCount);
                  for (int i = 0; i < C2HistoryCount; i++) {
                     if (C2CommandHistory[i] != NULL) {
                        fprintf(stderr, "  %d: %s\n", i + 1, C2CommandHistory[i]);
                     }
                  }
               }
            } else {
               fprintf(stderr, "Invalid list type '%c'. Use 'a' for algorithms, 'v' for VARs, 'l' for LISTs, 's' for spypoints, 'o' for options, 'h' for history\n", listType);
            }
         }
         continue;
      case 't':
         fprintf(stderr, "\n");
         if (c2IsemptyOrWhitespace(arg)) {
            // No argument - show current algorithm's code
            C2ProcInfo currentProc = c2DebugInfo->procs[C2Stack[depth].procInfoIndex];
            if (currentProc.code != NULL && currentProc.code[0] != '\0') {
               fprintf(stderr, "\n%s\n", currentProc.code);
            } else {
               fprintf(stderr, "(No source code available)\n");
            }
         } else {
            // Check if argument is a sequence of dots (for ancestor navigation)
            char* p = arg;
            while (*p == ' ' || *p == '\t') p++;
            int dotCount = 0;
            while (*p == '.') {
               dotCount++;
               p++;
            }
            while (*p == ' ' || *p == '\t') p++;

            if (dotCount > 0 && *p == '\0') {
               // Argument is only dots - show ancestor code
               VALUE ancestorDepth = depth - (dotCount - 1);
               if (ancestorDepth < 0) {
                  fprintf(stderr, "Not enough call stack depth (only " VALUE_DEC_FORMAT " level(s) available)\n", depth + 1);
               } else if (ancestorDepth > C2SP) {
                  fprintf(stderr, "Invalid stack depth\n");
               } else {
                  C2ProcInfo ancestorProc = c2DebugInfo->procs[C2Stack[ancestorDepth].procInfoIndex];
                  if (ancestorProc.code != NULL && ancestorProc.code[0] != '\0') {
                     fprintf(stderr, "\n%s\n", ancestorProc.code);
                  } else {
                     fprintf(stderr, "(No source code available for %s.%s)\n", 
                        ancestorProc.container, ancestorProc.name);
                  }
               }
            } else {
               // Regular argument - find matching algorithm(s)
               int count = 0;
               C2ProcInfo** procs = c2FindProcs(arg, &count);
               if (procs != NULL && count > 0) {
                  for (int i = 0; i < count; i++) {
                     if (procs[i]->code != NULL && procs[i]->code[0] != '\0') {
                        fprintf(stderr, "\n%s\n", procs[i]->code);
                     } else {
                        fprintf(stderr, "(No source code available for %s.%s)\n", 
                           procs[i]->container, procs[i]->name);
                     }
                  }
                  free(procs);
               } else {
                  fprintf(stderr, "No algorithms found matching '%s'\n", arg);
               }
            }
         }
         continue;
      case 'd':
      case 'x':
      case 'c':
         fprintf(stderr, "\n");
         if (c2IsemptyOrWhitespace(arg)) {
            fprintf(stderr, "Expression cannot be empty\n");
         } else {
            C2EvalResult result = c2EvaluateExpr(depth, arg);
            if (result.values != NULL) {
               c2PrintValues(&result, (char)command);
               c2FreeEvalResult(&result);
            } else {
               fprintf(stderr, "Cannot evaluate '%s'\n", arg);
            }
         }
         continue;
      case 'q':
         fprintf(stderr, "\n");
         fprintf(stderr, "Quitting program.\n");
         c2SaveDebugState();
         exit(0);
         break;
      default:
         fprintf(stderr, "\n");
         fprintf(stderr, "Invalid command '%c'. Enter 'h' for help.\n", command);
         continue;
      }
      // If we reach here, break out of the loop (for commands like '>', 'g', 'j', 's', '<', 'r')
      break;
   }
}

/////////////////////////////////////////////////////////////////////////////////////
// Utility functions
/////////////////////////////////////////////////////////////////////////////////////

// Name extractor functions for generic search
char* c2GetProcName(int index) { return c2DebugInfo->procs[index].name; }
char* c2GetVarName(int index) { return c2DebugInfo->vars[index].name; }
char* c2GetListName(int index) { return c2DebugInfo->lists[index].name; }

// Generic linear search function - finds first match
int c2GenericFind(char* name, int count, char* (*getNameFunc)(int index)) {
   char* clean_name = c2RemoveBlanks(name);

   // Linear search for prefix match
   for (int i = 0; i < count; i++) {
      char* clean_target = c2RemoveBlanks(getNameFunc(i));
      bool matches = strcmp(clean_name, clean_target) == 0 || c2StartsWith(clean_target, clean_name);
      free(clean_target);
      if (matches) {
         free(clean_name);
         return i;
      }
   }

   free(clean_name);
   return -1;
}

// Generic function to find all matches (returns array of indices)
int* c2GenericFindAll(char* name, int count, char* (*getNameFunc)(int index), int* outCount) {
   *outCount = 0;

   char* clean_name = c2RemoveBlanks(name);

   // First pass: count all matches (not just contiguous ones)
   int matchCount = 0;
   for (int i = 0; i < count; i++) {
      char* clean_target = c2RemoveBlanks(getNameFunc(i));
      bool matches = strcmp(clean_name, clean_target) == 0 || c2StartsWith(clean_target, clean_name);
      free(clean_target);
      if (matches) matchCount++;
   }

   if (matchCount == 0) {
      free(clean_name);
      return NULL;
   }

   // Allocate result array
   int* result = (int*)malloc(matchCount * sizeof(int));
   if (result == NULL) {
      free(clean_name);
      *outCount = 0;
      return NULL;
   }

   // Second pass: collect all matching indices
   int resultIndex = 0;
   for (int i = 0; i < count; i++) {
      char* clean_target = c2RemoveBlanks(getNameFunc(i));
      bool matches = strcmp(clean_name, clean_target) == 0 || c2StartsWith(clean_target, clean_name);
      free(clean_target);
      if (matches) {
         result[resultIndex++] = i;
      }
   }

   free(clean_name);
   *outCount = matchCount;
   return result;
}

C2ProcInfo* c2FindProc(char* name) {
   int index = c2GenericFind(name, c2DebugInfo->procCount, c2GetProcName);
   return index >= 0 ? &c2DebugInfo->procs[index] : NULL;
}

C2ProcInfo** c2FindProcs(char* name, int* outCount) {
   int* indices = c2GenericFindAll(name, c2DebugInfo->procCount, c2GetProcName, outCount);
   if (indices == NULL) {
      return NULL;
   }

   C2ProcInfo** result = (C2ProcInfo**)malloc(*outCount * sizeof(C2ProcInfo*));
   if (result == NULL) {
      free(indices);
      *outCount = 0;
      return NULL;
   }

   for (int i = 0; i < *outCount; i++) {
      result[i] = &c2DebugInfo->procs[indices[i]];
   }

   free(indices);
   return result;
}

C2VarInfo* c2FindVar(char* name) {
   int index = c2GenericFind(name, c2DebugInfo->varCount, c2GetVarName);
   return index >= 0 ? &c2DebugInfo->vars[index] : NULL;
}

C2VarInfo** c2FindVars(char* name, int* outCount) {
   int* indices = c2GenericFindAll(name, c2DebugInfo->varCount, c2GetVarName, outCount);
   if (indices == NULL) {
      return NULL;
   }

   C2VarInfo** result = (C2VarInfo**)malloc(*outCount * sizeof(C2VarInfo*));
   if (result == NULL) {
      free(indices);
      *outCount = 0;
      return NULL;
   }

   for (int i = 0; i < *outCount; i++) {
      result[i] = &c2DebugInfo->vars[indices[i]];
   }

   free(indices);
   return result;
}

C2ListInfo* c2FindList(char* name) {
   int index = c2GenericFind(name, c2DebugInfo->listCount, c2GetListName);
   return index >= 0 ? &c2DebugInfo->lists[index] : NULL;
}

C2ListInfo** c2FindLists(char* name, int* outCount) {
   int* indices = c2GenericFindAll(name, c2DebugInfo->listCount, c2GetListName, outCount);
   if (indices == NULL) {
      return NULL;
   }

   C2ListInfo** result = (C2ListInfo**)malloc(*outCount * sizeof(C2ListInfo*));
   if (result == NULL) {
      free(indices);
      *outCount = 0;
      return NULL;
   }

   for (int i = 0; i < *outCount; i++) {
      result[i] = &c2DebugInfo->lists[indices[i]];
   }

   free(indices);
   return result;
}

C2EvalResult c2EvaluateExpr(VALUE depth, char* expr) {
   C2EvalResult result = { NULL, 0, false, false, 0, NULL, 0, 0, false };

   // Check for pointer indirection
   bool isIndirection = false;
   bool isSizedIndirection = false;
   if (expr[0] == '*') {
      isIndirection = true;
      expr++; // Skip the '*'
   } else if (expr[0] == '>') {
      isIndirection = true;
      isSizedIndirection = true;
      expr++; // Skip the '>'
   }

   char nameBuf[256];
   char* bracket = strchr(expr, '[');
   char* paren = strchr(expr, '(');
   bool useParens = false;

   // Both [] and () work for LISTs and pointers
   // [] gives terse display, () gives one per line with index
   if (paren != NULL && (bracket == NULL || paren < bracket)) {
      bracket = paren;
      useParens = true;
   }

   int nameLen = bracket ? (int)(bracket - expr) : (int)strlen(expr);

   if (nameLen >= 256) {
      return result;
   }

   // If brackets/parens are used, ensure there's a name before them
   if (bracket != NULL && nameLen == 0) {
      return result;
   }

   strncpy(nameBuf, expr, nameLen);
   nameBuf[nameLen] = '\0';

   char* cleanName = c2RemoveBlanks(nameBuf);

   // If brackets/parens are used, ensure there's a valid name before them
   if (bracket != NULL && (cleanName == NULL || cleanName[0] == '\0')) {
      if (cleanName != NULL) free(cleanName);
      return result;
   }

   C2StackFrame frame = C2Stack[depth];
   C2ProcInfo procInfo = c2DebugInfo->procs[frame.procInfoIndex];
   VALUE baseValue = 0;
   bool foundValue = false;

   // Check affixes
   for (int i = 0; i < procInfo.nargs; i++) {
      if (c2MatchName(procInfo.argnames[i], cleanName)) {
         switch (procInfo.affTypes[i]) {
            case C2_AFF_INPUT:
               baseValue = frame.args[i].val;
               foundValue = true;
               break;
            case C2_AFF_OUTPUT:
            case C2_AFF_TRANSPUT:
               baseValue = isIndirection ? frame.args[i].val : *frame.args[i].ptr;
               foundValue = true;
               break;
            case C2_AFF_STRING:
               baseValue = frame.args[i].str ? (VALUE)strlen(frame.args[i].str) : 0;
               foundValue = true;
               break;
         }
         break;
      }
   }

   // Check locals if not found
   if (!foundValue) {
      for (int i = 0; i < procInfo.nlocals; i++) {
         if (c2MatchName(procInfo.localnames[i], cleanName)) {
            baseValue = *frame.locals[i];
            foundValue = true;
            break;
         }
      }
   }

   // Check VARs if not found
   if (!foundValue) {
      C2VarInfo* var = c2FindVar(cleanName);
      if (var != NULL) {
         baseValue = *var->value;
         foundValue = true;
      }
   }

   // If we found a value and it's indirection
   if (foundValue && isIndirection) {
      WARNING_SUPPRESS(4305, "-Wconversion")
      VALUE* ptr = (VALUE*)baseValue;
      WARNING_RESTORE(4305, "-Wconversion")
      if (ptr == NULL) {
         free(cleanName);
         return result;
      }

      // For sized indirection (>), get the size from ptr[-1]
      int actualSize = 0;

      if (isSizedIndirection) {
         actualSize = (int)ptr[-1];
         if (actualSize < 0) actualSize = 0;
      }

      // Handle indexing for indirection with lwb=0
      if (bracket != NULL) {
         char* indexExpr = bracket + 1;
         char closingChar = useParens ? ')' : ']';
         char* closeBracket = strchr(indexExpr, closingChar);
         if (closeBracket == NULL) {
            free(cleanName);
            return result;
         }

         char indexBuf[128];
         strncpy(indexBuf, indexExpr, closeBracket - indexExpr);
         indexBuf[closeBracket - indexExpr] = '\0';

         int startIdx = 0;
         int endIdx = 0;
         int count = 1;

         // Parse index expression (same logic as LIST but lwb=0)
         char* trimmed = indexBuf;
         while (*trimmed == ' ' || *trimmed == '\t') trimmed++;

         // Special case for sized indirection: [-] [:] (-) (:) means show all elements
         if (*trimmed == '\0') {
            // Empty brackets - use default count from start
            count = C2DefaultListElements;
            endIdx = startIdx + count - 1;
         } else if (isSizedIndirection && actualSize > 0 && 
                    ((trimmed[0] == '-' || trimmed[0] == ':') && trimmed[1] == '\0')) {
            // [-] or [:] - show all elements from 0 to actualSize-1
            startIdx = 0;
            endIdx = actualSize - 1;
            count = actualSize;
         } else {
            char* colon = strchr(indexBuf, ':');
            char* dash = strchr(indexBuf, '-');

            if (colon != NULL) {
               *colon = '\0';
               if (indexBuf[0] == '\0') {
                  // [:endIdx] - end at endIdx, show default count elements
                  endIdx = atoi(colon + 1);
                  startIdx = endIdx - C2DefaultListElements + 1;
                  if (startIdx < 0) startIdx = 0;
                  count = endIdx - startIdx + 1;
               } else if (*(colon + 1) == '\0') {
                  // [start:] - start at startIdx, show default count elements
                  startIdx = atoi(indexBuf);
                  endIdx = startIdx + C2DefaultListElements - 1;
                  count = C2DefaultListElements;
               } else {
                  // [start:n] - start at startIdx, show n elements
                  startIdx = atoi(indexBuf);
                  count = atoi(colon + 1);
                  endIdx = startIdx + count - 1;
               }
            } else if (dash != NULL) {
               *dash = '\0';
               if (indexBuf[0] == '\0') {
                  // [-endIdx] - end at endIdx, show default count elements
                  endIdx = atoi(dash + 1);
                  startIdx = endIdx - C2DefaultListElements + 1;
                  count = C2DefaultListElements;
               } else if (*(dash + 1) == '\0') {
                  // [start-] - start at startIdx, show default count elements
                  startIdx = atoi(indexBuf);
                  endIdx = startIdx + C2DefaultListElements - 1;
                  count = C2DefaultListElements;
               } else {
                  // [start-end] - from startIdx to endIdx
                  startIdx = atoi(indexBuf);
                  endIdx = atoi(dash + 1);
                  count = endIdx - startIdx + 1;
               }
            } else {
               // Single index
               startIdx = atoi(indexBuf);
               endIdx = startIdx;
               count = 1;
            }
         }

            // For sized indirection, clamp to actual size
            if (isSizedIndirection && actualSize > 0) {
               if (startIdx >= actualSize) {
                  free(cleanName);
                  return result;
               }
               if (endIdx >= actualSize) {
                  endIdx = actualSize - 1;
               }
               count = endIdx - startIdx + 1;
            }

            if (count <= 0 || startIdx < 0) {
               free(cleanName);
               return result;
            }

            result.count = count;
            result.startIndex = startIdx;
            result.onePerLine = useParens;
            result.needsFree = true;
            result.lwb = startIdx;
            result.upb = startIdx + count - 1;
            result.listName = cleanName;
            result.freeListName = true;
            result.values = (VALUE*)malloc(count * sizeof(VALUE));

            if (result.values != NULL) {
               for (int i = 0; i < count; i++) {
                  result.values[i] = ptr[startIdx + i];
               }
            }
            return result;
      } else {
         // No indexing - just dereference
         result.count = 1;
         result.needsFree = true;
         result.values = (VALUE*)malloc(sizeof(VALUE));
         if (result.values != NULL) {
            result.values[0] = *ptr;
         }
         free(cleanName);
         return result;
      }
   }

   // If not indirection or not found yet, continue with original logic
   if (foundValue && !isIndirection) {
      result.count = 1;
      result.needsFree = true;
      result.values = (VALUE*)malloc(sizeof(VALUE));
      if (result.values != NULL) {
         result.values[0] = baseValue;
      }
      free(cleanName);
      return result;
   }

   // Check LISTs
   C2ListInfo* list = c2FindList(cleanName);
   if (list != NULL) {
      int startIdx = list->lwb;
      int endIdx = list->upb;
      int count = 1;

      if (bracket != NULL) {
         char* indexExpr = bracket + 1;
         char closingChar = useParens ? ')' : ']';
         char* closeBracket = strchr(indexExpr, closingChar);
         if (closeBracket == NULL) {
            free(cleanName);
            return result;
         }

         char indexBuf[128];
         strncpy(indexBuf, indexExpr, closeBracket - indexExpr);
         indexBuf[closeBracket - indexExpr] = '\0';

         // If empty brackets [], treat like no brackets
         char* trimmed = indexBuf;
         while (*trimmed == ' ' || *trimmed == '\t') trimmed++;

         // Special case for LISTs: [-] or [:] means show all elements
         if (*trimmed == '\0') {
            // Empty brackets - use default count from start
            count = C2DefaultListElements;
            endIdx = startIdx + count - 1;
         } else if ((trimmed[0] == '-' || trimmed[0] == ':') && trimmed[1] == '\0') {
            // [-] or [:] - show all elements from lwb to upb
            startIdx = list->lwb;
            endIdx = list->upb;
            count = endIdx - startIdx + 1;
         } else {
            char* colon = strchr(indexBuf, ':');
            char* dash = strchr(indexBuf, '-');

            if (colon != NULL) {
               *colon = '\0';
               if (indexBuf[0] == '\0') {
                  // [:endIdx] form - end at endIdx, show default count elements
                  endIdx = atoi(colon + 1);
                  startIdx = endIdx - C2DefaultListElements + 1;
                  count = C2DefaultListElements;
               } else if (*(colon + 1) == '\0') {
                  // [start:] - start at startIdx, show default count elements
                  startIdx = atoi(indexBuf);
                  endIdx = startIdx + C2DefaultListElements - 1;
                  count = C2DefaultListElements;
               } else {
                  // [start:n] - start at startIdx, show n elements
                  startIdx = atoi(indexBuf);
                  count = atoi(colon + 1);
                  endIdx = startIdx + count - 1;
               }
            } else if (dash != NULL) {
               *dash = '\0';
               if (indexBuf[0] == '\0') {
                  // [-endIdx] form - end at endIdx, show default count elements
                  endIdx = atoi(dash + 1);
                  startIdx = endIdx - C2DefaultListElements + 1;
                  count = C2DefaultListElements;
               } else if (*(dash + 1) == '\0') {
                  // [start-] - start at startIdx, show default count elements
                  startIdx = atoi(indexBuf);
                  endIdx = startIdx + C2DefaultListElements - 1;
                  count = C2DefaultListElements;
               } else {
                  // [start-end] - from startIdx to endIdx
                  startIdx = atoi(indexBuf);
                  endIdx = atoi(dash + 1);
                  count = endIdx - startIdx + 1;
               }
            } else {
               // Single index
               startIdx = atoi(indexBuf);
               endIdx = startIdx;
               count = 1;
            }
         }
      } else {
         // No bracket - use default count from start
         count = C2DefaultListElements;
         endIdx = startIdx + count - 1;
      }

      result.onePerLine = useParens;

      // Clamp to list bounds
      if (startIdx < list->lwb) {
         startIdx = list->lwb;
      }
      if (startIdx > list->upb) {
         free(cleanName);
         return result;
      }
      if (endIdx > list->upb) {
         endIdx = list->upb;
      }

      count = endIdx - startIdx + 1;
      if (count <= 0) {
         free(cleanName);
         return result;
      }

      result.count = count;
      result.startIndex = startIdx;
      result.onePerLine = useParens;
      result.needsFree = true;
      result.lwb = list->lwb;
      result.upb = list->upb;
      result.listName = list->name;
      result.values = (VALUE*)malloc(count * sizeof(VALUE));
      if (result.values != NULL) {
         for (int i = 0; i < count; i++) {
            result.values[i] = list->value[startIdx - list->lwb + i];
         }
      }
      free(cleanName);
      return result;
   }

   free(cleanName);
   return result;
}

void c2PrintValues(C2EvalResult* result, char format) {
   if (result == NULL || result->values == NULL || result->count == 0) {
      return;
   }

   if (result->onePerLine) {
      // Print header with list name and bounds if this is a list
      if (result->listName != NULL) {
         fprintf(stderr, "%s(%d:%d)\n", result->listName, result->lwb, result->upb);
      }

      // Calculate width needed for the largest index
      int maxIndex = result->startIndex + result->count - 1;
      int width = snprintf(NULL, 0, "%d", maxIndex);

      for (int i = 0; i < result->count; i++) {
         fprintf(stderr, "%*d: ", width, result->startIndex + i);

         if (result->values[i] == VALUE_UNDEFINED) {
            fprintf(stderr, "?\n");
         } else {
            switch (format) {
            case 'd':
               fprintf(stderr, FMT(VALUE_DEC_FORMAT "\n"), result->values[i]);
               break;
            case 'x':
               fprintf(stderr, FMT("0x" VALUE_HEX_FORMAT "\n"), result->values[i]);
               break;
            case 'c':
               if (result->values[i] >= 32 && result->values[i] <= 126) {
                  fprintf(stderr, "'%c'\n", (char)result->values[i]);
               }
               else {
                  fprintf(stderr, FMT("'\\x" VALUE_HEX_FMT(2) "'\n"), result->values[i]);
               }
               break;
            }
         }
      }
   } else {
      for (int i = 0; i < result->count; i++) {
         if (i > 0) fprintf(stderr, ", ");

         if (result->values[i] == VALUE_UNDEFINED) {
            fprintf(stderr, "?");
         } else {
            switch (format) {
            case 'd':
               fprintf(stderr, FMT(VALUE_DEC_FORMAT), result->values[i]);
               break;
            case 'x':
               fprintf(stderr, FMT("0x" VALUE_HEX_FORMAT), result->values[i]);
               break;
            case 'c':
               if (result->values[i] >= 32 && result->values[i] <= 126) {
                  fprintf(stderr, "'%c'", (char)result->values[i]);
               }
               else {
                  fprintf(stderr, FMT("'\\x" VALUE_HEX_FMT(2) "'"), result->values[i]);
               }
               break;
            }
         }
      }
      fprintf(stderr, "\n");
   }
}

void c2FreeEvalResult(C2EvalResult* result) {
   if (result != NULL && result->needsFree) {
      if (result->values != NULL) {
         free(result->values);
         result->values = NULL;
      }
      if (result->freeListName && result->listName != NULL) {
         free(result->listName);
         result->listName = NULL;
      }
      result->count = 0;
   }
}

bool c2StartsWith(char* str, char* prefix) {
   while (*prefix != '\0') {
      if (*str != *prefix) {
         return false;
      }
      str++;
      prefix++;
   }
   return true;
}

bool c2MatchName(char* name1, char* name2) {
   char* clean1 = c2RemoveBlanks(name1);
   char* clean2 = c2RemoveBlanks(name2);
   bool result = c2StartsWith(clean1, clean2);
   free(clean1);
   free(clean2);
   return result;
}

char* c2RemoveBlanks(char* str) {
   // First pass: count non-blank characters
   int count = 0;
   for (char* src = str; *src != '\0'; src++) {
      if (*src != ' ') count++;
   }

   // Allocate exactly what we need
   char* result = (char*)malloc(count + 1);
   if (result == NULL) {
      return NULL; // Memory allocation failed
   }

   // Second pass: copy non-blank characters
   char* dst = result;
   for (char* src = str; *src != '\0'; src++) {
      if (*src != ' ') *dst++ = *src;
   }
   *dst = '\0';
   return result;
}

bool c2IsemptyOrWhitespace(char* str) {
   for (char* p = str; *p != '\0'; p++) {
      if (*p != ' ' && *p != '\t' && *p != '\n' && *p != '\r') {
         return false;
      }
   }
   return true;
}

// Read line until Enter (simple version without history)
char* c2ReadLine() {
   static char buffer[256];
   int i = 0;
   int ch;
   while (i < 255 && (ch = getchar()) != '\n' && ch != '\r' && ch != EOF) {
      buffer[i++] = (char)ch;
   }
   buffer[i] = '\0';
   return buffer;
}

// Read full command with history support (used at main REPL prompt)
char* c2ReadFullCommand() {
   static char buffer[256];
   static char tempBuffer[256];
   int i = 0;
   int cursorPos = 0;
   int historyPos = C2HistoryCount;

   buffer[0] = '\0';
   tempBuffer[0] = '\0';

   while (1) {
      int ch = c2_get_special_key();

      // Translate special keys to simple commands
      if (ch == '\r' || ch == '\n') {
         if (i == 0) {
            strcpy(buffer, ">");
            fprintf(stderr, "%s>%s", ansi_fg(YELLOW), ansi_fg(RESET));
         }
         break;
      } else if (ch == KEY_END && i == 0) {
         // END key only works as 'g' command when buffer is empty
         strcpy(buffer, "g");
         fprintf(stderr, "%sg%s", ansi_fg(YELLOW), ansi_fg(RESET));
         break;
      } else if (ch == ' ' && i == 0) {
         // SPACE only works as 'j' command when buffer is empty
         strcpy(buffer, "j");
         fprintf(stderr, "%sj%s", ansi_fg(YELLOW), ansi_fg(RESET));
         break;
      } else if (ch == '\t' && i == 0) {
         // TAB only works as 's' command when buffer is empty
         strcpy(buffer, "s");
         fprintf(stderr, "%ss%s", ansi_fg(YELLOW), ansi_fg(RESET));
         break;
      } else if (ch == KEY_ESC && i == 0) {
         // ESC only works as 'q' command when buffer is empty
         strcpy(buffer, "q");
         fprintf(stderr, "%sq%s", ansi_fg(YELLOW), ansi_fg(RESET));
         break;
      } else if (ch == KEY_ESC) {
         // ESC clears the command line when editing
         while (cursorPos < i) {
            fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[cursorPos], ansi_fg(RESET));
            cursorPos++;
         }
         for (int j = 0; j < i; j++) fprintf(stderr, "\b \b");
         i = 0;
         cursorPos = 0;
         buffer[0] = '\0';
      } else if (ch == KEY_LEFT && i == 0) {
         // LEFT key only works as '<' command when buffer is empty
         strcpy(buffer, "<");
         fprintf(stderr, "%s<%s", ansi_fg(YELLOW), ansi_fg(RESET));
         break;
      } else if (ch == KEY_F1 && i == 0) {
         // F1 key only works as 'h' command when buffer is empty
         strcpy(buffer, "h");
         fprintf(stderr, "%sh%s", ansi_fg(YELLOW), ansi_fg(RESET));
         break;
      } else if (ch == KEY_LEFT) {
         if (cursorPos > 0) {
            cursorPos--;
            fprintf(stderr, "\b");
         }
      } else if (ch == KEY_RIGHT) {
         if (cursorPos < i) {
            fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[cursorPos], ansi_fg(RESET));
            cursorPos++;
         }
      } else if (ch == KEY_HOME) {
         // Move cursor to beginning
         while (cursorPos > 0) {
            cursorPos--;
            fprintf(stderr, "\b");
         }
      } else if (ch == KEY_END) {
         // Move cursor to end
         while (cursorPos < i) {
            fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[cursorPos], ansi_fg(RESET));
            cursorPos++;
         }
      } else if (ch == KEY_UP) {
         // Find previous command
         if (historyPos > 0) {
            if (historyPos == C2HistoryCount && i > 0) {
               strncpy(tempBuffer, buffer, sizeof(tempBuffer) - 1);
               tempBuffer[sizeof(tempBuffer) - 1] = '\0';
            }
            historyPos--;
            if (C2CommandHistory[historyPos] != NULL) {
               // Clear current line
               while (cursorPos < i) {
                  fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[cursorPos], ansi_fg(RESET));
                  cursorPos++;
               }
               for (int j = 0; j < i; j++) fprintf(stderr, "\b \b");
               // Copy and display history
               strncpy(buffer, C2CommandHistory[historyPos], sizeof(buffer) - 1);
               buffer[sizeof(buffer) - 1] = '\0';
               i = (int)strlen(buffer);
               cursorPos = i;
               fprintf(stderr, "%s%s%s", ansi_fg(YELLOW), buffer, ansi_fg(RESET));
            }
         }
      } else if (ch == KEY_DOWN) {
         if (historyPos < C2HistoryCount) {
            historyPos++;
            // Clear current line
            while (cursorPos < i) {
               fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[cursorPos], ansi_fg(RESET));
               cursorPos++;
            }
            for (int j = 0; j < i; j++) fprintf(stderr, "\b \b");
            if (historyPos == C2HistoryCount) {
               // Restore temp buffer
               strncpy(buffer, tempBuffer, sizeof(buffer) - 1);
               buffer[sizeof(buffer) - 1] = '\0';
            } else if (C2CommandHistory[historyPos] != NULL) {
               strncpy(buffer, C2CommandHistory[historyPos], sizeof(buffer) - 1);
               buffer[sizeof(buffer) - 1] = '\0';
            }
            i = (int)strlen(buffer);
            cursorPos = i;
            fprintf(stderr, "%s%s%s", ansi_fg(YELLOW), buffer, ansi_fg(RESET));
         }
      } else if (ch == 127 || ch == 8) { // Backspace
         if (cursorPos > 0) {
            // Delete character before cursor
            memmove(&buffer[cursorPos - 1], &buffer[cursorPos], i - cursorPos + 1);
            i--;
            cursorPos--;
            // Redraw from cursor to end
            fprintf(stderr, "\b");
            for (int j = cursorPos; j < i; j++) {
               fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[j], ansi_fg(RESET));
            }
            fprintf(stderr, " \b");
            for (int j = cursorPos; j < i; j++) fprintf(stderr, "\b");
         }
      } else if (ch == KEY_DELETE) { // Delete key
         if (cursorPos < i) {
            // Delete character at cursor
            memmove(&buffer[cursorPos], &buffer[cursorPos + 1], i - cursorPos);
            i--;
            // Redraw from cursor to end
            for (int j = cursorPos; j < i; j++) {
               fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[j], ansi_fg(RESET));
            }
            fprintf(stderr, " \b");
            for (int j = cursorPos; j < i; j++) fprintf(stderr, "\b");
         }
      } else if (ch >= 32 && ch < 127 && i < 255) {
         // Insert character at cursor
         if (cursorPos < i) {
            memmove(&buffer[cursorPos + 1], &buffer[cursorPos], i - cursorPos + 1);
         }
         buffer[cursorPos] = (char)ch;
         i++;
         buffer[i] = '\0';
         // Redraw from cursor to end
         for (int j = cursorPos; j < i; j++) {
            fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[j], ansi_fg(RESET));
         }
         cursorPos++;
         for (int j = cursorPos; j < i; j++) fprintf(stderr, "\b");

         // Check if this is a single-letter command that should execute immediately
         if (i == 1 && (ch == 'q' || ch == 'g' || ch == 'j' || ch == 's' ||
                     ch == '<' || ch == 'b' || ch == 'h' || ch == '>')) {
         break;  // Execute immediately
      }

      // Commands that take arguments - echo space and add to buffer
      if (i == 1 && (ch == 'l' || ch == 'd' || ch == 'x' || ch == 'c' || 
                     ch == '+' || ch == '-' || ch == 'r' || ch == 't')) {
         fprintf(stderr, " ");  // Echo space after command letter
         if (cursorPos < i) {
            memmove(&buffer[cursorPos + 1], &buffer[cursorPos], i - cursorPos + 1);
         }
         buffer[cursorPos] = ' ';
         i++;
         cursorPos++;
         buffer[i] = '\0';
      }
   }
   }

   return buffer;
}

// Read line with up/down arrow history support
char* c2ReadLineWithHistory() {
   static char buffer[256];
   static char tempBuffer[256];
   int i = 0;
   int cursorPos = 0;
   int historyPos = C2HistoryCount;

   buffer[0] = '\0';
   tempBuffer[0] = '\0';

   while (1) {
      int ch = c2_get_special_key();

      if (ch == '\n' || ch == '\r') {
         fprintf(stderr, "\n");
         break;
      } else if (ch == KEY_LEFT) {
         if (cursorPos > 0) {
            cursorPos--;
            fprintf(stderr, "\b");
         }
      } else if (ch == KEY_RIGHT) {
         if (cursorPos < i) {
            fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[cursorPos], ansi_fg(RESET));
            cursorPos++;
         }
      } else if (ch == KEY_HOME) {
         // Move cursor to beginning
         while (cursorPos > 0) {
            cursorPos--;
            fprintf(stderr, "\b");
         }
      } else if (ch == KEY_END) {
         // Move cursor to end
         while (cursorPos < i) {
            fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[cursorPos], ansi_fg(RESET));
            cursorPos++;
         }
      } else if (ch == KEY_UP) {
         // Find previous command
         if (historyPos > 0) {
            if (historyPos == C2HistoryCount && i > 0) {
               strncpy(tempBuffer, buffer, sizeof(tempBuffer) - 1);
               tempBuffer[sizeof(tempBuffer) - 1] = '\0';
            }
            historyPos--;
            if (C2CommandHistory[historyPos] != NULL) {
               // Clear current line
               while (cursorPos < i) {
                  fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[cursorPos], ansi_fg(RESET));
                  cursorPos++;
               }
               for (int j = 0; j < i; j++) fprintf(stderr, "\b \b");
               // Copy and display FULL command from history
               strncpy(buffer, C2CommandHistory[historyPos], sizeof(buffer) - 1);
               buffer[sizeof(buffer) - 1] = '\0';
               i = (int)strlen(buffer);
               cursorPos = i;
               fprintf(stderr, "%s%s%s", ansi_fg(YELLOW), buffer, ansi_fg(RESET));
            }
         }
      } else if (ch == KEY_DOWN) {
         if (historyPos < C2HistoryCount) {
            historyPos++;
            // Clear current line
            while (cursorPos < i) {
               fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[cursorPos], ansi_fg(RESET));
               cursorPos++;
            }
            for (int j = 0; j < i; j++) fprintf(stderr, "\b \b");
            if (historyPos == C2HistoryCount) {
               // Restore temp buffer
               strncpy(buffer, tempBuffer, sizeof(buffer) - 1);
               buffer[sizeof(buffer) - 1] = '\0';
            } else if (C2CommandHistory[historyPos] != NULL) {
               // Copy and display FULL command from history
               strncpy(buffer, C2CommandHistory[historyPos], sizeof(buffer) - 1);
               buffer[sizeof(buffer) - 1] = '\0';
            }
            i = (int)strlen(buffer);
            cursorPos = i;
            fprintf(stderr, "%s%s%s", ansi_fg(YELLOW), buffer, ansi_fg(RESET));
         }
      } else if (ch == 127 || ch == 8) { // Backspace
         if (cursorPos > 0) {
            // Delete character before cursor
            memmove(&buffer[cursorPos - 1], &buffer[cursorPos], i - cursorPos + 1);
            i--;
            cursorPos--;
            // Redraw from cursor to end
            fprintf(stderr, "\b");
            for (int j = cursorPos; j < i; j++) {
               fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[j], ansi_fg(RESET));
            }
            fprintf(stderr, " \b");
            for (int j = cursorPos; j < i; j++) fprintf(stderr, "\b");
         }
      } else if (ch == KEY_DELETE) { // Delete key
         if (cursorPos < i) {
            // Delete character at cursor
            memmove(&buffer[cursorPos], &buffer[cursorPos + 1], i - cursorPos);
            i--;
            // Redraw from cursor to end
            for (int j = cursorPos; j < i; j++) {
               fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[j], ansi_fg(RESET));
            }
            fprintf(stderr, " \b");
            for (int j = cursorPos; j < i; j++) fprintf(stderr, "\b");
         }
      } else if (ch >= 32 && ch < 127 && i < 255) {
         // Insert character at cursor
         if (cursorPos < i) {
            memmove(&buffer[cursorPos + 1], &buffer[cursorPos], i - cursorPos + 1);
         }
         buffer[cursorPos] = (char)ch;
         i++;
         buffer[i] = '\0';
         // Redraw from cursor to end
         for (int j = cursorPos; j < i; j++) {
            fprintf(stderr, "%s%c%s", ansi_fg(YELLOW), buffer[j], ansi_fg(RESET));
         }
         cursorPos++;
         for (int j = cursorPos; j < i; j++) fprintf(stderr, "\b");
      }
   }

   return buffer;
}

// Add command to history
void c2AddToHistory(char* cmd) {
   if (cmd == NULL || cmd[0] == '\0') return;

   // Don't add duplicate of most recent command
   if (C2HistoryCount > 0 && C2CommandHistory[C2HistoryCount - 1] != NULL &&
       strcmp(C2CommandHistory[C2HistoryCount - 1], cmd) == 0) {
      return;
   }

   // Free oldest if at capacity
   if (C2HistoryCount >= C2_HISTORY_SIZE) {
      free(C2CommandHistory[0]);
      // Shift all entries down
      for (int i = 0; i < C2_HISTORY_SIZE - 1; i++) {
         C2CommandHistory[i] = C2CommandHistory[i + 1];
      }
      C2HistoryCount = C2_HISTORY_SIZE - 1;
   }

   // Add new command
   C2CommandHistory[C2HistoryCount] = (char*)malloc(strlen(cmd) + 1);
   if (C2CommandHistory[C2HistoryCount] != NULL) {
      strcpy(C2CommandHistory[C2HistoryCount], cmd);
      C2HistoryCount++;
   }
}

// Cross-platform immediate character input
char c2_getch() {
#ifdef _WIN32
   return (char)_getch();
#else
   struct termios oldattr, newattr;
   char ch;
   tcgetattr(STDIN_FILENO, &oldattr);
   newattr = oldattr;
   newattr.c_lflag &= ~(ICANON | ECHO);
   tcsetattr(STDIN_FILENO, TCSANOW, &newattr);
   ch = getchar();
   tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
   return ch;
#endif
}

// Cross-platform special key detection
int c2_get_special_key() {
#ifdef _WIN32
   int ch = _getch();
   if (ch == 0 || ch == 224) { // Extended key prefix on Windows (0 or 0xE0)
      ch = _getch();
      switch (ch) {
      case 59: return KEY_F1;      // F1 key
      case 79: return KEY_END;     // END key
      case 71: return KEY_HOME;    // HOME key
      case 72: return KEY_UP;      // UP arrow
      case 80: return KEY_DOWN;    // DOWN arrow
      case 75: return KEY_LEFT;    // LEFT arrow
      case 77: return KEY_RIGHT;   // RIGHT arrow
      case 83: return KEY_DELETE;  // DELETE key
      }
   }
   return ch; // Regular character
#else
   struct termios oldattr, newattr;
   int ch;
   int result;
   tcgetattr(STDIN_FILENO, &oldattr);
   newattr = oldattr;
   newattr.c_lflag &= ~(ICANON | ECHO);
   newattr.c_cc[VMIN] = 1;   // Wait for at least 1 character
   newattr.c_cc[VTIME] = 0;  // No timeout - wait indefinitely for that character
   tcsetattr(STDIN_FILENO, TCSANOW, &newattr);

   ch = getchar();
   result = ch;

   if (ch == 27) { // ESC sequence
      // Switch to non-blocking mode to check if more characters are waiting
      newattr.c_cc[VMIN] = 0;
      newattr.c_cc[VTIME] = 2; // 200ms timeout (0.2 seconds)
      tcsetattr(STDIN_FILENO, TCSANOW, &newattr);

      // Now check if more characters are available
      ch = getchar();
      if (ch != EOF) {
         // More characters available - it's an escape sequence
         if (ch == 'O') {
            // Some terminals send ESC O P for F1
            ch = getchar();
            if (ch == 'P') {
               result = KEY_F1;
            }
         } else if (ch == '[') {
            ch = getchar();
            switch (ch) {
            case 'F':
               result = KEY_END;
               break;
            case 'H':
               result = KEY_HOME;
               break;
            case 'A':
               result = KEY_UP;
               break;
            case 'B':
               result = KEY_DOWN;
               break;
            case 'D':
               result = KEY_LEFT;
               break;
            case 'C':
               result = KEY_RIGHT;
               break;
            case '1':
               // F1 key sequence: ESC [ 1 1 ~
               ch = getchar();
               if (ch == '1') {
                  ch = getchar();
                  if (ch == '~') {
                     result = KEY_F1;
                  }
               }
               break;
            case '3':
               ch = getchar();
               if (ch == '~') {
                  result = KEY_DELETE;
               }
               break;
            case '4':
               ch = getchar();
               if (ch == '~') {
                  result = KEY_END;
               }
               break;
            }
         }
      } else {
         // Timeout/EOF - it's just ESC pressed alone
         result = KEY_ESC;
      }
   }

   tcsetattr(STDIN_FILENO, TCSANOW, &oldattr);
   return result;
#endif
}

/////////////////////////////////////////////////////////////////////////////////
// Signal handler and exit wrapper - defined early so ALL code uses them
/////////////////////////////////////////////////////////////////////////////////
void c2SignalHandler(int sig) {
   fprintf(stderr, "\n\x1b[31m*** CDL2 Runtime Error: Caught signal %d ***\x1b[0m\n", sig);
   c2Backtrace();
   _Exit(sig);  // Use _Exit directly to avoid recursion
}

void c2InitTrace() {
   // Initialize stack if not already done
   if (C2Stack == NULL) {
      C2Stack = (C2StackFrame*)malloc(CALL_STACK_MAX_DEPTH * sizeof(C2StackFrame));
      if (C2Stack == NULL) {
         fprintf(stderr, "Failed to allocate call stack\n");
         _Exit(1);
      }
      C2StackCapacity = CALL_STACK_MAX_DEPTH;
   }

   // Set up signal handlers to catch runtime errors
   signal(SIGSEGV, c2SignalHandler);  // Segmentation fault
   signal(SIGABRT, c2SignalHandler);  // Abort
   signal(SIGFPE, c2SignalHandler);   // Floating point exception
   signal(SIGILL, c2SignalHandler);   // Illegal instruction
   signal(SIGINT, c2SignalHandler);   // Ctrl-C interrupt
#ifndef _WIN32
   signal(SIGBUS, c2SignalHandler);   // Bus error (POSIX)
#endif
}

// Get executable path
char* c2GetExecutablePath() {
   static char path[1024];
#ifdef _WIN32
   GetModuleFileNameA(NULL, path, sizeof(path));
#else
   ssize_t len = readlink("/proc/self/exe", path, sizeof(path) - 1);
   if (len != -1) {
      path[len] = '\0';
   } else {
      path[0] = '\0';
   }
#endif
   return path;
}

// Save debugger state to file
void c2SaveDebugState() {
   char* exePath = c2GetExecutablePath();
   if (exePath[0] == '\0') return;

   char debugFile[1280];
   sprintf(debugFile, "%s.cdl2debug", exePath);

   FILE* f = fopen(debugFile, "w");
   if (f == NULL) return;

   fprintf(f, "# CDL2 Debugger State\n");
   fprintf(f, "StepOverSuccess=%d\n", C2StepOverSuccess);
   fprintf(f, "StepOverFailure=%d\n", C2StepOverFailure);
   fprintf(f, "FullNames=%d\n", C2FullNames);
   fprintf(f, "DefaultListElements=%d\n", C2DefaultListElements);

   fprintf(f, "\n# Spy Points\n");
   for (int i = 0; i < c2DebugInfo->procCount; i++) {
      if (c2DebugInfo->procs[i].spypoint) {
         fprintf(f, "SpyPoint=%s.%s\n", c2DebugInfo->procs[i].container, c2DebugInfo->procs[i].name);
      }
   }

   fprintf(f, "\n# Command History\n");
   for (int i = 0; i < C2HistoryCount; i++) {
      if (C2CommandHistory[i] != NULL) {
         fprintf(f, "History=%s\n", C2CommandHistory[i]);
      }
   }

   fclose(f);
}

// Load debugger state from file

// Helper: set spypoint by container and name
static void c2SetSpyPointByContainerAndName(const char* container, const char* name, bool set) {
   for (int i = 0; i < c2DebugInfo->procCount; i++) {
      C2ProcInfo* proc = &c2DebugInfo->procs[i];
      if (strcmp(proc->container, container) == 0 && strcmp(proc->name, name) == 0) {
         proc->spypoint = set;
      }
   }
}

void c2LoadDebugState() {
   char* exePath = c2GetExecutablePath();
   if (exePath[0] == '\0') return;

   char debugFile[1280];
   sprintf(debugFile, "%s.cdl2debug", exePath);

   FILE* f = fopen(debugFile, "r");
   if (f == NULL) return;

   char line[512];
   while (fgets(line, sizeof(line), f) != NULL) {
      // Remove newline
      line[strcspn(line, "\r\n")] = '\0';

      // Skip comments and empty lines
      if (line[0] == '#' || line[0] == '\0') continue;

      // Parse key=value
      char* eq = strchr(line, '=');
      if (eq == NULL) continue;

      *eq = '\0';
      char* key = line;
      char* value = eq + 1;

      if (strcmp(key, "StepOverSuccess") == 0) {
         C2StepOverSuccess = (bool)atoi(value);
      } else if (strcmp(key, "StepOverFailure") == 0) {
         C2StepOverFailure = (bool)atoi(value);
      } else if (strcmp(key, "FullNames") == 0) {
         C2FullNames = (bool)atoi(value);
      } else if (strcmp(key, "DefaultListElements") == 0) {
         C2DefaultListElements = (bool)atoi(value);
      } else if (strcmp(key, "SpyPoint") == 0) {
         // value is container.name
         char* dot = strrchr(value, '.');
         if (dot != NULL) {
            *dot = '\0';
            const char* container = value;
            const char* name = dot + 1;
            c2SetSpyPointByContainerAndName(container, name, true);
         }
      } else if (strcmp(key, "History") == 0) {
         c2AddToHistory(value);
      }
   }

   fclose(f);
}

void c2Exit(int code) {
   static bool exiting = false;
   if (!exiting && code != 0 && C2SP >= 0) {
      exiting = true;
      fprintf(stderr, "\n*** CDL2 Program exiting with code %d ***\n", code);
      c2Backtrace();
   }

#ifdef CDL2PROFILE
   // Dump profiling data to a .c2prof file
   char* exePath = c2GetExecutablePath();
   if (exePath[0] != '\0') {
      char profFile[1280];
      sprintf(profFile, "%s-c2prof.csv", exePath);

      FILE* f = fopen(profFile, "w");
      if (f != NULL) {
         fprintf(f, "Module,Layer,Section,Procedure,CallCount\n");
         for (int i = 0; i < c2DebugInfo->procCount; i++) {
            C2ProcInfo* proc = &c2DebugInfo->procs[i];

            // Parse container into module, layer, and section
            char temp[256];
            strncpy(temp, proc->container, 255);
            temp[255] = '\0';

            char* parts[3] = {NULL, NULL, NULL};
            int partCount = 0;
            char* token = strtok(temp, ".");
            while (token != NULL && partCount < 3) {
               parts[partCount++] = token;
               token = strtok(NULL, ".");
            }

            // Write CSV row
            fprintf(f, "\"%s\",\"%s\",\"%s\",\"%s\",%llu\n",
               parts[0] ? parts[0] : "",
               parts[1] ? parts[1] : "",
               parts[2] ? parts[2] : "",
               proc->name,
               proc->callCount);
         }
         fclose(f);
         fprintf(stderr, "Profiling data has been generated into file: %s\n", profFile);
      }
   }
#endif

   c2SaveDebugState();
   _Exit(code);
}
/////////////////////////////////////////////////////////////////////////////////
// ANSI color codes for colored output
//////////////////////////////////////////////////////////////////////////////////
#define ANSI_COLOR_RESET "\x1b[0m"

char* ansi_fg(AnsiColor color) {
   static char fg_colors[98][16];
   static bool initialized = false;

   if (!initialized) {
      // Initialize all foreground colors on first call
      for (int i = 30; i <= 37; i++) snprintf(fg_colors[i], 16, "\x1b[%dm", i);
      snprintf(fg_colors[38], 16, "%s", ANSI_COLOR_RESET);
      for (int i = 90; i <= 97; i++) snprintf(fg_colors[i], 16, "\x1b[%dm", i);
      initialized = true;
   }

   return fg_colors[color];
}

char* ansi_bg(AnsiColor color) {
   static char bg_colors[98][16];
   static bool initialized = false;

   if (!initialized) {
      // Initialize all background colors on first call
      for (int i = 30; i <= 37; i++) snprintf(bg_colors[i], 16, "\x1b[%dm", i + 10);
      snprintf(bg_colors[38], 16, "%s", ANSI_COLOR_RESET);
      for (int i = 90; i <= 97; i++) snprintf(bg_colors[i], 16, "\x1b[%dm", i + 10);
      initialized = true;
   }

   return bg_colors[color];
}