//=============================================================================
// CDL2.h - Common definitions and utilities for the CDL2 project
// This file is part of the CDL2 project and is included in code generated by the C code genrator
//=============================================================================

#define _CRT_SECURE_NO_WARNINGS

//Add any necessary includes here.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#ifdef WINDOWS
void debug_pause() {
    system("pause");
}
#else
// No equivalent of system("pause") on Linux and mac, so we just print a message and wait for user input.
void debug_pause() {
    printf("Press Enter to continue...");
    getchar();
}
#endif

// Define the some convenient types and macros for use in generated code. The "#define VALUE  type" (usually "long") is expected to be before this file is included.
#define BOOL VALUE
#define TRUE 1
#define FALSE 0
#define RETURNV(res) return res
#define RETURN return
#define PREDICATE BOOL
#define TEST BOOL
#define ACTION void
#define FUNCTION void
#define PROC
#define MACRO

#define ADD_LIST(name,value,lwb,upb)
#define ADD_VAR(name,value)

/* CDL2 Standard Macros for Lists */
#define CDL2_DECLARE_LIST(name, lwb, upb) \
    VALUE name##_array[(upb) - (lwb) + 1]; \
    VALUE name##_lwb = (lwb); \
    VALUE name##_upb = (upb); \
    ADD_LIST(name,&name##_array,lwb,upb)

#define CDL2_LIST_GET(name, i) \
    ((i) < name##_lwb || (i) > name##_upb ? \
        (fprintf(stderr, "Index out of bounds: %ld not in [%ld..%ld]\\n", (VALUE)(i), name##_lwb, name##_upb), exit(1), 0) : \
        name##_array[(i) - name##_lwb])

#define CDL2_LIST_SET(name, i, value) \
    do { \
        if ((i) < name##_lwb || (i) > name##_upb) { \
            fprintf(stderr, "Index out of bounds: %ld not in [%ld..%ld]\\n", (VALUE)(i), name##_lwb, name##_upb); \
            exit(1); \
        } \
        name##_array[(i) - name##_lwb] = (value); \
    } while(0)

#define CDL2_LIST_SWAP(name, i, j) \
    do { \
        VALUE temp; \
        if ((i) < name##_lwb || (i) > name##_upb || (j) < name##_lwb || (j) > name##_upb) { \
            fprintf(stderr, "Index out of bounds in swap\\n"); \
            exit(1); \
        } \
        temp = name##_array[(i) - name##_lwb]; \
        name##_array[(i) - name##_lwb] = name##_array[(j) - name##_lwb]; \
        name##_array[(j) - name##_lwb] = temp; \
    } while(0)

#define DECLARE_VAR(name,initial) \
    VALUE name = initial; \
    ADD_VAR(name, &name)

//==============================================================================
// Place any C code here that cannot be contained in macros.
//==============================================================================

// Define a sort comparer
int cmpvalue(const void *a, const void *b) { return (*(VALUE*)a - *(VALUE*)b); }
