// This file is part of the CDL2 project and is included in code generated by the C code genrator
// Place any C code here that cannot be contained in macros.

int cmplong(const void *a, const void *b) { return (*(long*)a - *(long*)b); }
