#!/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
$DIR/CDL2v1-Linux --sources Quicksort.cdl2 --output-dir . --allow-errors --messages Warning --lab --program "csharp sort" --console -v0 -d0 "$@"
