//=============================================================================
// CDL2.h - Common definitions and utilities for the CDL2 project
// This file is part of the CDL2 project and is included in 
// code generated by the C code genrator.
//=============================================================================

#define _CRT_SECURE_NO_WARNINGS
#define CDL2H

#include <stdint.h>
#include <limits.h>
#define VALUE long long
#define VALUE_MAX LLONG_MAX   
#define VALUE_MIN LLONG_MIN
#define VALUE_UNDEFINED VALUE_MIN
#define VALUE_FMT "ll"

#define VALUE_DEC_FORMAT "%" VALUE_FMT "d"
#define VALUE_UDEC_FORMAT "%" VALUE_FMT "u"
#define VALUE_HEX_FORMAT "%" VALUE_FMT "x"

#define VALUE_FMTC(n,b) "%0" #n VALUE_FMT b
#define VALUE_DEC_FMT(n) VALUE_FMTC(n,"d")
#define VALUE_HEX_FMT(n) VALUE_FMTC(n,"x")

// Format helper for string literal concatenation with VALUE format macros
#define FMT(s) s

//Add any necessary includes here.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>

#ifdef WINDOWS
void debug_pause() {
    system("pause");
}
#else
// No equivalent of system("pause") on Linux and mac, so we just print a message and wait for user input.
void debug_pause() {
    printf("Press Enter to continue...");
    getchar();
}
#endif

void c2Abort(char* msg) {
   fprintf(stderr, "\x1b[31mABORT in %s\x1b[0m\\n", msg);
   exit(1);
}

// Define control constructs that have to be redefined when code with -trace is generated
#define ENTER(index,affixes,locals)
#define RETURNV(v) return v
#define RETURN return
#define ABORT(msg,index) c2Abort(msg)



// Define the some convenient types and macros for use in generated code.
//VALUE must already be defined.
#define BOOL VALUE
#define TRUE 1
#define FALSE 0
#define PREDICATE BOOL
#define TEST BOOL
#define ACTION void
#define FUNCTION void
#define PROC
#define MACRO

#define DECLARE_VAR(name) \
    VALUE name = VALUE_UNDEFINED

/* CDL2 Standard Macros for Lists */
#define DECLARE_LIST(name, lwb, upb) \
    VALUE name##_array[(upb) - (lwb) + 1]; \
    int name##_lwb = (int)(lwb); \
    int name##_upb = (int)(upb)

// Define a common bounds check macro
#define CDL2_BOUNDS_CHECK(name, i, action) \
    ((int)(i) >= name##_lwb && (int)(i) <= name##_upb) ? \
    true : \
    (fprintf(stderr, "%s: Index %d out of bounds in LIST %s(%d:%d)\n", action, (int)(i), #name, name##_lwb, name##_upb), exit(1), false)

#define CDL2_LIST_GET(name, i) \
    (CDL2_BOUNDS_CHECK(name, i, "GET") ? \
        name##_array[(int)(i) - name##_lwb] : VALUE_UNDEFINED)

#define CDL2_LIST_SET(name, i, value) \
    { \
        CDL2_BOUNDS_CHECK(name, i, "SET"); \
        name##_array[(int)(i) - name##_lwb] = (value); \
    }

#define CDL2_LIST_SWAP(name, i, j) \
    { \
        CDL2_BOUNDS_CHECK(name, i, "SWAP(...,i,...)"); \
        CDL2_BOUNDS_CHECK(name, j, "SWAP(...,...,j)"); \
        VALUE temp = name##_array[(int)(i) - name##_lwb]; \
        name##_array[(int)(i) - name##_lwb] = name##_array[(int)(j) - name##_lwb]; \
        name##_array[(int)(j) - name##_lwb] = temp; \
    }

    

//==============================================================================
// Place any C code here that cannot be contained in macros.
//==============================================================================

// Define a sort comparer
int cmpvalue(const void *a, const void *b) { VALUE d =  (*(VALUE*)a - *(VALUE*)b); return d < 0 ? -1 : (d > 0 ? 1 : 0); }
