
//cspell:disable
/*
 * C# program generated by CDL2 v1.0.0 for PROGRAM csharp sort at 2025-12-18 13:11:05.
 */

using System;

namespace CDL2Generated {
   public class BoundedArray<T> {
      public int LowerBound { get; }
      public int UpperBound { get; }
      private readonly T[] array;

      public BoundedArray(int lowerBound, int upperBound) {
         if (upperBound - lowerBound < 0)
            throw new ArgumentException($"Upper bound {upperBound} must be greater than or equal to lower bound {lowerBound}.");
         LowerBound = lowerBound;
         UpperBound = upperBound;
         array = new T[upperBound - lowerBound + 1];
      }

      private void CheckIndex(params int[] indices) {
         foreach (int index in indices) {
            if (index < LowerBound || index > UpperBound)
               throw new IndexOutOfRangeException($"Index: {index}, LowerBound: {LowerBound}, UpperBound: {UpperBound}");
         }
      }

      public T this[int index] {
         get { CheckIndex(index); return array[index - LowerBound]; }
         set { CheckIndex(index); array[index - LowerBound] = value; }
      }

      public void Swap(int i, int j) {
         CheckIndex(i, j);
         (array[i - LowerBound], array[j - LowerBound]) = (array[j - LowerBound], array[i - LowerBound]);
      }
   }

   public static class Program {
      //===============================================================================

// Begin PROG csharp sort
public static void Main(string[] args) {
   try {
      
      // ##### 6 Consts #####
      
      private const Int64 csharpkernel_kernel_arithmetic_constx = 1;
      private const Int64 quicksort_base_parametrization_upb = 1000;
      private const Int64 quicksort_base_parametrization_lwb = 1;
      private const Int64 quicksort_base_parametrization_minrandom = 0;
      private const Int64 quicksort_base_parametrization_maxrandom = 200;
      private const Int64 quicksort_base_parametrization_maxsizeoflisttoshow = 100;
      
      // ##### 3 Vars #####
      
      private static Int64 csharpkernel_kernel_data_datasize = 486989713  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
      private static Int64 csharpkernel_kernel_timer_start = 996311376  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
      private static Int64 csharpkernel_kernel_timer_stop = 774944220  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
      
      // ##### 1 LIST #####
      
      private static BoundedArray<Int64> csharpkernel_kernel_data_data = new BoundedArray<Int64>(quicksort_base_parametrization_lwb, quicksort_base_parametrization_upb);
      
      // ##### 23 Macros #####
      
      
      // FUNCTION add+>a+>b+c> =
      //    c " = " a " + " b ";".
      private static void csharpkernel_kernel_arithmetic_add(Int64 a, Int64 b, ref Int64 c) {
         c = a + b;
      }
      
      // FUNCTION subtract+>a+>b+c> =
      //    c " = " a " - " b ";".
      private static void csharpkernel_kernel_arithmetic_subtract(Int64 a, Int64 b, ref Int64 c) {
         c = a - b;
      }
      
      // FUNCTION incr+>a> =
      //    a "++;".
      private static void csharpkernel_kernel_arithmetic_incr(ref Int64 a) {
         a++;
      }
      
      // FUNCTION make+a>+>b =
      //    a " = " b ";".
      private static void csharpkernel_kernel_arithmetic_make(ref Int64 a, Int64 b) {
         a = b;
      }
      
      // TEST le+>a+>b =
      //    a " <= " b.
      private static bool csharpkernel_kernel_arithmetic_le(Int64 a, Int64 b) {
         return a <= b;
      }
      
      // FUNCTION random+>min+>max+r> =
      //    r " = System.Random.Shared.Next(" min ", " max " + 1);".
      private static void csharpkernel_kernel_arithmetic_random(Int64 min, Int64 max, ref Int64 r) {
         r = System.Random.Shared.Next(min, max + 1);
      }
      
      // ACTION set element+>i+>v =
      //    data "[" i "] = " v ";".
      private static void csharpkernel_kernel_data_setelement(Int64 i, Int64 v) {
         csharpkernel_kernel_data_data[i] = v;
      }
      
      // ACTION show msg no newline*string =
      //    "System.Console.Write(" string ");".
      private static void csharpkernel_kernel_messages_showmsgnonewline(string string) {
         System.Console.Write(string);
      }
      
      // ACTION dump list =
      //    "for (int i = " lwb " ; i <= " upb " ; i++) System.Console.Write(" data "[i]);".
      private static void csharpkernel_kernel_data_dumplist() {
         for (int i = quicksort_base_parametrization_lwb ; i <= quicksort_base_parametrization_upb ; i++) System.Console.Write(csharpkernel_kernel_data_data[i]);
      }
      
      // ACTION show msg*string =
      //    "System.Console.WriteLine(" string ");".
      private static void csharpkernel_kernel_messages_showmsg(string string) {
         System.Console.WriteLine(string);
      }
      
      // FUNCTION touch out+v> =
      //    "".
      private static void quicksort_base_touch_touchout(ref Int64 v) {
         }
      
      // FUNCTION touch in+>v =
      //    "".
      private static void quicksort_base_touch_touchin(Int64 v) {
         }
      
      // TEST is data sorted macro -i -r =
      //    r " = true;" 
      //    "$Lfor (" i " = " lwb "; " i " < " upb "; " i "++) {" 
      //    "$L   if (" data "[" i "] > " data "[" i " + 1]) {" 
      //    "$L      " r " = false;" 
      //    "$L      break;" 
      //    "$L   }" 
      //    "$L}" 
      //    "$L" r.
      private static bool csharpkernel_kernel_data_isdatasortedmacro() {
         Int64 i = 150123469  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         Int64 r = 1572908451  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         r = true;
         for (i = quicksort_base_parametrization_lwb; i < quicksort_base_parametrization_upb; i++) {
            if (csharpkernel_kernel_data_data[i] > csharpkernel_kernel_data_data[i + 1]) {
               r = false;
               break;
            }
         }
         return r;
      }
      
      // ACTION show number+>number =
      //    "System.Console.Write($$$"{" number ":N0}$");".
      private static void csharpkernel_kernel_messages_shownumber(Int64 number) {
         System.Console.Write($"{number:N0}");
      }
      
      // ACTION start timer =
      //    start " = System.DateTime.Now.Ticks;".
      private static void csharpkernel_kernel_timer_starttimer() {
         csharpkernel_kernel_timer_start = System.DateTime.Now.Ticks;
      }
      
      // TEST lt+>a+>b =
      //    a " < " b.
      private static bool csharpkernel_kernel_arithmetic_lt(Int64 a, Int64 b) {
         return a < b;
      }
      
      // FUNCTION halve+>a> =
      //    a " /= 2;".
      private static void csharpkernel_kernel_arithmetic_halve(ref Int64 a) {
         a /= 2;
      }
      
      // TEST smaller element+>p+>q =
      //    data "[" p "] < " data "[" q "]".
      private static bool csharpkernel_kernel_data_smallerelement(Int64 p, Int64 q) {
         return csharpkernel_kernel_data_data[p] < csharpkernel_kernel_data_data[q];
      }
      
      // FUNCTION decr+>a> =
      //    a "--;".
      private static void csharpkernel_kernel_arithmetic_decr(ref Int64 a) {
         a--;
      }
      
      // ACTION swap element+>i+>j =
      //    data ".Swap(" i ", " j ");".
      private static void csharpkernel_kernel_data_swapelement(Int64 i, Int64 j) {
         csharpkernel_kernel_data_data.Swap(i, j);
      }
      
      // ACTION stop timer =
      //    stop " = System.DateTime.Now.Ticks;".
      private static void csharpkernel_kernel_timer_stoptimer() {
         csharpkernel_kernel_timer_stop = System.DateTime.Now.Ticks;
      }
      
      // ACTION show elapsed time =
      //    "System.Console.WriteLine($$$"Elapsed time: {((" stop " - " start 
      //    ") / 10000.0):N0} milliseconds$");".
      private static void csharpkernel_kernel_timer_showelapsedtime() {
         System.Console.WriteLine($"Elapsed time: {((csharpkernel_kernel_timer_stop - csharpkernel_kernel_timer_start) / 10000.0):N0} milliseconds");
      }
      
      // ACTION sort data =
      //    "System.Array.Sort(" data ");".
      private static void csharpkernel_kernel_data_sortdata() {
         System.Array.Sort(csharpkernel_kernel_data_data);
      }
      
      // ##### 12 Procedures #####
      
      
      // ACTION initialize data -i -r -z :
      //    add+const x+const x+z, subtract+upb+lwb+data size, incr+data size, make+i+lwb, 
      //       (le+i+upb, random+min random+max random+r, set element+i+r, incr+i, *;
      //        +).
      private static void csharpkernel_kernel_data_initializedata() {
         Int64 i = 286286459  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         Int64 r = 1199950945  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         Int64 z = 1024393719  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         // Alternative 1
         csharpkernel_kernel_arithmetic_add(csharpkernel_kernel_arithmetic_constx, csharpkernel_kernel_arithmetic_constx, ref z);
         csharpkernel_kernel_arithmetic_subtract(quicksort_base_parametrization_upb, quicksort_base_parametrization_lwb, ref csharpkernel_kernel_data_datasize);
         csharpkernel_kernel_arithmetic_incr(ref csharpkernel_kernel_data_datasize);
         csharpkernel_kernel_arithmetic_make(ref i, quicksort_base_parametrization_lwb);
         // Group
         while (true) {
            // Alternative 1
            if (csharpkernel_kernel_arithmetic_le(i, quicksort_base_parametrization_upb)) {
               csharpkernel_kernel_arithmetic_random(quicksort_base_parametrization_minrandom, quicksort_base_parametrization_maxrandom, ref r);
               csharpkernel_kernel_data_setelement(i, r);
               csharpkernel_kernel_arithmetic_incr(ref i);
               continue;
            }
            // End Alternative 1
            // Alternative 2
            return;
            // End Alternative 2
            break;
         }
         // End Group
         // End Alternative 1
         return;
      }
      
      // ACTION run demo -data size :
      //    initialize data, dump data+"Data before sorting: ", verify data sorted+"Random", 
      //       get data size+data size, show msg no newline+"Running quicksort on list of ", 
      //          show number+data size, show msg+" elements.", start timer, quicksort+lwb+upb, stop timer, 
      //             show elapsed time, dump data+"Data after sorting: ", verify data sorted+"Quicksort-ed", 
      //             initialize data, show msg+"Running .NET sort on list.", start timer, sort data, 
      //             stop timer, show elapsed time.
      private static void quicksort_sort_sorter_rundemo() {
         Int64 datasize = 774491540  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         // Alternative 1
         csharpkernel_kernel_data_initializedata();
         csharpkernel_kernel_data_dumpdata("Data before sorting: ");
         quicksort_sort_sorter_verifydatasorted("Random");
         csharpkernel_kernel_data_getdatasize(ref datasize);
         csharpkernel_kernel_messages_showmsgnonewline("Running quicksort on list of ");
         csharpkernel_kernel_messages_shownumber(datasize);
         csharpkernel_kernel_messages_showmsg(" elements.");
         csharpkernel_kernel_timer_starttimer();
         quicksort_sort_sorter_quicksort(quicksort_base_parametrization_lwb, quicksort_base_parametrization_upb);
         csharpkernel_kernel_timer_stoptimer();
         csharpkernel_kernel_timer_showelapsedtime();
         csharpkernel_kernel_data_dumpdata("Data after sorting: ");
         quicksort_sort_sorter_verifydatasorted("Quicksort-ed");
         csharpkernel_kernel_data_initializedata();
         csharpkernel_kernel_messages_showmsg("Running .NET sort on list.");
         csharpkernel_kernel_timer_starttimer();
         csharpkernel_kernel_data_sortdata();
         csharpkernel_kernel_timer_stoptimer();
         csharpkernel_kernel_timer_showelapsedtime();
         return;
         // End Alternative 1
         return;
      }
      
      // ACTION dump data*msg :
      //    show msg no newline+msg, 
      //       (le+data size+max size of list to show, dump list;
      //        show msg+"too many elements to show.").
      private static void csharpkernel_kernel_data_dumpdata(string msg) {
         // Alternative 1
         csharpkernel_kernel_messages_showmsgnonewline(msg);
         // Group
            // Alternative 1
            if (csharpkernel_kernel_arithmetic_le(csharpkernel_kernel_data_datasize, quicksort_base_parametrization_maxsizeoflisttoshow)) {
               csharpkernel_kernel_data_dumplist();
               return;
            }
            // End Alternative 1
            // Alternative 2
            csharpkernel_kernel_messages_showmsg("too many elements to show.");
            return;
            // End Alternative 2
         // End Group
         // End Alternative 1
         return;
      }
      
      // ACTION verify data sorted*which :
      //    is data sorted, show msg no newline+which, show msg+" data is sorted.";
      //    show msg no newline+which, show msg+" data is not sorted.".
      private static void quicksort_sort_sorter_verifydatasorted(string which) {
         // Alternative 1
         if (quicksort_sort_sorter_isdatasorted()) {
            csharpkernel_kernel_messages_showmsgnonewline(which);
            csharpkernel_kernel_messages_showmsg(" data is sorted.");
            return;
         }
         // End Alternative 1
         // Alternative 2
         csharpkernel_kernel_messages_showmsgnonewline(which);
         csharpkernel_kernel_messages_showmsg(" data is not sorted.");
         return;
         // End Alternative 2
         return;
      }
      
      // PREDICATE is data sorted -where :
      //    use macro for sortedness test, touch out+where, touch in+where, is data sorted macro;
      //    is data unsorted procedure+where, show msg no newline+"Unsorted at ", show number+where, 
      //       show msg+".", -;
      //    +.
      private static bool quicksort_sort_sorter_isdatasorted() {
         Int64 where = 1922256649  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         // Alternative 1
         quicksort_base_touch_touchout(ref where);
         quicksort_base_touch_touchin(where);
         if (csharpkernel_kernel_data_isdatasortedmacro()) {
            return true;
         }
         // End Alternative 1
         // Alternative 2
         // Alternative suppressed by previous conditional compilation ON
         // End Alternative 2
         // Alternative 3
         // Alternative suppressed by previous conditional compilation ON
         // End Alternative 3
         return false;
      }
      
      // TEST use macro for sortedness test :
      //    +.
      
      // FUNCTION get data size+size> :
      //    make+size+data size.
      private static void csharpkernel_kernel_data_getdatasize(ref Int64 size) {
         // Alternative 1
         csharpkernel_kernel_arithmetic_make(ref size, csharpkernel_kernel_data_datasize);
         return;
         // End Alternative 1
         return;
      }
      
      // ACTION quicksort+>from+>to -p -q :
      //    less+from+to, split+from+to+p+q, quicksort+from+q, quicksort+p+to;
      //    +.
      private static void quicksort_sort_sorter_quicksort(Int64 from, Int64 to) {
         Int64 p = 260568903  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         Int64 q = 1200918076  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         // Alternative 1
         if (quicksort_base_arithmetic_less(from, to)) {
            quicksort_sort_sorter_split(from, to, ref p, ref q);
            quicksort_sort_sorter_quicksort(from, q);
            quicksort_sort_sorter_quicksort(p, to);
            return;
         }
         // End Alternative 1
         // Alternative 2
         return;
         // End Alternative 2
         return;
      }
      
      // TEST less+>a+>b :
      //    lt+a+b.
      private static bool quicksort_base_arithmetic_less(Int64 a, Int64 b) {
         // Alternative 1
         if (csharpkernel_kernel_arithmetic_lt(a, b)) {
            return true;
         }
         // End Alternative 1
         return false;
      }
      
      // ACTION split+>i+>j+p>+q> -m :
      //    make+p+i, make+q+j, add+i+j+m, halve+m, 
      //       (again:move p up+j+p+m, move q down+i+q+m, 
      //          (less+p+q, swap element+p+q, incr+p, decr+q, *again;
      //           less+p+m, swap element+p+m,  incr+p;
      //           less+m+q, swap element+q+m,  decr+q;
      //           +)).
      private static void quicksort_sort_sorter_split(Int64 i, Int64 j, ref Int64 p, ref Int64 q) {
         Int64 m = 2082579534  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         // Alternative 1
         csharpkernel_kernel_arithmetic_make(ref p, i);
         csharpkernel_kernel_arithmetic_make(ref q, j);
         csharpkernel_kernel_arithmetic_add(i, j, ref m);
         csharpkernel_kernel_arithmetic_halve(ref m);
         // Group
         while (true) {
            // Alternative 1
            quicksort_sort_sorter_movepup(j, ref p, m);
            quicksort_sort_sorter_moveqdown(i, ref q, m);
            // Group
               // Alternative 1
               if (quicksort_base_arithmetic_less(p, q)) {
                  csharpkernel_kernel_data_swapelement(p, q);
                  csharpkernel_kernel_arithmetic_incr(ref p);
                  csharpkernel_kernel_arithmetic_decr(ref q);
                  continue;
               }
               // End Alternative 1
               // Alternative 2
               if (quicksort_base_arithmetic_less(p, m)) {
                  csharpkernel_kernel_data_swapelement(p, m);
                  csharpkernel_kernel_arithmetic_incr(ref p);
                  return;
               }
               // End Alternative 2
               // Alternative 3
               if (quicksort_base_arithmetic_less(m, q)) {
                  csharpkernel_kernel_data_swapelement(q, m);
                  csharpkernel_kernel_arithmetic_decr(ref q);
                  return;
               }
               // End Alternative 3
               // Alternative 4
               return;
               // End Alternative 4
            // End Group
            // End Alternative 1
            break;
         }
         // End Group
         // End Alternative 1
         return;
      }
      
      // FUNCTION move p up+>j+>p>+>m :
      //    less+j+p;
      //    smaller element+m+p;
      //    incr+p, *.
      private static void quicksort_sort_sorter_movepup(Int64 j, ref Int64 p, Int64 m) {
         while (true) {
            // Alternative 1
            if (quicksort_base_arithmetic_less(j, p)) {
               return;
            }
            // End Alternative 1
            // Alternative 2
            if (csharpkernel_kernel_data_smallerelement(m, p)) {
               return;
            }
            // End Alternative 2
            // Alternative 3
            csharpkernel_kernel_arithmetic_incr(ref p);
            continue;
            // End Alternative 3
            return;
         }
         return;
      }
      
      // FUNCTION move q down+>i+>q>+>m :
      //    less+q+i;
      //    smaller element+q+m;
      //    decr+q, *.
      private static void quicksort_sort_sorter_moveqdown(Int64 i, ref Int64 q, Int64 m) {
         while (true) {
            // Alternative 1
            if (quicksort_base_arithmetic_less(q, i)) {
               return;
            }
            // End Alternative 1
            // Alternative 2
            if (csharpkernel_kernel_data_smallerelement(q, m)) {
               return;
            }
            // End Alternative 2
            // Alternative 3
            csharpkernel_kernel_arithmetic_decr(ref q);
            continue;
            // End Alternative 3
            return;
         }
         return;
      }
      
      // ##### 2 Synthetic Procedures #####
      
      // MOD csharp kernel LAY kernel SEC data ACTION PRELUDE
      private static void csharpkernel_kernel_data__PRELUDE() {
         // Alternative 1
         csharpkernel_kernel_data_initializedata();
         return;
         // End Alternative 1
         return;
      }
      // MOD quicksort LAY sort SEC sorter ACTION ROOT
      private static void quicksort_sort_sorter__ROOT() {
         // Alternative 1
         quicksort_sort_sorter_rundemo();
         return;
         // End Alternative 1
         return;
      }
      
      // PROGRAM csharp sort.
      //    PART csharp kernel, quicksort.
      //    PRELUDE csharp kernel.
      //    ROOT quicksort.
      // ENDPROG csharp sort.
      // 
      // Program Ludes
      // MOD_csharpkernel__PRELUDE
         csharpkernel_kernel_data__PRELUDE();
      // MOD_quicksort__ROOT
         quicksort_sort_sorter__ROOT();
   } catch (Exception ex) {
      Console.WriteLine($"Error: {ex.Message}");
      Console.WriteLine($"Stack Trace:\n{ex.StackTrace}");
   }
}
// End PROG csharp sort
   }
}
