
//cspell:disable
/*
 * C# program generated by CDL2 v1.0.0 for PROGRAM csharp sort at 2025-12-21 12:37:23.
 */

using System;

#pragma warning disable CS0162 // Unreachable code detected
#pragma warning disable CS0219 // Variable is assigned but its value is never used

namespace CDL2Generated {
   public class BoundedArray<T> {
      public Int64 LowerBound { get; }
      public Int64 UpperBound { get; }
      public readonly T[] array;

      public BoundedArray(Int64 lowerBound, Int64 upperBound) {
         if (upperBound - lowerBound < 0)
            throw new ArgumentException($"Upper bound {upperBound} must be greater than or equal to lower bound {lowerBound}.");
         LowerBound = lowerBound;
         UpperBound = upperBound;
         array = new T[upperBound - lowerBound + 1];
      }

      private void CheckIndex(params Int64[] indices) {
         foreach (int index in indices) {
            if (index < LowerBound || index > UpperBound)
               throw new IndexOutOfRangeException($"Index: {index}, LowerBound: {LowerBound}, UpperBound: {UpperBound}");
         }
      }

      public T this[Int64 index] {
         get { CheckIndex(index); return array[index - LowerBound]; }
         set { CheckIndex(index); array[index - LowerBound] = value; }
      }

      public void Swap(Int64 i, Int64 j) {
         CheckIndex(i, j);
         (array[i - LowerBound], array[j - LowerBound]) = (array[j - LowerBound], array[i - LowerBound]);
      }
   }

   public static class Program {
      //===============================================================================

// Begin PROG csharp sort

// ##### 6 Consts #####

private const long csharpkernel_kernel_arithmetic_constx = 1;
private const long quicksort_base_parametrization_upb = 1000;
private const long quicksort_base_parametrization_lwb = 1;
private const long quicksort_base_parametrization_minrandom = 0;
private const long quicksort_base_parametrization_maxrandom = 200;
private const long quicksort_base_parametrization_maxsizeoflisttoshow = 100;

// ##### 3 Vars #####

private static long v_csharpkernel_kernel_data_datasize = 2030439060  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
private static long v_csharpkernel_kernel_timer_start = 2052543344  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
private static long v_csharpkernel_kernel_timer_stop = 1743728266  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;

// ##### 1 LIST #####

private static BoundedArray<long> csharpkernel_kernel_data_data = new BoundedArray<long>(quicksort_base_parametrization_lwb, quicksort_base_parametrization_upb);

// ##### 23 Macros #####


// FUNCTION add+>a+>b+c> =
//    c " = " a " + " b ";".
private static void csharpkernel_kernel_arithmetic_add(long a_a, long a_b, ref long a_c) {
   a_c = a_a + a_b;
}

// FUNCTION subtract+>a+>b+c> =
//    c " = " a " - " b ";".
private static void csharpkernel_kernel_arithmetic_subtract(long a_a, long a_b, ref long a_c) {
   a_c = a_a - a_b;
}

// FUNCTION incr+>a> =
//    a "++;".
private static void csharpkernel_kernel_arithmetic_incr(ref long a_a) {
   a_a++;
}

// FUNCTION make+a>+>b =
//    a " = " b ";".
private static void csharpkernel_kernel_arithmetic_make(ref long a_a, long a_b) {
   a_a = a_b;
}

// TEST le+>a+>b =
//    a " <= " b.
private static bool csharpkernel_kernel_arithmetic_le(long a_a, long a_b) {
   return a_a <= a_b;
}

// FUNCTION random+>min+>max+r> =
//    r " = System.Random.Shared.Next((int)" min ", (int)" max " + 1);".
private static void csharpkernel_kernel_arithmetic_random(long a_min, long a_max, ref long a_r) {
   a_r = System.Random.Shared.Next((int)a_min, (int)a_max + 1);
}

// ACTION set element+>i+>v =
//    data "[" i "] = " v ";".
private static void csharpkernel_kernel_data_setelement(long a_i, long a_v) {
   csharpkernel_kernel_data_data[a_i] = a_v;
}

// ACTION show msg no newline*string =
//    "System.Console.Write(" string ");".
private static void csharpkernel_kernel_messages_showmsgnonewline(string a_string) {
   System.Console.Write(a_string);
}

// ACTION dump list =
//    "for (int i = (int)" lwb " ; i <= (int)" upb " ; i++) System.Console.Write(" data "[i]);".
private static void csharpkernel_kernel_data_dumplist() {
   for (int i = (int)quicksort_base_parametrization_lwb ; i <= (int)quicksort_base_parametrization_upb ; i++) System.Console.Write(csharpkernel_kernel_data_data[i]);
}

// ACTION show msg*string =
//    "System.Console.WriteLine(" string ");".
private static void csharpkernel_kernel_messages_showmsg(string a_string) {
   System.Console.WriteLine(a_string);
}

// FUNCTION touch out+v> =
//    "".
private static void quicksort_base_touch_touchout(ref long a_v) {
   }

// FUNCTION touch in+>v =
//    "".
private static void quicksort_base_touch_touchin(long a_v) {
   }

// TEST is data sorted macro -i -r =
//    r " = 1;" 
//    "$Lfor (" i " = " lwb "; " i " < " upb "; " i "++) {" 
//    "$L   if (" data "[" i "] > " data "[" i " + 1]) {" 
//    "$L      " r " = 0;" 
//    "$L      break;" 
//    "$L   }" 
//    "$L}" 
//    "$L" r "== 1".
private static bool csharpkernel_kernel_data_isdatasortedmacro() {
   long l_i = 1330710289  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   long l_r = 4708776  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   l_r = 1;
   for (l_i = quicksort_base_parametrization_lwb; l_i < quicksort_base_parametrization_upb; l_i++) {
      if (csharpkernel_kernel_data_data[l_i] > csharpkernel_kernel_data_data[l_i + 1]) {
         l_r = 0;
         break;
      }
   }
   return l_r== 1;
}

// ACTION show number+>number =
//    "System.Console.Write($$$"{" number ":N0}$");".
private static void csharpkernel_kernel_messages_shownumber(long a_number) {
   System.Console.Write($"{a_number:N0}");
}

// ACTION start timer =
//    start " = System.DateTime.Now.Ticks;".
private static void csharpkernel_kernel_timer_starttimer() {
   v_csharpkernel_kernel_timer_start = System.DateTime.Now.Ticks;
}

// TEST lt+>a+>b =
//    a " < " b.
private static bool csharpkernel_kernel_arithmetic_lt(long a_a, long a_b) {
   return a_a < a_b;
}

// FUNCTION halve+>a> =
//    a " /= 2;".
private static void csharpkernel_kernel_arithmetic_halve(ref long a_a) {
   a_a /= 2;
}

// TEST smaller element+>p+>q =
//    data "[" p "] < " data "[" q "]".
private static bool csharpkernel_kernel_data_smallerelement(long a_p, long a_q) {
   return csharpkernel_kernel_data_data[a_p] < csharpkernel_kernel_data_data[a_q];
}

// FUNCTION decr+>a> =
//    a "--;".
private static void csharpkernel_kernel_arithmetic_decr(ref long a_a) {
   a_a--;
}

// ACTION swap element+>i+>j =
//    data ".Swap(" i ", " j ");".
private static void csharpkernel_kernel_data_swapelement(long a_i, long a_j) {
   csharpkernel_kernel_data_data.Swap(a_i, a_j);
}

// ACTION stop timer =
//    stop " = System.DateTime.Now.Ticks;".
private static void csharpkernel_kernel_timer_stoptimer() {
   v_csharpkernel_kernel_timer_stop = System.DateTime.Now.Ticks;
}

// ACTION show elapsed time =
//    "System.Console.WriteLine($$$"Elapsed time: {((" stop " - " start 
//    ") / 10000.0):N0} milliseconds$");".
private static void csharpkernel_kernel_timer_showelapsedtime() {
   System.Console.WriteLine($"Elapsed time: {((v_csharpkernel_kernel_timer_stop - v_csharpkernel_kernel_timer_start) / 10000.0):N0} milliseconds");
}

// ACTION sort data =
//    "System.Array.Sort(" data ".array);".
private static void csharpkernel_kernel_data_sortdata() {
   System.Array.Sort(csharpkernel_kernel_data_data.array);
}

// ##### 12 Procedures #####


// ACTION initialize data -i -r -z :
//    add+const x+const x+z, subtract+upb+lwb+data size, incr+data size, make+i+lwb, 
//       (le+i+upb, random+min random+max random+r, set element+i+r, incr+i, *;
//        +).
private static void csharpkernel_kernel_data_initializedata() {
   long l_i = 1922214571  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   long l_r = 1486859305  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   long l_z = 1761612539  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   // Alternative 1
   csharpkernel_kernel_arithmetic_add(csharpkernel_kernel_arithmetic_constx, csharpkernel_kernel_arithmetic_constx, ref l_z);
   csharpkernel_kernel_arithmetic_subtract(quicksort_base_parametrization_upb, quicksort_base_parametrization_lwb, ref v_csharpkernel_kernel_data_datasize);
   csharpkernel_kernel_arithmetic_incr(ref v_csharpkernel_kernel_data_datasize);
   csharpkernel_kernel_arithmetic_make(ref l_i, quicksort_base_parametrization_lwb);
   // Group
   while (true) {
      // Alternative 1
      if (csharpkernel_kernel_arithmetic_le(l_i, quicksort_base_parametrization_upb)) {
         csharpkernel_kernel_arithmetic_random(quicksort_base_parametrization_minrandom, quicksort_base_parametrization_maxrandom, ref l_r);
         csharpkernel_kernel_data_setelement(l_i, l_r);
         csharpkernel_kernel_arithmetic_incr(ref l_i);
         continue;
      }
      // End Alternative 1
      // Alternative 2
      return;
      // End Alternative 2
      break;
   }
   // End Group
   // End Alternative 1
   return;
}

// ACTION run demo -data size :
//    initialize data, dump data+"Data before sorting: ", verify data sorted+"Random", 
//       get data size+data size, show msg no newline+"Running quicksort on list of ", 
//          show number+data size, show msg+" elements.", start timer, quicksort+lwb+upb, stop timer, 
//             show elapsed time, dump data+"Data after sorting: ", verify data sorted+"Quicksort-ed", 
//             initialize data, show msg+"Running .NET sort on list.", start timer, sort data, 
//             stop timer, show elapsed time.
private static void quicksort_sort_sorter_rundemo() {
   long l_datasize = 806617553  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   // Alternative 1
   csharpkernel_kernel_data_initializedata();
   csharpkernel_kernel_data_dumpdata("Data before sorting: ");
   quicksort_sort_sorter_verifydatasorted("Random");
   csharpkernel_kernel_data_getdatasize(ref l_datasize);
   csharpkernel_kernel_messages_showmsgnonewline("Running quicksort on list of ");
   csharpkernel_kernel_messages_shownumber(l_datasize);
   csharpkernel_kernel_messages_showmsg(" elements.");
   csharpkernel_kernel_timer_starttimer();
   quicksort_sort_sorter_quicksort(quicksort_base_parametrization_lwb, quicksort_base_parametrization_upb);
   csharpkernel_kernel_timer_stoptimer();
   csharpkernel_kernel_timer_showelapsedtime();
   csharpkernel_kernel_data_dumpdata("Data after sorting: ");
   quicksort_sort_sorter_verifydatasorted("Quicksort-ed");
   csharpkernel_kernel_data_initializedata();
   csharpkernel_kernel_messages_showmsg("Running .NET sort on list.");
   csharpkernel_kernel_timer_starttimer();
   csharpkernel_kernel_data_sortdata();
   csharpkernel_kernel_timer_stoptimer();
   csharpkernel_kernel_timer_showelapsedtime();
   return;
   // End Alternative 1
   return;
}

// ACTION dump data*msg :
//    show msg no newline+msg, 
//       (le+data size+max size of list to show, dump list;
//        show msg+"too many elements to show.").
private static void csharpkernel_kernel_data_dumpdata(string a_msg) {
   // Alternative 1
   csharpkernel_kernel_messages_showmsgnonewline(a_msg);
   // Group
      // Alternative 1
      if (csharpkernel_kernel_arithmetic_le(v_csharpkernel_kernel_data_datasize, quicksort_base_parametrization_maxsizeoflisttoshow)) {
         csharpkernel_kernel_data_dumplist();
         return;
      }
      // End Alternative 1
      // Alternative 2
      csharpkernel_kernel_messages_showmsg("too many elements to show.");
      return;
      // End Alternative 2
   // End Group
   // End Alternative 1
   return;
}

// ACTION verify data sorted*which :
//    is data sorted, show msg no newline+which, show msg+" data is sorted.";
//    show msg no newline+which, show msg+" data is not sorted.".
private static void quicksort_sort_sorter_verifydatasorted(string a_which) {
   // Alternative 1
   if (quicksort_sort_sorter_isdatasorted()) {
      csharpkernel_kernel_messages_showmsgnonewline(a_which);
      csharpkernel_kernel_messages_showmsg(" data is sorted.");
      return;
   }
   // End Alternative 1
   // Alternative 2
   csharpkernel_kernel_messages_showmsgnonewline(a_which);
   csharpkernel_kernel_messages_showmsg(" data is not sorted.");
   return;
   // End Alternative 2
   return;
}

// PREDICATE is data sorted -where :
//    use macro for sortedness test, touch out+where, touch in+where, is data sorted macro;
//    is data unsorted procedure+where, show msg no newline+"Unsorted at ", show number+where, 
//       show msg+".", -;
//    +.
private static bool quicksort_sort_sorter_isdatasorted() {
   long l_where = 1616583849  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   // Alternative 1
   quicksort_base_touch_touchout(ref l_where);
   quicksort_base_touch_touchin(l_where);
   if (csharpkernel_kernel_data_isdatasortedmacro()) {
      return true;
   }
   // End Alternative 1
   // Alternative 2
   // Alternative suppressed by previous conditional compilation ON
   // End Alternative 2
   // Alternative 3
   // Alternative suppressed by previous conditional compilation ON
   // End Alternative 3
   return false;
}

// TEST use macro for sortedness test :
//    +.

// FUNCTION get data size+size> :
//    make+size+data size.
private static void csharpkernel_kernel_data_getdatasize(ref long a_size) {
   // Alternative 1
   csharpkernel_kernel_arithmetic_make(ref a_size, v_csharpkernel_kernel_data_datasize);
   return;
   // End Alternative 1
   return;
}

// ACTION quicksort+>from+>to -p -q :
//    less+from+to, split+from+to+p+q, quicksort+from+q, quicksort+p+to;
//    +.
private static void quicksort_sort_sorter_quicksort(long a_from, long a_to) {
   long l_p = 1393431228  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   long l_q = 457847905  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   // Alternative 1
   if (quicksort_base_arithmetic_less(a_from, a_to)) {
      quicksort_sort_sorter_split(a_from, a_to, ref l_p, ref l_q);
      quicksort_sort_sorter_quicksort(a_from, l_q);
      quicksort_sort_sorter_quicksort(l_p, a_to);
      return;
   }
   // End Alternative 1
   // Alternative 2
   return;
   // End Alternative 2
   return;
}

// TEST less+>a+>b :
//    lt+a+b.
private static bool quicksort_base_arithmetic_less(long a_a, long a_b) {
   // Alternative 1
   if (csharpkernel_kernel_arithmetic_lt(a_a, a_b)) {
      return true;
   }
   // End Alternative 1
   return false;
}

// ACTION split+>i+>j+p>+q> -m :
//    make+p+i, make+q+j, add+i+j+m, halve+m, 
//       (again:move p up+j+p+m, move q down+i+q+m, 
//          (less+p+q, swap element+p+q, incr+p, decr+q, *again;
//           less+p+m, swap element+p+m,  incr+p;
//           less+m+q, swap element+q+m,  decr+q;
//           +)).
private static void quicksort_sort_sorter_split(long a_i, long a_j, ref long a_p, ref long a_q) {
   long l_m = 2095128004  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
   // Alternative 1
   csharpkernel_kernel_arithmetic_make(ref a_p, a_i);
   csharpkernel_kernel_arithmetic_make(ref a_q, a_j);
   csharpkernel_kernel_arithmetic_add(a_i, a_j, ref l_m);
   csharpkernel_kernel_arithmetic_halve(ref l_m);
   // Group
   while (true) {
      // Alternative 1
      quicksort_sort_sorter_movepup(a_j, ref a_p, l_m);
      quicksort_sort_sorter_moveqdown(a_i, ref a_q, l_m);
      // Group
         // Alternative 1
         if (quicksort_base_arithmetic_less(a_p, a_q)) {
            csharpkernel_kernel_data_swapelement(a_p, a_q);
            csharpkernel_kernel_arithmetic_incr(ref a_p);
            csharpkernel_kernel_arithmetic_decr(ref a_q);
            continue;
         }
         // End Alternative 1
         // Alternative 2
         if (quicksort_base_arithmetic_less(a_p, l_m)) {
            csharpkernel_kernel_data_swapelement(a_p, l_m);
            csharpkernel_kernel_arithmetic_incr(ref a_p);
            return;
         }
         // End Alternative 2
         // Alternative 3
         if (quicksort_base_arithmetic_less(l_m, a_q)) {
            csharpkernel_kernel_data_swapelement(a_q, l_m);
            csharpkernel_kernel_arithmetic_decr(ref a_q);
            return;
         }
         // End Alternative 3
         // Alternative 4
         return;
         // End Alternative 4
      // End Group
      // End Alternative 1
      break;
   }
   // End Group
   // End Alternative 1
   return;
}

// FUNCTION move p up+>j+>p>+>m :
//    less+j+p;
//    smaller element+m+p;
//    incr+p, *.
private static void quicksort_sort_sorter_movepup(long a_j, ref long a_p, long a_m) {
   while (true) {
      // Alternative 1
      if (quicksort_base_arithmetic_less(a_j, a_p)) {
         return;
      }
      // End Alternative 1
      // Alternative 2
      if (csharpkernel_kernel_data_smallerelement(a_m, a_p)) {
         return;
      }
      // End Alternative 2
      // Alternative 3
      csharpkernel_kernel_arithmetic_incr(ref a_p);
      continue;
      // End Alternative 3
      return;
   }
   return;
}

// FUNCTION move q down+>i+>q>+>m :
//    less+q+i;
//    smaller element+q+m;
//    decr+q, *.
private static void quicksort_sort_sorter_moveqdown(long a_i, ref long a_q, long a_m) {
   while (true) {
      // Alternative 1
      if (quicksort_base_arithmetic_less(a_q, a_i)) {
         return;
      }
      // End Alternative 1
      // Alternative 2
      if (csharpkernel_kernel_data_smallerelement(a_q, a_m)) {
         return;
      }
      // End Alternative 2
      // Alternative 3
      csharpkernel_kernel_arithmetic_decr(ref a_q);
      continue;
      // End Alternative 3
      return;
   }
   return;
}

// ##### 2 Synthetic Procedures #####

// MOD csharp kernel LAY kernel SEC data ACTION PRELUDE
private static void csharpkernel_kernel_data__PRELUDE() {
   // Alternative 1
   csharpkernel_kernel_data_initializedata();
   return;
   // End Alternative 1
   return;
}
// MOD quicksort LAY sort SEC sorter ACTION ROOT
private static void quicksort_sort_sorter__ROOT() {
   // Alternative 1
   quicksort_sort_sorter_rundemo();
   return;
   // End Alternative 1
   return;
}

// PROGRAM csharp sort.
//    PART csharp kernel, quicksort.
//    PRELUDE csharp kernel.
//    ROOT quicksort.
// ENDPROG csharp sort.
// 
public static void Main(string[] args) {
   try {
      // Program Ludes
      // MOD_csharpkernel__PRELUDE
         csharpkernel_kernel_data__PRELUDE();
      // MOD_quicksort__ROOT
         quicksort_sort_sorter__ROOT();
   } catch (Exception ex) {
      Console.WriteLine($"Error: {ex.Message}");
      Console.WriteLine($"Stack Trace:\n{ex.StackTrace}");
   }
}
// End PROG csharp sort
   }
}
