<#
.SYNOPSIS
Generate a Windows and a Linux executable for the CDL2 lab and package for Linux.
.DESCRIPTION
   The script copies required files for distribution and generates 3 zip files:
   * CDL2-Windows.zip: Contains the Windows executables and all other files, but not the Linux executables.
   * CDL2-Linux.zip: Contains the Linux executables and all other files, but not the Windows executables.
   * CDL2.zip: Contains both the Windows and Linux executables and all other files.
   
   The script also copies itself to the Visual Studio project directory so it is pushed to GitHub.

   IMPORTANT:
   Do not edit this file in the Visual Studio project directory. Edit the file in the source directory and 
   then run the script to copy it to the project directory. The file in the project directory
   is read-only to prevent accidental edits.
   .PARAMETER NoBuild
   Skip building the executables. Default is to build the executables.
   .PARAMETER BuildOnly
   Only build the executables. Default is to build and deploy. Use OS to build only one or both.
   .PARAMETER OS
   The operating system(s) to generate the lab for. Default is both Windows and Linux.
   .PARAMETER NoDeploy
   Skip copying the build to the WSL and Windows test locations. Default is to copy the build.
   .PARAMETER KeepPDBs
   Keep the PDB files in the zip file. Default is to remove the PDB files prior to zipping.
   .PARAMETER UpdateDB
   Update the sample lab database in the WSL test location. Default is to NOT update the database if it exists.
   .PARAMETER Version
   Update the version number of the app using git tag vM.m unless the value is None (the default).
   Finds the latest tag that matches the pattern "vM.m" and increments the version number based on the specified
   type (Major or Minor). Default is to increment the Minor version number.
   When this parameter is not None, only versioning will be done.
   A value of Undo can be used to undo the last version update by deleting the latest tag.
   Use with caution, and only if you are sure that the latest tag is the one created by the last version update.
   The release artifacts will be built in the directory $releaseDir which should be outside the source directory.
   .PARAMETER Release
   Create a GitHub Release with the given name and attach the generated zip files to the release.
   The release will be created from the latest version tag. 
   Default is to not create a release. Use with '*' to name the release with just the version number (e.g. "v1.2").


   .EXAMPLE
   .\Publish-CDL2.ps1 -Version Minor
   This command increments the minor version number of the latest version tag and pushes the new tag to GitHub. 
   For example, if the latest tag is v1.2, it creates and pushes the new tag v1.3.
   .EXAMPLE
   .\Publish-CDL2.ps1 -Release "Alpha test"

   #>
   
   
   #cspell:ignore czvf labc
   
[CmdletBinding()]
param (
   [switch]$NoBuild,
   [switch]$BuildOnly,
   [ValidateSet('windows', 'linux')]
   [string[]]$OS = ('windows','linux'),
   [switch]$NoWSL,
   [switch]$KeepPDBs,
   [switch]$UpdateDB,
   [ValidateSet('None','Major','Minor','Undo')]
   [string]$Version = 'None',
   [string]$Release = ''
)
      
# The target root is the root directory in the zip file. It is used to determine the structure of the zip file.
[string]$targetRoot       = 'cdl2'
# The name of the sample lab database file. It is copied to the top level of the test target directories.
[string]$sampleDBName     = 'CDL2v1.lab.gz'
[string]$sampleDBLocation = "$targetRoot/Sample/$sampleDBName"

# Set the variables for the source and target locations. The source is the directory containing the files to be copied, and the
# target is the directory where the files will be copied to for zipping and deployment.
[string]$WSLDistro        = 'Ubuntu-24.04'
[string]$WSLDir           = "/home/peter/lab"
[string]$WSLDistroDir     = "\\wsl$\$WSLDistro"
[string]$WSLTarget        = Join-Path $WSLDistroDir $WSLDir
[string]$WindowsTarget    = 'C:\'

# The source directory is the location of the Visual Studio project. It is used to perform the builds.
[string]$releaseDir       = 'C:\Visual Studio Projects\CDL2.Release'
[string]$source           = 'C:\Visual Studio Projects\CDL2\CDL2v1'
[string]$VSProjectDir     = "$source\CDL2"

# The target directory is a temporary directory where the files are copied to for zipping.
# It is deleted and recreated each time the script is run.
[string]$targetDir        = "$Env:temp\CDL2Release"



# The operating system(s) to generate the lab for. The default is both Windows and Linux.
[bool]$Windows            = $OS -contains 'windows'
[bool]$Linux              = $OS -contains 'linux'


# Note: The file map is used to determine which files to copy for each part.
#       * The keys are the file names.
#       * The value may be the empty string (use $source\$targetRoot), or the directory of the file relative to $source.
#       * The executables get special treatment (generated in place, or temp directory to be copied when the zip is built)
[Hashtable]$FileMap = @{
   _README                        = '.'
   _LICENSE                       = '.'
   Docs = @{
      'CDL2 Lab.md'               = ''
      'CDL2-vWG.md'               = ''
      'hms.pdf'                   = ''
      'Implementation Notes.md'   = ''
      'md-styles.css'             = ''
   }
   Sample = @{
      'CDL2v1.lab.gz'             = ''
      'Quicksort.cdl2'            = ''
      'LabCommandsTest.labc'      = ''
   }
   C = @{
      'CDL2.h'                    = ''
      'CDL2Trace.h'               = ''
   }
   'bin\Windows' = @{
      'cc.cmd'                    = ''
      'cco.cmd'                   = ''
      'cdl2-lab.cmd'              = ''
      'cdl2c.cmd'                 = ''
   }
   'bin\Linux' = @{
      'cdl2-lab'                  = ''
      'cdl2c'                     = ''
   }   
}
# Copy the files in $map to the target given by $dst. The keys of $map are the file names.
# The value of $map is a hashtable with the same structure as $FileMap.
function Copy-Files([string]$dst,[Hashtable]$map) {
   [string]$dstDir = $dst -replace [regex]::escape("$targetDir\$targetRoot"),''
   foreach ($fn in $map.Keys | Sort-Object) {
      $src = $map[$fn]
      if ($src -is [string]) {
         [string]$srcPath = ''
         if ($src -eq '') {
            $srcPath = Join-Path $source "$targetRoot\$fn"
         } else {
            $srcPath = Join-Path $source "$(if ($src -eq '.') { '' } else { $src })\$fn"
         }
         $fileName = $srcPath -replace "$([Regex]::Escape($source))\\",''
         if ($fileName.StartsWith($targetRoot)) {
            $fileName = $fileName -replace "^$targetRoot","$targetRoot$dstDir"
         }
         Write-Host -ForegroundColor Yellow "   $filename"
         New-Item -ItemType Directory -Force -Path $dst -ErrorAction Ignore | Out-Null
         Copy-Item $srcPath $dst -Force
      } else {
         New-Item -ItemType Directory -Force -Path "$dst\$fn" -ErrorAction Ignore | Out-Null
         Copy-Files "$dst\$fn" $map[$fn]
      } 
   }  
}

function Invoke-Git([scriptblock]$gitCommand,[scriptblock]$errorHandler) {
   $res = & $gitCommand
   if ($LASTEXITCODE -ne 0) {
      [string]$operation = (($gitCommand.ToString().Trim() -split '\s+') | Select-Object -First 2) -join ' '
      Write-Error "$operation failed with exit code $LASTEXITCODE"
      exit $LASTEXITCODE
   }
   return $res
}

# If versioning is requested, do nothing else.
if ($Version -ne 'None') {
   Push-Location $source
   try {
      Write-Host -ForegroundColor Green "Updating version number ..."
      $latestTag = Invoke-Git { git describe --tags --match "v[0-9]*.[0-9]*" }

      if ($latestTag -match '^v(\d+)\.(\d+)') {
         if ($Version -eq 'Undo') {
            Write-Host -ForegroundColor Green "Deleting latest tag '$latestTag' to undo the last version update ..."
            Invoke-Git { git tag -d $latestTag }
            Invoke-Git { git push --delete origin $latestTag } { git tag $latestTag }
            Write-Host -ForegroundColor Green "Tag '$latestTag' deleted successfully."
         } else {
            $major = [int]$matches[1]
            $minor = [int]$matches[2]
            switch ($Version) {
               'Major' { $major++ ; $minor = 0 }
               'Minor' { $minor++ }
            }
            $newTag = "v$major.$minor"
            Write-Host -ForegroundColor Green "Latest tag: $($latestTag -replace '-.*$',''). New tag: $newTag"
            Invoke-Git { git tag $newTag }
            Invoke-Git { git push origin $newTag } { git tag -d $newTag }
         }
      } else {
         Write-Error "Latest tag '$latestTag' does not match the expected pattern 'vM.m'"
         exit 1
      }
      exit 0
   } finally {
      Pop-Location
   }
}


Remove-Item -Recurse -Force $targetDir -ErrorAction Ignore
New-Item -ItemType Directory -Force -Path "$targetDir\$targetRoot" -ErrorAction Ignore | Out-Null

if (-not $BuildOnly) {
   Write-Host -ForegroundColor Green "Copying files $source -> $($targetDir -replace [Regex]::Escape($Env:TMP),'$env:TMP') ..."
   Copy-Files "$targetDir\$targetRoot" $FileMap
}

# Build the executables in the source directory and copy them to the target directory for zipping.
Push-Location $source

New-Item -ItemType Directory -Force -Path "$releaseDir" -ErrorAction Ignore | Out-Null
Remove-Item -Force "$releaseDir\*.zip" -ErrorAction Ignore
if (-not $NoBuild -and $Windows) {
   Write-Host -ForegroundColor Green "`nPublishing CDL2 Lab for Windows..."
   dotnet publish CDL2v1.csproj        -c Release -r win-x64   --self-contained -p:PublishSingleFile=true -o:"$targetDir\$targetRoot\bin\Windows"
   if ($LASTEXITCODE -ne 0) {
      Write-Error "WINDOWS dotnet publish failed with exit code $LASTEXITCODE"
      exit $LASTEXITCODE
   }
   if (-not $KeepPDBs) { Remove-Item -Force "$targetDir\$targetRoot\bin\Windows\*.pdb" -ErrorAction Ignore }
}

if (-not $NoBuild -and $Linux) {
   Write-Host -ForegroundColor Green "`nPublishing CDL2 Lab for Linux..."
   dotnet publish CDL2v1-Linux.csproj -c Release -r linux-x64 --self-contained -p:PublishSingleFile=true -o:"$targetDir\Linux"
   if ($LASTEXITCODE -ne 0) {
      Write-Error "LINUX dotnet publish failed with exit code $LASTEXITCODE"
      exit $LASTEXITCODE
   }
   if (-not $KeepPDBs) { Remove-Item -Force "$targetDir\Linux\*.pdb" -ErrorAction Ignore }
}
Pop-Location

if ($BuildOnly) {
   Write-Host -ForegroundColor Green "`nBuildOnly specified. Skipping zipping and deployment."
   exit 0
}

Push-Location $targetDir

[int]$msgLen = 54
# Create the Windows only version zip file
Write-Host -ForegroundColor Green "`nCreating Windows only zip file (CDL2-Windows.zip) ... ".PadRight($msgLen) -NoNewline
# Compress-Archive -Path "$targetDir\$targetRoot" -DestinationPath "$source\$releaseDir\CDL2-Windows.zip" -Force -CompressionLevel Optimal
# zip -d "$source\$releaseDir\CDL2-Windows.zip" "cdl2/bin/Linux/*" *> $null
zip -r -9 "$releaseDir\CDL2-Windows.zip" $targetRoot -x "cdl2/bin/Linux/*" *> $null
Write-Host -ForegroundColor Cyan ("{0:N0} MiB" -f ((Get-ChildItem -Path "$releaseDir\CDL2-Windows.zip").Length/1024/1024))

# Copy the Linux directory to the target to create the combined version zip file.
Write-Host -ForegroundColor Green "Creating combined zip file (CDL2.zip) ... ".PadRight($msgLen) -NoNewline
Move-Item -Force "$targetDir\Linux\*" "$targetDir\$targetRoot\bin\Linux"
# Compress-Archive -Path "$targetDir\$targetRoot" -DestinationPath "$source\$releaseDir\CDL2.zip" -Force -CompressionLevel Optimal
zip -r -9 "$releaseDir\CDL2.zip" $targetRoot *> $null
Write-Host -ForegroundColor Cyan ("{0:N0} MiB" -f ((Get-ChildItem -Path "$releaseDir\CDL2.zip").Length/1024/1024))

# Remove the Windows directory to create the Linux only version zip file.
Write-Host -ForegroundColor Green "Creating Linux only zip file (CDL2-Linux.zip) ... ".PadRight($msgLen) -NoNewline
Remove-Item -Recurse -Force "$targetDir\$targetRoot\bin\Windows" -ErrorAction Ignore
# Compress-Archive -Path "$targetDir\$targetRoot" -DestinationPath "$source\$releaseDir\CDL2-Linux.zip" -Force -CompressionLevel Optimal
zip -r -9 "$releaseDir\CDL2-Linux.zip" $targetRoot *> $null
Write-Host -ForegroundColor Cyan ("{0:N0} MiB" -f ((Get-ChildItem -Path "$releaseDir\CDL2-Linux.zip").Length/1024/1024))

Pop-Location

if (-not $NoDeploy -and $Linux) {
   Write-Host -ForegroundColor Green "`nCopying Linux build to WSL test location ($WSLDir) and making it executable ..."
   Copy-Item -Force "$releaseDir\CDL2-Linux.zip" $WSLTarget
   WSL -d $WSLDistro unzip -o "$WSLDir/CDL2-Linux.zip" -d $WSLDir *> $null
   [string]$WSLBin = "$WSLDir/cdl2/bin/Linux"
   WSL -d $WSLDistro chmod +x "$WSLBin/cdl2-lab" "$WSLBin/cdl2c" "$WSLBin/CDL2v1-Linux"

   # Copy the sample lab db to the WSL test location if it doesn't already exist, or if the UpdateDB flag is set.
   if ($UpdateDB || -not (Test-Path "$WSLDistroDir$WSLDir/$sampleDBLocation")) {
      Write-Host -ForegroundColor Green "Updating sample lab database in WSL test location ($WSLDistroDir$WSLDir/$sampleDBName) ..."
      WSL -d $WSLDistro cp -f "$WSLDir/$sampleDBLocation" $WSLDir
   }
}

if (-not $NoDeploy -and $Windows) {
   Write-Host -ForegroundColor Green "`nCopying Windows build to test location ($WindowsTarget) ..."
   # New-Item -ItemType Directory -Force -Path "$WindowsTarget\$targetDir" -ErrorAction Ignore | Out-Null
   Expand-Archive -Path "$releaseDir\CDL2-Windows.zip" -DestinationPath $WindowsTarget -Force
   Copy-Item -Force "$releaseDir\CDL2-Windows.zip" $WindowsTarget\$targetRoot

   # Copy the sample lab db to the Windows test location if it doesn't already exist, or if the UpdateDB flag is set.
   if ($UpdateDB -or -not (Test-Path "$WindowsTarget$targetRoot\$sampleDBName")) {
      Write-Host -ForegroundColor Green "Updating sample lab database in Windows test location ($WindowsTarget$targetRoot\$sampleDBName) ..."
      Copy-Item "$WindowsTarget$sampleDB" "$WindowsTarget$targetRoot\" -Force -ErrorAction Ignore
   }
}

Write-Host -ForegroundColor Green "`nCopying publish script to Visual Studio project directory for GitHub ..."
Copy-Item -Force $PSCommandPath $VSProjectDir
Set-ItemProperty -Path "$VSProjectDir\$($PSCommandPath | Split-Path -Leaf)" -Name IsReadOnly -Value $true
