
<#
.SYNOPSIS
   PowerShell program generated by CDL2 v1.0.0 for PROGRAM sort at 2025-03-31 11:44:44.
#>
class BoundedArray {
   [int]$LowerBound
   [int]$UpperBound
   [Array]$Array
   

   BoundedArray([int]$lowerBound, [int]$upperBound) {
       if ($upperBound - $lowerBound -lt 0) {
           throw [System.ArgumentException]::new("Upper bound $($this.UpperBound) must be greater than or equal to lower bound $($this.LowerBound).")
       }
       $this.LowerBound = $lowerBound
       $this.UpperBound = $upperBound
       $this.Array = [Int64[]]::new($upperBound - $lowerBound + 1)
   }
   [void]CheckIndex([int]$index) {
      if ($index - $this.LowerBound -ge 0 -and $index - $this.LowerBound -le $this.UpperBound - $this.LowerBound) {
         return
      } else {
         throw [System.IndexOutOfRangeException]::new("Index: $index, LowerBound: $($this.LowerBound), UpperBound: $($this.UpperBound)")
       }
   }
   # These do NOT create a [] indexer
   [Int64]Item([int]$index) {
      $this.CheckIndex($index)
      return $this.Array[$index - $this.LowerBound]
   }

   [void]Item([int]$index, [Int64]$value) {
      $this.CheckIndex($index)
      $this.Array[$index - $this.LowerBound] = $value
   }
}

#===============================================================================

# Begin PROG sort
# PROGRAM sort.
#    PART quicksort.
#    PRELUDE quicksort.
#    ROOT quicksort.
#    POSTLUDE quicksort.
# ENDPROG sort.
# 
# Begin MOD quicksort
# Begin MOD quicksort LAY base
# Begin MOD quicksort LAY base SEC arithmetic

##### 1 Const #####

$C_quicksort_base_arithmetic_ten = 10

##### 1 Var #####

[Int64]$V_quicksort_base_arithmetic_var = 0

##### 17 Macros #####

# TEST choose+>a+>limit+c>+>inc =
#    "$L" c " = " a " + " inc 
#    "$L" a " -gt " limit.
function quicksort_base_arithmetic_choose([Int64]$A_a,[Int64]$A_limit,[ref]$A_c,[Int64]$A_inc) {
   [Int64]$_A_c = 0
      $__b = @(
         $_A_c = $A_a + $A_inc
         $A_a -gt $A_limit
      )[-1]
   if ($__b) {
      $A_c.Value = $_A_c
   }
   $__b
}
# # Return the test result as 0 or 1  #
# 
# FUNCTION choose func+>a+>limit+c>+>inc+res> =
#    c " = " a " + " inc 
#    "$L" res " = [int](" a " -gt " limit ")".
function quicksort_base_arithmetic_chooseFunc([Int64]$A_a,[Int64]$A_limit,[ref]$A_c,[Int64]$A_inc,[ref]$A_res) {
   $A_c.Value = $A_a + $A_inc
   $A_res.Value = [int]($A_a -gt $A_limit)
}
# FUNCTION incr+>a> =
#    a "++".
function quicksort_base_arithmetic_incr([ref]$A_a) {
   $A_a.Value++
}
# FUNCTION decr+>a> =
#    a "--".
function quicksort_base_arithmetic_decr([ref]$A_a) {
   $A_a.Value--
}
# FUNCTION incr with+>a>+>b =
#    a " += " b.
function quicksort_base_arithmetic_incrWith([ref]$A_a,[Int64]$A_b) {
   $A_a.Value += $A_b
}
# FUNCTION decr with+>a>+>b =
#    a " -= " b.
function quicksort_base_arithmetic_decrWith([ref]$A_a,[Int64]$A_b) {
   $A_a.Value -= $A_b
}
# FUNCTION add+>a+>b+c> =
#    c " = " a " + " b.
function quicksort_base_arithmetic_add([Int64]$A_a,[Int64]$A_b,[ref]$A_c) {
   $A_c.Value = $A_a + $A_b
}
# FUNCTION subtract+>a+>b+c> =
#    c " = " a " - " b.
function quicksort_base_arithmetic_subtract([Int64]$A_a,[Int64]$A_b,[ref]$A_c) {
   $A_c.Value = $A_a - $A_b
}
# FUNCTION multiply+>a+>b+c> =
#    c " = " a " * " b.
function quicksort_base_arithmetic_multiply([Int64]$A_a,[Int64]$A_b,[ref]$A_c) {
   $A_c.Value = $A_a * $A_b
}
# FUNCTION divide+>a+>b+c> =
#    c " = " a " / " b.
function quicksort_base_arithmetic_divide([Int64]$A_a,[Int64]$A_b,[ref]$A_c) {
   $A_c.Value = $A_a / $A_b
}
# FUNCTION remainder+>a+>b+c> =
#    c " = " a " - " a " / " b " * " b.
function quicksort_base_arithmetic_remainder([Int64]$A_a,[Int64]$A_b,[ref]$A_c) {
   $A_c.Value = $A_a - $A_a / $A_b * $A_b
}
# FUNCTION modulo+>a+>b+c> =
#    c " = " a " % " b.
function quicksort_base_arithmetic_modulo([Int64]$A_a,[Int64]$A_b,[ref]$A_c) {
   $A_c.Value = $A_a % $A_b
}
# FUNCTION halve+>a> =
#    a " /= 2".
function quicksort_base_arithmetic_halve([ref]$A_a) {
   $A_a.Value /= 2
}
# FUNCTION make+a>+>b =
#    a " = " b.
function quicksort_base_arithmetic_make([ref]$A_a,[Int64]$A_b) {
   $A_a.Value = $A_b
}
# TEST lt+>a+>b =
#    a " -lt " b.
function quicksort_base_arithmetic_lt([Int64]$A_a,[Int64]$A_b) {
   $A_a -lt $A_b
}
# TEST eq+>a+>b =
#    a " -eq " b.
function quicksort_base_arithmetic_eq([Int64]$A_a,[Int64]$A_b) {
   $A_a -eq $A_b
}
# FUNCTION random+>min+>max+r> =:
#    r " = Get-Random -Minimum " min " -Maximum (" max " + 1)".
function quicksort_base_arithmetic_random([Int64]$A_min,[Int64]$A_max,[ref]$A_r) {
   $A_r.Value = Get-Random -Minimum $A_min -Maximum ($A_max + 1)
}

##### 11 Procedures #####

# # >>> WARNING 105: Procedure has no effect tough is a ACTION
# ACTION action test :
#    +.
# #####################################################
# ### Procedures for testing the Semantic analyzer  ###
# ### Conditional compilation flag.                 ###
# #####################################################
# 
# # >>> ERROR   004: Procedure can not fail tough it is a TEST
# TEST wants less test :
#    +.
# # This proc cannot fail.            #
# 
# # >>> ERROR   001: Procedure has defect (has an effect tough it is a TEST)
# # >>> ERROR   004: Procedure can not fail tough it is a TEST
# TEST test+>a+>b>+c> :
#    wants less test, less+a+b, make+c+a;
#    eq+a+b, add+a+ten+c, action test;
#    add+b+ten+var, incr+b, make+c+b.
function quicksort_base_arithmetic_test([Int64]$A_a,[ref]$A_b,[ref]$A_c) {
   [Int64]$_A_b = $A_b.Value
   [Int64]$_A_c = 0
   do {
      # Simple body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_less $_A_a $_A_b
         if ($__b) { quicksort_base_arithmetic_make [ref]$_A_c $_A_a }
         if ($__b) { break }
      # Alternative 2
         [bool]$__b = quicksort_base_arithmetic_eq $_A_a $_A_b
         if ($__b) { quicksort_base_arithmetic_add $_A_a $C_quicksort_base_arithmetic_ten [ref]$_A_c }
         if ($__b) { quicksort_base_arithmetic_actionTest  }
         if ($__b) { break }
      # Alternative 3
         quicksort_base_arithmetic_add $_A_b $C_quicksort_base_arithmetic_ten [ref]$_V_quicksort_base_arithmetic_var
         quicksort_base_arithmetic_incr [ref]$_A_b
         quicksort_base_arithmetic_make [ref]$_A_c $_A_b
         $__b = $true; break
      break
   } while ($true)
   if ($__b) {
      $A_b.Value = $_A_b
      $A_c.Value = $_A_c
   }
   return $__b
}
# # This proc tries to use a fail.  #
# 
# # >>> ERROR   007: Procedure has FAIl operator (-) tough it is a FUNCTION
# # >>> ERROR   003: Procedure can fail tough it is a FUNCTION
# FUNCTION illegal fail operator :
#    eq+var+ten.
function quicksort_base_arithmetic_illegalFailOperator() {
      # Very simple body
      quicksort_base_arithmetic_eq $_V_quicksort_base_arithmetic_var $C_quicksort_base_arithmetic_ten
}
# TEST gt+>a+>b :
#    lt+b+a.
function quicksort_base_arithmetic_gt([Int64]$A_a,[Int64]$A_b) {
   do {
      # Simple body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_lt $_A_b $_A_a
         return $true
   } while ($true)
   return $__b
}
# TEST ne+>a+>b :
#    eq+a+b, -;
#    +.
function quicksort_base_arithmetic_ne([Int64]$A_a,[Int64]$A_b) {
   do {
      # Simple body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_eq $_A_a $_A_b
         if ($__b) { return $false }
         if ($__b) { return $true }
      # Alternative 2
         return $true
         return $true
   } while ($true)
   return $__b
}
# TEST ge+>a+>b :
#    eq+a+b;
#    gt+a+b.
function quicksort_base_arithmetic_ge([Int64]$A_a,[Int64]$A_b) {
   do {
      # Simple body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_eq $_A_a $_A_b
         if ($__b) { return $true }
      # Alternative 2
         [bool]$__b = quicksort_base_arithmetic_gt $_A_a $_A_b
         return $true
   } while ($true)
   return $__b
}
# TEST le+>a+>b :
#    eq+a+b;
#    lt+a+b.
function quicksort_base_arithmetic_le([Int64]$A_a,[Int64]$A_b) {
   do {
      # Simple body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_eq $_A_a $_A_b
         if ($__b) { return $true }
      # Alternative 2
         [bool]$__b = quicksort_base_arithmetic_lt $_A_a $_A_b
         return $true
   } while ($true)
   return $__b
}
# TEST greater+>a+>b :
#    gt+a+b.
function quicksort_base_arithmetic_greater([Int64]$A_a,[Int64]$A_b) {
   do {
      # Simple body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_gt $_A_a $_A_b
         return $true
   } while ($true)
   return $__b
}
# TEST less+>a+>b :
#    lt+a+b.
function quicksort_base_arithmetic_less([Int64]$A_a,[Int64]$A_b) {
   do {
      # Simple body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_lt $_A_a $_A_b
         return $true
   } while ($true)
   return $__b
}
# TEST less or equal+>a+>b :
#    le+a+b.
function quicksort_base_arithmetic_lessOrEqual([Int64]$A_a,[Int64]$A_b) {
   do {
      # Simple body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_le $_A_a $_A_b
         return $true
   } while ($true)
   return $__b
}
# End MOD quicksort LAY base SEC arithmetic
# Begin MOD quicksort LAY base SEC data

##### 4 Consts #####

$C_quicksort_base_data_lwb = 0
$C_quicksort_base_data_upb = 100
$C_quicksort_base_data_minRandom = 0
$C_quicksort_base_data_maxRandom = 200

##### 2 Vars #####

[Int64]$V_quicksort_base_data_unused = 0
[Int64]$V_quicksort_base_data_unused2 = 0

##### 1 LIST #####

$LL_quicksort_base_data_data = [BoundArray]::new($C_quicksort_base_data_lwb,$C_quicksort_base_data_upb)

##### 5 Macros #####

# TEST smaller element+>p+>q =
#    data ".Item(" p ") -lt " data ".Item(" q ")".
function quicksort_base_data_smallerElement([Int64]$A_p,[Int64]$A_q) {
   $LL_quicksort_base_data_data.Item($A_p) -lt $LL_quicksort_base_data_data.Item($A_q)
}
# FUNCTION get element+>i+v> =
#    v " = " data ".Item(" i ")".
function quicksort_base_data_getElement([Int64]$A_i,[ref]$A_v) {
   $A_v.Value = $LL_quicksort_base_data_data.Item($A_i)
}
# ACTION set element+>i+>v =
#    data ".Item(" i "," v ")".
function quicksort_base_data_setElement([Int64]$A_i,[Int64]$A_v) {
   $LL_quicksort_base_data_data.Item($A_i,$A_v)
}
# ACTION set element to+>p+>q =
#    data ".Item(" p "," data ".Item(" q "))".
function quicksort_base_data_setElementTo([Int64]$A_p,[Int64]$A_q) {
   $LL_quicksort_base_data_data.Item($A_p,$LL_quicksort_base_data_data.Item($A_q))
}
# ACTION dump list =
#    "Write-Host " data.
function quicksort_base_data_dumpList() {
   Write-Host $LL_quicksort_base_data_data
}

##### 3 Procedures #####

# ACTION swap element+>p+>q -t :
#    get element+p+t, set element to+p+q, set element+q+t.
function quicksort_base_data_swapElement([Int64]$A_p,[Int64]$A_q) {
   [Int64]$L_t = 0
      # Very simple body
      quicksort_base_data_getElement $_A_p [ref]$L_t
      quicksort_base_data_setElementTo $_A_p $_A_q
      quicksort_base_data_setElement $_A_q $L_t
}
# ACTION dump data*msg :
#    show msg no newline+msg, dump list.
function quicksort_base_data_dumpData([string]$A_msg) {
      # Very simple body
      quicksort_base_messages_showMsgNoNewline $_A_msg
      quicksort_base_data_dumpList 
}
# # Fill the array with random integers. #
# 
# ACTION initialize data -i -r :
#    make+i+lwb, 
#       (less or equal+i+upb, random+min random+max random+r, set element+i+r, incr+i, *;
#       +).
function quicksort_base_data_initializeData() {
   [Int64]$L_i = 0
   [Int64]$L_r = 0
      # Very simple body
      quicksort_base_arithmetic_make [ref]$L_i $C_quicksort_base_data_lwb
}

##### 1 Synthetic Procedure #####

# ACTION PRELUDE
function quicksort_base_data_PRELUDE() {
      # Very simple body
      quicksort_base_data_initializeData 
}
# End MOD quicksort LAY base SEC data
# Begin MOD quicksort LAY base SEC messages

##### 2 Macros #####

# ACTION show msg*string =
#    "Write-Host " string.
function quicksort_base_messages_showMsg([string]$A_string) {
   Write-Host $A_string
}
# ACTION show msg no newline*string =
#    "Write-Host -NoNewline" string.
function quicksort_base_messages_showMsgNoNewline([string]$A_string) {
   Write-Host -NoNewline$A_string
}
# End MOD quicksort LAY base SEC messages
# End MOD quicksort LAY base
# Begin MOD quicksort LAY sort
# Begin MOD quicksort LAY sort SEC sorter

##### 4 Procedures #####

# ACTION quicksort+>from+>to -p -q :
#    less+from+to, split+from+to+p+q, quicksort+from+q, quicksort+p+to;
#    +.
function quicksort_sort_sorter_quicksort([Int64]$A_from,[Int64]$A_to) {
   [Int64]$L_p = 0
   [Int64]$L_q = 0
   do {
      # Simple body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_less $_A_from $_A_to
         if ($__b) { quicksort_sort_sorter_split $_A_from $_A_to [ref]$L_p [ref]$L_q }
         if ($__b) { quicksort_sort_sorter_quicksort $_A_from $L_q }
         if ($__b) { quicksort_sort_sorter_quicksort $L_p $_A_to }
         return
      # Alternative 2
         return
         return
   } while ($true)
}
# # Split the array into two parts.                                   #
# # The first part contains elements less than or equal to the pivot. #
# 
# ACTION split+>i+>j+p>+q> -m :
#    make+p+i, make+q+j, add+i+j+m, halve+m, 
#       (again:
#       #############################################
#       ### Notes can be placed almost anywhere.  ###
#       #############################################
#       
#       NOTE.
#       move p up+j+p+m, move q down+i+q+m, 
#          (less+p+q, swap element+p+q, incr+p, decr+q, *again;
#           less+p+m, swap element+p+m, incr+p;
#           less+m+q, swap element+q+m, decr+q;
#          +)).
function quicksort_sort_sorter_split([Int64]$A_i,[Int64]$A_j,[ref]$A_p,[ref]$A_q) {
   [Int64]$L_m = 0
      # Very simple body
      quicksort_base_arithmetic_make [ref]$_A_p $_A_i
      quicksort_base_arithmetic_make [ref]$_A_q $_A_j
      quicksort_base_arithmetic_add $_A_i $_A_j [ref]$L_m
      quicksort_base_arithmetic_halve [ref]$L_m
}
# FUNCTION move p up+>j+>p>+>m :
#    less+p+j;
#    smaller element+m+p;
#    incr+p, *.
function quicksort_sort_sorter_movePUp([Int64]$A_j,[ref]$A_p,[Int64]$A_m) {
   do {
      # General body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_less $_A_p $_A_j
         return
      # Alternative 2
         [bool]$__b = quicksort_base_data_smallerElement $_A_m $_A_p
         return
      # Alternative 3
         quicksort_base_arithmetic_incr [ref]$_A_p
         if ($__b) { continue }
         return
   } while ($true)
}
# FUNCTION move q down+>i+>q>+>m :
#    less+q+i;
#    smaller element+q+m;
#    decr+q, *.
function quicksort_sort_sorter_moveQDown([Int64]$A_i,[ref]$A_q,[Int64]$A_m) {
   do {
      # General body
      # Alternative 1
         [bool]$__b = quicksort_base_arithmetic_less $_A_q $_A_i
         return
      # Alternative 2
         [bool]$__b = quicksort_base_data_smallerElement $_A_q $_A_m
         return
      # Alternative 3
         quicksort_base_arithmetic_decr [ref]$_A_q
         if ($__b) { continue }
         return
   } while ($true)
}

##### 3 Synthetic Procedures #####

# ACTION PRELUDE
function quicksort_sort_sorter_PRELUDE() {
      # Very simple body
      quicksort_base_data_dumpData "Data before sorting: "
}
# ACTION ROOT
function quicksort_sort_sorter_ROOT() {
      # Very simple body
      quicksort_base_messages_showMsg "Running quicksort ..."
      quicksort_sort_sorter_quicksort $C_quicksort_base_data_lwb $C_quicksort_base_data_upb
      quicksort_base_messages_showMsg "Done."
}
# ACTION POSTLUDE
function quicksort_sort_sorter_POSTLUDE() {
      # Very simple body
      quicksort_base_data_dumpData "Data after sorting: "
}
# End MOD quicksort LAY sort SEC sorter
# End MOD quicksort LAY sort
function MOD_quicksort_PRELUDE {
   quicksort_base_data_PRELUDE
   quicksort_sort_sorter_PRELUDE
}
function MOD_quicksort_ROOT {
   quicksort_sort_sorter_ROOT
}
function MOD_quicksort_POSTLUDE {
   quicksort_sort_sorter_POSTLUDE
}
# End MOD quicksort
# PROG_sort_PRELUDE
   MOD_quicksort_PRELUDE
# PROG_sort_ROOT
   MOD_quicksort_ROOT
# PROG_sort_POSTLUDE
   MOD_quicksort_POSTLUDE
# End PROG sort
