
//cspell:disable
/*
 * C# program generated by CDL2 v1.0.0 for PROGRAM sort at 2025-12-17 13:56:36.
 */

using System;

namespace CDL2Generated {
   public class BoundedArray<T> {
      public int LowerBound { get; }
      public int UpperBound { get; }
      private readonly T[] array;

      public BoundedArray(int lowerBound, int upperBound) {
         if (upperBound - lowerBound < 0)
            throw new ArgumentException($"Upper bound {upperBound} must be greater than or equal to lower bound {lowerBound}.");
         LowerBound = lowerBound;
         UpperBound = upperBound;
         array = new T[upperBound - lowerBound + 1];
      }

      private void CheckIndex(params int[] indices) {
         foreach (int index in indices) {
            if (index < LowerBound || index > UpperBound)
               throw new IndexOutOfRangeException($"Index: {index}, LowerBound: {LowerBound}, UpperBound: {UpperBound}");
         }
      }

      public T this[int index] {
         get { CheckIndex(index); return array[index - LowerBound]; }
         set { CheckIndex(index); array[index - LowerBound] = value; }
      }

      public void Swap(int i, int j) {
         CheckIndex(i, j);
         (array[i - LowerBound], array[j - LowerBound]) = (array[j - LowerBound], array[i - LowerBound]);
      }
   }

   public static class Program {
      //===============================================================================

// Begin PROG sort
public static void Main(string[] args) {
   try {
      
      // ##### 6 Consts #####
      
      private const Int64 powershellkernel_kernel_arithmetic_constx = 1;
      private const Int64 quicksort_base_parametrization_upb = 1000;
      private const Int64 quicksort_base_parametrization_lwb = 1;
      private const Int64 quicksort_base_parametrization_minrandom = 0;
      private const Int64 quicksort_base_parametrization_maxrandom = 200;
      private const Int64 quicksort_base_parametrization_maxsizeoflisttoshow = 100;
      
      // ##### 1 Var #####
      
      private static Int64 powershellkernel_kernel_data_datasize = 927436239  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
      
      // ##### 1 LIST #####
      
      private static BoundedArray<Int64> powershellkernel_kernel_data_data = new BoundedArray<Int64>(quicksort_base_parametrization_lwb, quicksort_base_parametrization_upb);
      
      // ##### 23 Macros #####
      
      
      // FUNCTION add+>a+>b+c> =
      //    c " = " a " + " b.
      // Macro inlined
      
      // FUNCTION subtract+>a+>b+c> =
      //    c " = " a " - " b.
      // Macro inlined
      
      // FUNCTION incr+>a> =
      //    a "++".
      // Macro inlined
      
      // FUNCTION make+a>+>b =
      //    a " = " b.
      // Macro inlined
      
      // TEST le+>a+>b =
      //    a " -le " b.
      // Macro inlined
      
      // FUNCTION random+>min+>max+r> =
      //    r " = Get-Random -Minimum " min " -Maximum (" max " + 1)".
      // Macro inlined
      
      // ACTION set element+>i+>v =
      //    data ".Item(" i "," v ")".
      // Macro inlined
      
      // ACTION show msg no newline*string =
      //    "Write-Host -NoNewline " string.
      // Macro inlined
      
      // ACTION dump list =
      //    "Write-Host " data ".Array".
      // Macro inlined
      
      // ACTION show msg*string =
      //    "Write-Host " string.
      // Macro inlined
      
      // FUNCTION touch out+v> =
      //    "".
      // Macro inlined
      
      // FUNCTION touch in+>v =
      //    "".
      // Macro inlined
      
      // TEST is data sorted macro -i -r =
      //    "$L " r " = 1" 
      //    "$L for (" i " = " lwb " ; " i " -lt " upb " ; " i "++) {" 
      //    "$L    if (" data ".Item(" i ") -gt " data ".Item(" i " + 1)) { " r " = 0; break }" 
      //    "$L }" 
      //    "$L [bool]" r.
      // Macro inlined
      
      // ACTION show number+>number =
      //    "Write-Host -NoNewline ('{0:N0}' -f " number ")".
      // Macro inlined
      
      // ACTION start timer =
      //    "$L $$script:start = Get-Date".
      // Macro inlined
      
      // TEST lt+>a+>b =
      //    a " -lt " b.
      // Macro inlined
      
      // FUNCTION halve+>a> =
      //    a " /= 2".
      // Macro inlined
      
      // TEST smaller element+>p+>q =
      //    data ".Item(" p ") -lt " data ".Item(" q ")".
      // Macro inlined
      
      // FUNCTION decr+>a> =
      //    a "--".
      // Macro inlined
      
      // ACTION swap element+>i+>j =
      //    data ".Swap(" i "," j ")".
      // Macro inlined
      
      // ACTION stop timer =
      //    "$L $$script:stop = Get-Date".
      // Macro inlined
      
      // ACTION show elapsed time =
      //    "$L Write-Host -ForegroundColor Blue ('Elapsed time: {0:N0} milliseconds' -f " 
      //    "[int](($$script:stop-$$script:start).TotalMicroseconds/1000))".
      // Macro inlined
      
      // ACTION sort data =
      //    "[Array]::Sort(" data ".Array)".
      // Macro inlined
      
      // ##### 12 Procedures #####
      
      
      // ACTION initialize data -i -r -z :
      //    add+const x+const x+z, subtract+upb+lwb+data size, incr+data size, make+i+lwb, 
      //       (le+i+upb, random+min random+max random+r, set element+i+r, incr+i, *;
      //        +).
      private static void powershellkernel_kernel_data_initializedata() {
         Int64 i = 341750233  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         Int64 r = 925641106  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         Int64 z = 1945802763  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         // Alternative 1
         // Inlining macro call -> add+const x+const x+z
         z = powershellkernel_kernel_arithmetic_constx + powershellkernel_kernel_arithmetic_constx
         // Inlining macro call -> subtract+upb+lwb+data size
         powershellkernel_kernel_data_datasize = quicksort_base_parametrization_upb - quicksort_base_parametrization_lwb
         // Inlining macro call -> incr+data size
         powershellkernel_kernel_data_datasize++
         // Inlining macro call -> make+i+lwb
         i = quicksort_base_parametrization_lwb
         // Group
         while (true) {
            // Alternative 1
            // Inlining macro call -> le+i+upb
            i -le quicksort_base_parametrization_upb
            // Inlining macro call -> random+min random+max random+r
            r = Get-Random -Minimum quicksort_base_parametrization_minrandom -Maximum (quicksort_base_parametrization_maxrandom + 1)
            // Inlining macro call -> set element+i+r
            powershellkernel_kernel_data_data.Item(i,r)
            // Inlining macro call -> incr+i
            i++
            continue;
            // End Alternative 1
            // Alternative 2
            return;
            // End Alternative 2
            break;
         }
         // End Group
         // End Alternative 1
         return;
      }
      
      // ACTION run demo -data size :
      //    initialize data, dump data+"Data before sorting: ", verify data sorted+"Random", 
      //       get data size+data size, show msg no newline+"Running quicksort on list of ", 
      //          show number+data size, show msg+" elements.", start timer, quicksort+lwb+upb, stop timer, 
      //             show elapsed time, dump data+"Data after sorting: ", verify data sorted+"Quicksort-ed", 
      //             initialize data, show msg+"Running .NET sort on list.", start timer, sort data, 
      //             stop timer, show elapsed time.
      // Procedure inlined
      
      // ACTION dump data*msg :
      //    show msg no newline+msg, 
      //       (le+data size+max size of list to show, dump list;
      //        show msg+"too many elements to show.").
      private static void powershellkernel_kernel_data_dumpdata(string msg) {
         // Alternative 1
         // Inlining macro call -> show msg no newline+msg
         Write-Host -NoNewline msg
         // Group
            // Alternative 1
            // Inlining macro call -> le+data size+max size of list to show
            powershellkernel_kernel_data_datasize -le quicksort_base_parametrization_maxsizeoflisttoshow
            // Inlining macro call -> dump list
            Write-Host powershellkernel_kernel_data_data.Array
            return;
            // End Alternative 1
            // Alternative 2
            // Inlining macro call -> show msg+"too many elements to show."
            Write-Host "too many elements to show."
            return;
            // End Alternative 2
         // End Group
         // End Alternative 1
         return;
      }
      
      // ACTION verify data sorted*which :
      //    is data sorted, show msg no newline+which, show msg+" data is sorted.";
      //    show msg no newline+which, show msg+" data is not sorted.".
      private static void quicksort_sort_sorter_verifydatasorted(string which) {
         // Alternative 1
         if (quicksort_sort_sorter_isdatasorted()) {
            // Inlining macro call -> show msg no newline+which
            Write-Host -NoNewline which
            // Inlining macro call -> show msg+" data is sorted."
            Write-Host " data is sorted."
            return;
         }
         // End Alternative 1
         // Alternative 2
         // Inlining macro call -> show msg no newline+which
         Write-Host -NoNewline which
         // Inlining macro call -> show msg+" data is not sorted."
         Write-Host " data is not sorted."
         return;
         // End Alternative 2
         return;
      }
      
      // PREDICATE is data sorted -where :
      //    use macro for sortedness test, touch out+where, touch in+where, is data sorted macro;
      //    is data unsorted procedure+where, show msg no newline+"Unsorted at ", show number+where, 
      //       show msg+".", -;
      //    +.
      private static bool quicksort_sort_sorter_isdatasorted() {
         Int64 where = 1512230614  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         // Alternative 1
         // Inlining macro call -> touch out+where
         // Inlining macro call -> touch in+where
         // Inlining macro call -> is data sorted macro
          r = 1
          for (i = quicksort_base_parametrization_lwb ; i -lt quicksort_base_parametrization_upb ; i++) {
             if (powershellkernel_kernel_data_data.Item(i) -gt powershellkernel_kernel_data_data.Item(i + 1)) { r = 0; break }
          }
          [bool]r
         return true;
         // End Alternative 1
         // Alternative 2
         // Alternative suppressed by previous conditional compilation ON
         // End Alternative 2
         // Alternative 3
         // Alternative suppressed by previous conditional compilation ON
         // End Alternative 3
         return false;
      }
      
      // TEST use macro for sortedness test :
      //    +.
      
      // FUNCTION get data size+size> :
      //    make+size+data size.
      // Procedure inlined
      
      // ACTION quicksort+>from+>to -p -q :
      //    less+from+to, split+from+to+p+q, quicksort+from+q, quicksort+p+to;
      //    +.
      private static void quicksort_sort_sorter_quicksort(Int64 from, Int64 to) {
         Int64 p = 371413860  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         Int64 q = 1989559293  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         // Alternative 1
         // Inlining procedure call -> less+from+to
         // Inlining macro call -> lt+a+b
         from -lt to
         quicksort_sort_sorter_split(from, to, ref p, ref q);
         quicksort_sort_sorter_quicksort(from, q);
         quicksort_sort_sorter_quicksort(p, to);
         return;
         // End Alternative 1
         // Alternative 2
         return;
         // End Alternative 2
         return;
      }
      
      // TEST less+>a+>b :
      //    lt+a+b.
      // Procedure inlined
      
      // ACTION split+>i+>j+p>+q> -m :
      //    make+p+i, make+q+j, add+i+j+m, halve+m, 
      //       (again:move p up+j+p+m, move q down+i+q+m, 
      //          (less+p+q, swap element+p+q, incr+p, decr+q, *again;
      //           less+p+m, swap element+p+m,  incr+p;
      //           less+m+q, swap element+q+m,  decr+q;
      //           +)).
      private static void quicksort_sort_sorter_split(Int64 i, Int64 j, ref Int64 p, ref Int64 q) {
         Int64 m = 985766302  /* Random value to catch uninitialized VARs, LOCALs, and output AFFIXes */;
         // Alternative 1
         // Inlining macro call -> make+p+i
         p = i
         // Inlining macro call -> make+q+j
         q = j
         // Inlining macro call -> add+i+j+m
         m = i + j
         // Inlining macro call -> halve+m
         m /= 2
         // Group
         while (true) {
            // Alternative 1
            quicksort_sort_sorter_movepup(j, ref p, m);
            quicksort_sort_sorter_moveqdown(i, ref q, m);
            // Group
               // Alternative 1
               // Inlining procedure call -> less+p+q
               // Inlining macro call -> lt+a+b
               p -lt q
               // Inlining macro call -> swap element+p+q
               powershellkernel_kernel_data_data.Swap(p,q)
               // Inlining macro call -> incr+p
               p++
               // Inlining macro call -> decr+q
               q--
               continue;
               // End Alternative 1
               // Alternative 2
               // Inlining procedure call -> less+p+m
               // Inlining macro call -> lt+a+b
               p -lt m
               // Inlining macro call -> swap element+p+m
               powershellkernel_kernel_data_data.Swap(p,m)
               // Inlining macro call -> incr+p
               p++
               return;
               // End Alternative 2
               // Alternative 3
               // Inlining procedure call -> less+m+q
               // Inlining macro call -> lt+a+b
               m -lt q
               // Inlining macro call -> swap element+q+m
               powershellkernel_kernel_data_data.Swap(q,m)
               // Inlining macro call -> decr+q
               q--
               return;
               // End Alternative 3
               // Alternative 4
               return;
               // End Alternative 4
            // End Group
            // End Alternative 1
            break;
         }
         // End Group
         // End Alternative 1
         return;
      }
      
      // FUNCTION move p up+>j+>p>+>m :
      //    less+j+p;
      //    smaller element+m+p;
      //    incr+p, *.
      private static void quicksort_sort_sorter_movepup(Int64 j, ref Int64 p, Int64 m) {
         while (true) {
            // Alternative 1
            // Inlining procedure call -> less+j+p
            // Inlining macro call -> lt+a+b
            j -lt p
            return;
            // End Alternative 1
            // Alternative 2
            // Inlining macro call -> smaller element+m+p
            powershellkernel_kernel_data_data.Item(m) -lt powershellkernel_kernel_data_data.Item(p)
            return;
            // End Alternative 2
            // Alternative 3
            // Inlining macro call -> incr+p
            p++
            continue;
            // End Alternative 3
            return;
         }
         return;
      }
      
      // FUNCTION move q down+>i+>q>+>m :
      //    less+q+i;
      //    smaller element+q+m;
      //    decr+q, *.
      private static void quicksort_sort_sorter_moveqdown(Int64 i, ref Int64 q, Int64 m) {
         while (true) {
            // Alternative 1
            // Inlining procedure call -> less+q+i
            // Inlining macro call -> lt+a+b
            q -lt i
            return;
            // End Alternative 1
            // Alternative 2
            // Inlining macro call -> smaller element+q+m
            powershellkernel_kernel_data_data.Item(q) -lt powershellkernel_kernel_data_data.Item(m)
            return;
            // End Alternative 2
            // Alternative 3
            // Inlining macro call -> decr+q
            q--
            continue;
            // End Alternative 3
            return;
         }
         return;
      }
      
      // ##### 2 Synthetic Procedures #####
      
      // MOD powershell kernel LAY kernel SEC data ACTION PRELUDE
      private static void powershellkernel_kernel_data__PRELUDE() {
         // Alternative 1
         powershellkernel_kernel_data_initializedata();
         return;
         // End Alternative 1
         return;
      }
      // MOD quicksort LAY sort SEC sorter ACTION ROOT
      private static void quicksort_sort_sorter__ROOT() {
         // Alternative 1
         // Inlining procedure call -> run demo
         powershellkernel_kernel_data_initializedata();
         powershellkernel_kernel_data_dumpdata("Data before sorting: ");
         quicksort_sort_sorter_verifydatasorted("Random");
         // Inlining procedure call -> get data size+data size
         // Inlining macro call -> make+size+data size
         datasize = powershellkernel_kernel_data_datasize
         // Inlining macro call -> show msg no newline+"Running quicksort on list of "
         Write-Host -NoNewline "Running quicksort on list of "
         // Inlining macro call -> show number+data size
         Write-Host -NoNewline ('{0:N0}' -f datasize)
         // Inlining macro call -> show msg+" elements."
         Write-Host " elements."
         // Inlining macro call -> start timer
          $script:start = Get-Date
         quicksort_sort_sorter_quicksort(quicksort_base_parametrization_lwb, quicksort_base_parametrization_upb);
         // Inlining macro call -> stop timer
          $script:stop = Get-Date
         // Inlining macro call -> show elapsed time
          Write-Host -ForegroundColor Blue ('Elapsed time: {0:N0} milliseconds' -f [int](($script:stop-$script:start).TotalMicroseconds/1000))
         powershellkernel_kernel_data_dumpdata("Data after sorting: ");
         quicksort_sort_sorter_verifydatasorted("Quicksort-ed");
         powershellkernel_kernel_data_initializedata();
         // Inlining macro call -> show msg+"Running .NET sort on list."
         Write-Host "Running .NET sort on list."
         // Inlining macro call -> start timer
          $script:start = Get-Date
         // Inlining macro call -> sort data
         [Array]::Sort(powershellkernel_kernel_data_data.Array)
         // Inlining macro call -> stop timer
          $script:stop = Get-Date
         // Inlining macro call -> show elapsed time
          Write-Host -ForegroundColor Blue ('Elapsed time: {0:N0} milliseconds' -f [int](($script:stop-$script:start).TotalMicroseconds/1000))
         return;
         // End Alternative 1
         return;
      }
      
      // PROGRAM sort.
      //    PART powershell kernel, quicksort.
      //    PRELUDE powershell kernel.
      //    ROOT quicksort.
      // ENDPROG sort.
      // 
      // Program Ludes
      // MOD_powershellkernel__PRELUDE
         powershellkernel_kernel_data__PRELUDE();
      // MOD_quicksort__ROOT
         quicksort_sort_sorter__ROOT();
   } catch (Exception ex) {
      Console.WriteLine($"Error: {ex.Message}");
      Console.WriteLine($"Stack Trace:\n{ex.StackTrace}");
   }
}
// End PROG sort
   }
}
