<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <UseWindowsForms>false</UseWindowsForms>
    <ApplicationIcon>CDL-V1.ico</ApplicationIcon>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="CDL-V1.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CDL2\**\*.cs" />
    <None Include="CDL2\**\*.cs" />
  </ItemGroup>

  <!-- Package reference for ALL target frameworks  
  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>
 -->

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <Reference Include="PresentationCore, Version=10.0.0.0,Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
    <Reference Include="PresentationFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
    <Reference Include="WindowsBase, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
  </ItemGroup>

  <ItemGroup>
    <None Include="CDL2v1-Linux.csproj" />
  </ItemGroup>

  <!-- Suppress WPF warnings when building for non-Windows platforms -->
  <PropertyGroup Condition="'$(RuntimeIdentifier)' != '' AND !$(RuntimeIdentifier.StartsWith('win'))">
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <!-- Compute version M.m.b number from last git tag of vM.m or vM.mR and b the number of commits since the tag -->
  <Target Name="ComputeVersion" BeforeTargets="GenerateAssemblyInfo">

    <Exec Command="git describe --tags --abbrev=0" ConsoleToMSBuild="true" StandardOutputImportance="Low">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitTagRawWithR" />
    </Exec>

    <!-- Use the latest tag for the commit count -->
    <Exec Command="git rev-list $(GitTagRawWithR)..HEAD --count" ConsoleToMSBuild="true" StandardOutputImportance="Low">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitCountRaw" />
    </Exec>

    <PropertyGroup>
      <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
      <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
      <!-- IMPORTANT: force trimming safely -->
      <GitTagRaw>$([System.String]::Copy($(GitTagRawWithR)).Trim('R').Trim())</GitTagRaw>
      <GitTag>$(GitTagRaw)</GitTag>
      <GitCount>$([System.String]::Copy($(GitCountRaw)).Trim())</GitCount>
      
      
      
      <BaseVersion Condition="'$(GitTag)' != ''">$([System.String]::Copy($(GitTag)).TrimStart('v'))</BaseVersion>

      <BaseVersion Condition="'$(GitTag)' == ''">1.0</BaseVersion>

      <Version>$(BaseVersion).$(GitCount)</Version>

      <InformationalVersion>$(GitTagRawWithR).$(GitCount)</InformationalVersion>
      <FileVersion>$(Version)</FileVersion>
      <AssemblyVersion Condition="'$(Version)' != ''">$(Version).0</AssemblyVersion>
      <AssemblyVersion Condition="'$(Version)' == ''">1.0.0.0</AssemblyVersion>
      
      <VersionPadded>$([System.String]::Format("| Generated Version {0,-13} |", $(Version)))</VersionPadded>
    </PropertyGroup>
    <!-- <Message Text="GitTagRaWithR: $(GitTagRawWithR) | GitTagRaw: $(GitTagRaw) | GitTag: $(GitTag) | GitCount: $(GitCount) | InformationalVersion: $(InformationalVersion)" Importance="High" /> -->
    <Message Text="+---------------------------------+" Importance="High" />
    <Message Text="$(VersionPadded)" Importance="High" />
    <Message Text="+---------------------------------+" Importance="High" />
  </Target>

  <PropertyGroup>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Deterministic>true</Deterministic>
    <SourceRevisionId></SourceRevisionId>
    <RepositoryUrl></RepositoryUrl>
  </PropertyGroup>

  <Target Name="OverrideInformationalVersion" AfterTargets="GenerateAssemblyInfo">
    <ItemGroup>
      <AssemblyAttribute Include="System.Reflection.AssemblyInformationalVersionAttribute">
        <_Parameter1>$(InformationalVersion)</_Parameter1>
      </AssemblyAttribute>
    </ItemGroup>
  </Target>

  <!-- Must be placed here (after the above Target) otherwise it does not have the required effect. -->
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

</Project>
