<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
    <ApplicationIcon>CDL-V1.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
  </PropertyGroup>

  <!-- Exclude this project from DebugGenerated and ReleaseGenerated configurations -->
  <PropertyGroup Condition="'$(Configuration)'=='DebugGenerated' Or '$(Configuration)'=='ReleaseGenerated'">
    <ExcludeFromBuild>true</ExcludeFromBuild>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="CDL-V1.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="CDL2\**\*.cs" />
    <None Include="CDL2\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="CDL2Generated.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
     <Reference Include="PresentationCore, Version=10.0.0.0,Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
     <Reference Include="PresentationFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
     <Reference Include="WindowsBase, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />
  </ItemGroup>

</Project>
