<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>LINUX</DefineConstants>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="bin\**;obj\**;CDL2\**\*.cs;ToastWindow.cs;CommandWindow.xaml.cs;EmitterCommandWindow.cs;EmitterWindow.cs;CommandPromptWindow.cs" />

    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>
  <!-- Compute version M.m.b number from last git tag of vM.m and b the number of commits since the tag -->
  <Target Name="ComputeVersion" BeforeTargets="GenerateAssemblyInfo">
    <Exec Command="git describe --tags --abbrev=0" ConsoleToMSBuild="true" StandardOutputImportance="Low">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitTagRaw" />
    </Exec>

    <!-- Use the latest tag for the commit count -->
    <Exec Command="git rev-list $(GitTagRaw)..HEAD --count" ConsoleToMSBuild="true" StandardOutputImportance="Low">
      <Output TaskParameter="ConsoleOutput" PropertyName="GitCountRaw" />
    </Exec>

    <PropertyGroup>
      <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
      <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
      <!-- IMPORTANT: force trimming safely -->
      <GitTag>$([System.String]::Copy($(GitTagRaw)).Trim())</GitTag>
      <GitCount>$([System.String]::Copy($(GitCountRaw)).Trim())</GitCount>

      <BaseVersion Condition="'$(GitTag)' != ''">$([System.String]::Copy($(GitTag)).TrimStart('v'))</BaseVersion>

      <BaseVersion Condition="'$(GitTag)' == ''">1.0</BaseVersion>

      <Version>$(BaseVersion).$(GitCount)</Version>

      <InformationalVersion>$(Version)</InformationalVersion>
      <FileVersion>$(Version)</FileVersion>
      <NormalizedVersion>$([System.String]::Copy($(Version)).Replace("R.","."))</NormalizedVersion>
      <AssemblyVersion Condition="'$(Version)' != ''">$(NormalizedVersion).0</AssemblyVersion>
      <AssemblyVersion Condition="'$(Version)' == ''">1.0.0.0</AssemblyVersion>
      
      <VersionPadded>$([System.String]::Format("| Generated Version {0,-13} |", $(Version)))</VersionPadded>
    </PropertyGroup>

    <Message Text="+---------------------------------+" Importance="High" />
    <Message Text="$(VersionPadded)" Importance="High" />
    <Message Text="+---------------------------------+" Importance="High" />
  </Target>

  <PropertyGroup>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Deterministic>true</Deterministic>
    <SourceRevisionId></SourceRevisionId>
    <RepositoryUrl></RepositoryUrl>
  </PropertyGroup>

  <Target Name="OverrideInformationalVersion" AfterTargets="GenerateAssemblyInfo">
    <ItemGroup>
      <AssemblyAttribute Include="System.Reflection.AssemblyInformationalVersionAttribute">
        <_Parameter1>$(Version)</_Parameter1>
      </AssemblyAttribute>
    </ItemGroup>
  </Target>

  <!-- Must be placed here (after the above Target) otherwise it does not have the required effect. -->
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
</Project>