// <auto-gen>
//=======================================================================
// <copyright file="CodeGeneratorC.cs" company="Peter Köves">
//     Copyright (c) Peter Köves, 2025. All rights reserved.
//     Licensed under the MIT License. See _LICENSE file in the project root
//     for full license information.
// </copyright>
//=======================================================================
// <author>Peter Köves</author>
// <creation-date>2025-12-18</creation-date>
// 
// <summary>
//   C code generator for CDL2.
//   Generates K&R C compatible code.
// </summary>
//=======================================================================
// </auto-gen>

namespace CDL2v1 {
   internal partial class CodeGeneratorC : TargetCodeGenerator, ICodeGenerator {
      public string FileExtension => "c";
      public string StatementSeparator => ";";
      public bool TargetRequiresMacroSpliting => true;

      private readonly EmitterString sourceEmitter = new(prefix: "// ");
      public Emitter SourceEmitter => sourceEmitter;

      private readonly string DataType;

      public CodeGeneratorC(string dataType) : base() => DataType = dataType;

      public void GenerateProgramStart(Program program,Emitter emitter,bool isSeparate = false) {
         this.emitter = emitter;
         emitter.Emitnl("/*cspell:disable*/");
         emitter.Emitnl("/*");
         emitter.Emitnl($" * C program generated by CDL2 v1.0.0 for PROGRAM {program.Id.Name} at {DateTime.Now:yyyy-MM-dd HH:mm:ss}.");
         emitter.Emitnl(" */");
         emitter.Emitnl();
         emitter.Emitnl("#include <stdio.h>");
         emitter.Emitnl("#include <stdlib.h>");
         emitter.Emitnl("#include <time.h>");
         emitter.Emitnl();
         emitter.Emitnl($"#define BOOL {DataType}");
         emitter.Emitnl($"#define VALUE {DataType}");
         GenerateStandardMacros();
         emitter.Emitnl();
         base.GenerateComment("===============================================================================");
         emitter.Emitnl();
         EmitUnitStartComment(program);
         emitter.Emitnl();
      }

      private void GenerateStandardMacros() {
         emitter.Emitnl("/* CDL2 Standard Macros for Lists */");
         emitter.Emitnl("#define CDL2_DECLARE_LIST(name, lwb, upb) \\");
         emitter.Emitnl("    VALUE name##_array[(upb) - (lwb) + 1]; \\");
         emitter.Emitnl("    VALUE name##_lwb = (lwb); \\");
         emitter.Emitnl("    VALUE name##_upb = (upb)");
         emitter.Emitnl();
         emitter.Emitnl("#define CDL2_LIST_GET(name, i) \\");
         emitter.Emitnl("    ((i) < name##_lwb || (i) > name##_upb ? \\");
         emitter.Emitnl("        (fprintf(stderr, \"Index out of bounds: %ld not in [%ld..%ld]\\\\n\", (VALUE)(i), name##_lwb, name##_upb), exit(1), 0) : \\");
         emitter.Emitnl("        name##_array[(i) - name##_lwb])");
         emitter.Emitnl();
         emitter.Emitnl("#define CDL2_LIST_SET(name, i, value) \\");
         emitter.Emitnl("    do { \\");
         emitter.Emitnl("        if ((i) < name##_lwb || (i) > name##_upb) { \\");
         emitter.Emitnl("            fprintf(stderr, \"Index out of bounds: %ld not in [%ld..%ld]\\\\n\", (VALUE)(i), name##_lwb, name##_upb); \\");
         emitter.Emitnl("            exit(1); \\");
         emitter.Emitnl("        } \\");
         emitter.Emitnl("        name##_array[(i) - name##_lwb] = (value); \\");
         emitter.Emitnl("    } while(0)");
         emitter.Emitnl();
         emitter.Emitnl("#define CDL2_LIST_SWAP(name, i, j) \\");
         emitter.Emitnl("    do { \\");
         emitter.Emitnl("        VALUE temp; \\");
         emitter.Emitnl("        if ((i) < name##_lwb || (i) > name##_upb || (j) < name##_lwb || (j) > name##_upb) { \\");
         emitter.Emitnl("            fprintf(stderr, \"Index out of bounds in swap\\\\n\"); \\");
         emitter.Emitnl("            exit(1); \\");
         emitter.Emitnl("        } \\");
         emitter.Emitnl("        temp = name##_array[(i) - name##_lwb]; \\");
         emitter.Emitnl("        name##_array[(i) - name##_lwb] = name##_array[(j) - name##_lwb]; \\");
         emitter.Emitnl("        name##_array[(j) - name##_lwb] = temp; \\");
         emitter.Emitnl("    } while(0)");
         emitter.Emitnl();
      }

      public void GenerateProgramLudesStart() {
         emitter.Emitnl();
         emitter.Emitnl("int main(int argc, char *argv[])");
         emitter.Emitnl("{");
         IncrementIndent();
         emitter.Emitnl("/* Program Ludes */");
      }

      public void GenerateProgramLudesEnd() { }

      public void GenerateProgramEnd(Program program,bool isSeparate = false) {
         DecrementIndent();
         emitter.Emitnl("return 0;");
         emitter.Emitnl("}");
         emitter.Emitnl();
         EmitUnitEndComment(program);
      }

      void ICodeGenerator.GenerateSourceComment() => emitter.NlEmit("\n",sourceEmitter.Content);

      public new void GenerateComment(string comment) {
         foreach (string line in comment.Split('\n')) emitter.Emitnl("/* ",line," */");
      }

      public void GenerateComment(PrettyPrinter pp) => emitter.Emit(pp.Emitter.Content);

      public void GenerateNewline() => emitter.Emitnl();

      public void GenerateObjectSectionStart<T>(IEnumerable<NamedElement> items,string typeName) where T : NamedElement {
         int n = items.Count();
         if (n > 0) emitter.NlEmitnl($"\n/* ##### {n} {typeName}{(n != 1 ? "s" : "")} ##### */\n");
      }

      public void GenerateObjectSectionEnd<T>(IEnumerable<NamedElement> items,string typeName) where T : NamedElement { }

      public void GenerateConstantStart(Const constant) => emitter.Emit("#define ",CName(constant)," ");
      public void GenerateConstElementInt(long value) => emitter.Emit(value);
      public void GenerateConstElementFloat(double value) => emitter.Emit(value);
      public void GenerateConstElementString(string value) => emitter.Emit("\"",value,"\"");
      public void GenerateConstElementConst(Const c) => emitter.Emit(CArgName(c));

      public void GenerateConstantEnd(Const constant) => emitter.Emitnl();

      public void GenerateVar(Var v) => emitter.Emitnl("VALUE ",CName(v)," = ",RandomInitialValue,";");

      public void GenerateList(LIST list,Const lwb,Const upb) => emitter.Emitnl("CDL2_DECLARE_LIST(",CName(list),", ",CName(lwb),", ",CName(upb),");");


      /// <summary>
      /// Generate the assigment of a value to the given actual argument. Used to implement builtin functions.
      /// </summary>
      /// <param name="arg"></param>
      /// <param name="value"></param>
      void ICodeGenerator.GenerateValueAssignment(IActualArg arg,object value) => emitter.Emitnl(CArgName(arg)," = ",GenerateValueExpression(value),";");

      public void GenerateMacroStart(Macro macro) => emitter.NlEmit("\n",sourceEmitter.Content);
      public void GenerateMacroEnd(Macro macro) {
         DecrementIndent();
         emitter.NlEmitnl("}");
      }

      public void GenerateMacroBodyStart(Macro macro) {
         if (macro.NeedsFinalization) IncrementIndent();
      }

      public void GenerateMacroBodyEnd(Macro macro) {
         if (macro.NeedsFinalization) DecrementIndent();
      }

      public void GenerateReturnExpressionStart(Macro macro) {
         if (macro.CanFail) emitter.Emit("return ");
      }

      public void GenerateReturnExpressionEnd(Macro macro) {
         if (macro.CanFail) emitter.Emitnl(";");
      }

      public void GenerateMacroInlineStart(Macro macro) { }
      public void GenerateMacroInlineEnd(Macro macro) { }

      public void GenerateMacroElementInt(long value) => emitter.Emit(value);
      public void GenerateMacroElementFloat(double value) => emitter.Emit(value);

      public void GenerateMacroElementString(string value,bool firstElement,bool quoted) {
         if (quoted) {
            emitter.Emit("\"",value.Replace("\"","\\\""),"\"");
         } else {
            string[] lines = value.Split('\n');
            foreach (string line in lines.Skip(firstElement ? 1 : 0).SkipLast(1)) emitter.Emitnl(line);
            emitter.Emit(lines.Last());
         }
      }

      public void GenerateMacroElementConst(Const c) => emitter.Emit(CName(c));
      public void GenerateMacroElementVar(Var v,bool canFail,bool inlined = false) => emitter.Emit(CName(v,canFail && !inlined ? "_" : ""));
      public void GenerateMacroElementList(LIST l) => emitter.Emit(CName(l));
      public void GenerateMacroElementLocal(Local local,Affix calledAffix) => emitter.Emit(CName(local));
      public void GenerateMacroElementAffix(Affix affix,bool canFail) => emitter.Emit((affix.IsOutput ? "*" : "") + CName(affix,canFail && affix.IsOutput ? "_" : ""));

      #region Procedures
      private ModifiableStack ifDepth = [];

      public void GenerateProcedureStart(Procedure proc) {
         emitter.Emitnl();
         ifDepth.Push(0);
      }

      public void GenerateProcedureEnd(Procedure proc) {
         ifDepth.Pop();
         emitter.Emitnl(proc.CanFail ? proc.NeedsFinalization ? "return 1;" : "return 0;" : "return;");
         emitter.NlEmitnl("}");
      }

      public void GenerateProcedureBodyStart(Procedure proc,ProcedureBodyType bodyType) {
         if (proc.NeedsWrapper) {
            emitter.Emitnl("while (1) {");
            IncrementIndent();
         }
         IncrementIndent();
      }

      public void GenerateProcedureBodyEnd(Procedure proc,ProcedureBodyType bodyType) {
         DecrementIndent();
         if (proc.NeedsWrapper) {
            emitter.Emitnl(proc.CanFail ? "return 0;" : "return;");
            DecrementIndent();
            emitter.Emitnl("}");
         }
      }

      public void GenerateAlternativeStart(Procedure proc,Group group,int alternativeNumber) => GenerateComment($"Alternative {alternativeNumber}");

      public void GenerateAlternativeEnd(Procedure proc,Group group,int alternativeNumber,Alternative alternative,bool removed) {
         if (alternative.lastCall.type != LCT.Group && alternative.lastCall.type != LCT.Repeat && !removed && !alternative.Terminates)
            emitter.Emitnl(proc.CanFail ? (proc.NeedsWrapper ? "break;" : "return 1;") : "return;");
         while (ifDepth > 0) {
            DecrementIndent();
            ifDepth--;
            emitter.Emitnl("}");
         }
         GenerateComment($"End Alternative {alternativeNumber}");
      }

      public void GenerateGroupStart(Procedure proc,Group group) {
         GenerateComment("Group");
         if (group.HasAnonymousRepeat || !group.IsSynthetic) emitter.Emitnl("while (1) {");
         ifDepth.Push(0);
         IncrementIndent();
      }

      public void GenerateGroupEnd(Procedure proc,Group group) {
         bool hasDo = group.HasAnonymousRepeat || !group.IsSynthetic;
         if (hasDo) emitter.Emitnl("break;");
         DecrementIndent();
         ifDepth.Pop();
         if (hasDo) emitter.Emitnl("}");
         GenerateComment("End Group");
      }

      public void GenerateCallStart(Algorithm called,Procedure calling,bool canFail,bool onlyCallInAlternative,bool lastAlternative) {
         if (called.CanFail) {
            emitter.Emit("if (!",CName(called),"(");
            ifDepth++;
            IncrementIndent();
         } else {
            emitter.Emit(CName(called),"(");
         }
      }

      public void GenerateCallEnd(Algorithm called,Procedure calling,bool canFail,bool onlyCallInAlternative,bool lastAlternative) {
         if (called.CanFail) {
            emitter.Emit(")) {");
         } else {
            emitter.Emit(";");
         }
         Newline();
      }

      public void GenerateFail(Procedure proc,Group group) => emitter.Emitnl("return 0;");
      public void GenerateSucceed(Procedure proc,Group group) => emitter.Emitnl("return 1;");
      public void GenerateAbort(Procedure proc,Group group) => emitter.Emitnl("exit(1);");
      public void GenerateRepeat(Procedure proc,Group group,ID label,bool canFail) => emitter.Emitnl("continue;");

      public void GenerateActualArgSeparator() => emitter.Emit(", ");
      public void GenerateCallArgString(string value) => emitter.Emit("\"",value.Replace("\"","\\\""),"\"");
      public void GenerateCallArgReferenceConst(Affix affix,Const c) => emitter.Emit(CName(c));

      public void GenerateCallArgReferenceVar(Affix affix,Var v,bool needFinalization) {
         if (affix.IsOutput) emitter.Emit("&",CName(v,needFinalization ? "_" : ""));
         else emitter.Emit(CName(v,needFinalization ? "_" : ""));
      }

      public void GenerateCallArgReferenceAffix(Affix calledAffix,Affix callingAffix,bool needFinalization) {
         if (calledAffix.IsOutput) {
            if (callingAffix.IsOutput) emitter.Emit("&",CName(callingAffix,needFinalization ? "_" : ""));
            else emitter.Emit(CName(callingAffix));
         } else {
            emitter.Emit(callingAffix.IsOutput ? "*" : "",CName(callingAffix,needFinalization && callingAffix.IsOutput ? "_" : ""));
         }
      }

      public void GenerateCallArgReferenceLocal(Affix affix,Local local) => emitter.Emit(affix.IsOutput ? "&" : "",CName(local));
      #endregion Procedures

      public void GenerateAlgorithmHeaderStart(Algorithm alg) => emitter.Emit($"{(alg.CanFail ? "BOOL" : "void")} {CName(alg)}(");
      public void GenerateAlgorithmHeaderEnd(Algorithm alg) {
         emitter.Emitnl(") {");
         IncrementIndent();
      }

      public void GenerateAffix(Affix affix,AffixDir dir,bool canFail) {
         switch (dir) {
            case AD.input:
               emitter.Emit("VALUE ",CName(affix));
               break;
            case AD.NONE:
               emitter.Emit("char *",CName(affix));
               break;
            default:
               emitter.Emit("VALUE *",CName(affix));
               break;
         }
      }

      public void GenerateAffixSeparator() => emitter.Emit(", ");

      public void GenerateLocal(Local local) => emitter.Emitnl("VALUE ",CName(local)," = ",RandomInitialValue,";");

      public void GenerateAffixAndVariableInitializationStart(Algorithm alg) {
         if (alg.NeedsFinalization) GenerateComment("Initialization");
      }

      public void GenerateAffixAndVariableInitializationEnd(Algorithm alg) {
         if (alg.NeedsFinalization) GenerateComment("End Initialization");
      }

      public void GenerateAffixAndVariableInitializer(Algorithm alg,IFailureProtected item,bool isVar) {
         switch (item is Affix affix ? affix.affixDir : AD.transput) {
            case AD.NONE:
            case AD.input:
               break;
            case AD.output:
               if (isVar) {
                  emitter.Emitnl("VALUE ",CName((Var)item,"_")," = ",RandomInitialValue,";");
               } else {
                  emitter.Emitnl("VALUE ",CName((Affix)item,"_")," = ",RandomInitialValue,";");
               }
               break;
            case AD.transput:
               if (isVar) {
                  emitter.Emitnl("VALUE ",CName((Var)item,"_")," = ",CName((Var)item),";");
               } else {
                  emitter.Emitnl("VALUE ",CName((Affix)item,"_")," = *",CName((Affix)item),";");
               }
               break;
         }
      }

      public void GenerateAffixAndVariableFinalizationStart(Algorithm algorithm) {
         if (algorithm.NeedsFinalization) GenerateComment("Finalization");
      }

      public void GenerateAffixAndVariableFinalizationEnd(Algorithm algorithm) {
         if (algorithm.NeedsFinalization) GenerateComment("End Finalization");
      }

      public void GenerateAffixAndVariableFinalizer(Algorithm alg,IFailureProtected item,bool isVar) {
         switch (item is Affix affix ? affix.affixDir : AD.transput) {
            case AD.NONE:
            case AD.input:
               break;
            default:
               if (isVar) {
                  emitter.Emitnl(CName((Var)item)," = ",CName((Var)item,"_"),";");
               } else {
                  emitter.Emitnl("*",CName((Affix)item)," = ",CName((Affix)item,"_"),";");
               }
               break;
         }
      }

      public void GenerateProgramPart(Program program,ID moduleId,bool isSeparate) { }

      public void GenerateProgramLudeStart(RW ludeType,Program program) => emitter.Emitnl("/* Program ",ludeType," */");

      public void GenerateProgramLudeEnd(RW ludeType,Program program) { }

      public void GenerateProgramLude(RW ludeType,Program program,Module module) =>
            emitter.Emitnl($"{module.TypeShortName}_{module.Id.Name.AsIdentifier(camelCase: false)}__{ludeType}();");

      public void GenerateModuleStart(Module module,bool isSeparate,string? headerFileName = null) {
         emitter.Emitnl();
         EmitUnitStartComment(module);
      }

      public void GenerateModuleEnd(Module module,bool isSeparate) => EmitUnitEndComment(module);

      public void GenerateImpExStart(Module module) { }
      public void GenerateImpExEnd(Module module) { }
      public void GenerateExport(IProvidable exportedItem) { }
      public void GenerateImport(IProvidable importedItem) { }

      public void GenerateModuleLudeStart(RW ludeType,Module module,bool wrapped) {
         emitter.Emitnl("/* MOD ",module.Id.Name," ",ludeType," */");
         if (wrapped) {
            string returnType = ludeType == RW.ROOT || ludeType == RW.PRELUDE || ludeType == RW.POSTLUDE ? "void" : "VALUE";
            string moduleName = $"{module.TypeShortName}_{module.Id.Name.AsIdentifier(camelCase: false)}__{ludeType}";

            emitter.Emitnl(returnType," ",moduleName,"__",ludeType,"()");
            emitter.Emitnl("{");
            IncrementIndent();
         }
      }

      public void GenerateModuleLudeEnd(RW ludeType,Module module,bool wrapped) {
         if (wrapped) {
            DecrementIndent();
            emitter.Emitnl("}");
         }
      }

      public void GenerateModuleLude(RW ludeType,Module module,Section section) =>
         emitter.Emitnl(section.SyntheticProcedures.Where(p => p.Id.CanonicalName == ludeType.ToString()).FirstOrDefault()?.FQN(camelCase: false,literalObjectName: true)!,"();");

      public void GenerateLayerStart(Layer layer) { }
      public void GenerateLayerEnd(Layer layer) { }
      public void GenerateSectionStart(Section section) { }
      public void GenerateSectionEnd(Section section) { }
      public void GenerateSectionLudeStart(RW ludeType,Section section) { }
      public void GenerateSectionLudeEnd(RW ludeType,Section section) { }
      public void GenerateSectionLude(RW ludeType,Section section,Procedure proc) => emitter.Emitnl(CName(proc),"();");


      #region Helpers
      private static string CName(CDL2Object obj,string suffix = "") => obj.FQN(camelCase: false,literalObjectName: obj.IsSynthetic) + suffix;
      private static string CName(Affix affix,string suffix = "") => "a_" + affix.Id.Name.AsIdentifier(camelCase: false) + suffix;
      private static string CName(Local local,string suffix = "") => "l_" + local.Id.Name.AsIdentifier(camelCase: false) + suffix;
      private static string CName(Var var,string suffix = "") => "v_" + var.FQN(camelCase: false,literalObjectName: var.IsSynthetic) + suffix;
      private static string CArgName(IActualArg arg,string suffix = "") => arg switch {
         Affix a => CName(a,suffix),
         Local l => CName(l,suffix),
         Var v => CName(v,suffix),
         _ => throw new NotImplementedException($"CName not implemented for type {arg.GetType()}."),
      };
      /// <summary>
      /// Generate the constant that will be assinged to an Affix, Local or Var.
      /// </summary>
      /// <param name="value"></param>
      /// <returns></returns>
      /// <exception cref="NotImplementedException"></exception>
      private string GenerateValueExpression(object value) => value switch {
         long l => l.ToString(),
         int i => i.ToString(),
         double d => d.ToString(System.Globalization.CultureInfo.InvariantCulture),
         string s => $"\"{s.Replace("\"","`\"")}\"",
         _ => throw new NotImplementedException($"Value expression generation not implemented for type {value.GetType()}."),
      };


      #endregion Helpers
   }
}