// <auto-gen>
//=======================================================================
// <copyright file="CodeGeneratorCSharp.cs" company="Peter Köves">
//     Copyright (c) Peter Köves, 2025. All rights reserved.
//     Licensed under the MIT License. See _LICENSE file in the project root
//     for full license information.
// </copyright>
//=======================================================================
// <author>Peter Köves</author>
// <creation-date>2025-03-15</creation-date>
// 
// <summary>
//   Target code generator to generate C# code from CDL2 programs.
// </summary>
// <attribution>
//   This file is part of the clean room reimplementation of the
//      CDL2 Compiler
//      CDL2 Laboratory
//      CDL2 Target Code Generators
//
//    Based on original work on CDL and CDL2 led by C. H. A. Koster
//    and the CDL2 team at the Universities of Berlin, Germany and
//    Nijmegen, The Netherlands.
//
//    The CDL2 Laboratory was the work of Epsilon GmbH, Berlin.
//    H. M. Stahl, H. Feuerhahn, JP. Dehotay, B. Böhringer
//    (and others I don't remember ... sorry).
//
//    This project is not affiliated with the original CDL2 project.
// </attribution>
//=======================================================================
// </auto-gen>

using System.Diagnostics;
using System.IO;
using System.Text.RegularExpressions;

namespace CDL2v1 {
   internal partial class CodeGeneratorCSharp : TargetCodeGenerator, ICodeGenerator {

      #region Instance and Static Variables, Constructors
      private readonly string DataType;

      private CodeGenerator? cg = null;
      public void SetCodeGenerator(CodeGenerator cg) => this.cg = cg;


      /// <summary>
      /// Constructor for the C# code generator.
      /// </summary>
      /// <param name="dataType">This can be used to change the word size, e.g., to int.</param>
      /// <remarks>No explicit references to this class. The instance is constructed via reflection.</remarks>
      public CodeGeneratorCSharp(string dataType) : base() => DataType = dataType;

      private static readonly string ProgramHeaderPattern = @"
//cspell:disable
/*
 * C# program generated by CDL2 v<%0%> for PROGRAM <%1%> at <%2:yyyy-MM-dd HH:mm:ss%>.
 * Settings: <%3%>
 */

using System;

#pragma warning disable CS0162 // Unreachable code detected
#pragma warning disable CS0219 // Variable is assigned but its value is never used

namespace CDL2Generated {
   public class BoundedArray<T> {
      public Int64 LowerBound { get; }
      public Int64 UpperBound { get; }
      public readonly T[] array;

      public BoundedArray(Int64 lowerBound, Int64 upperBound) {
         if (upperBound - lowerBound < 0)
            throw new ArgumentException($""Upper bound {upperBound} must be greater than or equal to lower bound {lowerBound}."");
         LowerBound = lowerBound;
         UpperBound = upperBound;
         array = new T[upperBound - lowerBound + 1];
      }

      private void CheckIndex(params Int64[] indices) {
         foreach (int index in indices) {
            if (index < LowerBound || index > UpperBound)
               throw new IndexOutOfRangeException($""Index: {index}, LowerBound: {LowerBound}, UpperBound: {UpperBound}"");
         }
      }

      public T this[Int64 index] {
         get { CheckIndex(index); return array[index - LowerBound]; }
         set { CheckIndex(index); array[index - LowerBound] = value; }
      }

      public void Swap(Int64 i, Int64 j) {
         CheckIndex(i, j);
         (array[i - LowerBound], array[j - LowerBound]) = (array[j - LowerBound], array[i - LowerBound]);
      }
   }

   public static class Program {
      //===============================================================================
";
      private static readonly string ProgramHeader;

      static CodeGeneratorCSharp() => ProgramHeader = ProgramHeaderPattern.Replace("{","{{").Replace("}","}}").Replace("<%","{").Replace("%>","}");

      protected new void EmitUnitStartComment(Container unit) => emitter.Emitnl($"// Begin {unit.ContainerName}");
      protected new void EmitUnitEndComment(Container unit) => emitter.Emitnl($"// End {unit.ContainerName}");
      #endregion Instance and Static Variables, Constructors

      #region Programs, Modules, Layers, Sections
      void ICodeGenerator.GenerateProgramStart(Program program,Emitter emitter,string settings,bool isSeparate) {
         this.emitter = emitter;
         emitter.Emitnl(string.Format(ProgramHeader,CDL2.Version,program.Id.Name,DateTime.Now,settings));
         if (program != null) {
            EmitUnitStartComment(program);
         }
      }

      void ICodeGenerator.GenerateProgramPart(Program program,ID mod,bool isSeparate) { }

      void ICodeGenerator.GenerateProgramEnd(Program program,bool isSeparate) {
         if (program != null) {
            EmitUnitEndComment(program);
            emitter.Emitnl("   }");
            emitter.Emitnl("}");
         }
      }

      void ICodeGenerator.GenerateModuleStart(Module module,bool isSeparate,string? target) {
         if (isSeparate) {
            emitter.Target = Path.Combine(Path.GetDirectoryName(emitter.Target) ?? "",module.Id.CanonicalName + ((ICodeGenerator)this).FileExtension);
         }
         EmitUnitStartComment(module);
      }

      void ICodeGenerator.GenerateModuleEnd(Module module,bool isSeparate) => EmitUnitEndComment(module);
      void ICodeGenerator.GenerateLayerStart(Layer layer) => EmitUnitStartComment(layer);
      void ICodeGenerator.GenerateLayerEnd(Layer layer) => EmitUnitEndComment(layer);
      void ICodeGenerator.GenerateSectionStart(Section section) => EmitUnitStartComment(section);
      void ICodeGenerator.GenerateSectionEnd(Section section) => EmitUnitEndComment(section);
      #endregion Programs, Modules, Layers, Sections

      #region Prelude, Postlude, Root
      void ICodeGenerator.GenerateProgramLudesStart() {
         emitter.Emitnl("// Command line arguments support");
         emitter.Emitnl("private static string[] args = [];");
         emitter.Emitnl();
         emitter.Emitnl("public static void Main(string[] args) {");
         IncrementIndent();
         emitter.Emitnl("Program.args = args;");
         emitter.Emitnl("try {");
         IncrementIndent();
      }
      void ICodeGenerator.GenerateProgramLudesEnd() {
         DecrementIndent();
         emitter.Emitnl("} catch (Exception ex) {");
         IncrementIndent();
         emitter.Emitnl("Console.WriteLine($\"Error: {ex.Message}\");");
         emitter.Emitnl("Console.WriteLine($\"Stack Trace:\\n{ex.StackTrace}\");");
         DecrementIndent();
         emitter.Emitnl("}");
         DecrementIndent();
         emitter.Emitnl("}");
      }

      void ICodeGenerator.GenerateProgramLudeStart(RW ludetype,Program program) {
         GenerateComment($"{program.TypeShortName}_{program.Id.Name.AsIdentifier(camelCase: false)}__{ludetype}");
         IncrementIndent();
      }

      void ICodeGenerator.GenerateProgramLude(RW ludeType,Program program,Module module)
         => emitter.Emitnl($"{module.TypeShortName}_{module.Id.Name.AsIdentifier(camelCase: false)}__{ludeType}();");

      void ICodeGenerator.GenerateProgramLudeEnd(RW ludeType,Program program) => DecrementIndent();

      void ICodeGenerator.GenerateModuleLudeStart(RW ludetype,Module module,bool wrapped) {
         string moduleName = $"{module.TypeShortName}_{module.Id.Name.AsIdentifier(camelCase: false)}__{ludetype}";
         if (wrapped) {
            emitter.Emitnl($"private static void {moduleName}() {{");
         } else {
            emitter.Emitnl($"// {moduleName}");
         }
         IncrementIndent();
      }

      void ICodeGenerator.GenerateModuleLude(RW ludeType,Module module,Section section) {
         Procedure lude = section.LudeProcs[ludeType]?.ToNamedElement<Procedure>()!;
         GenerateComment(lude.FQDN());
         emitter.Emitnl(TargetName(lude),"();");
      }

      void ICodeGenerator.GenerateModuleLudeEnd(RW ludeType,Module module,bool wrapped) {
         DecrementIndent();
         if (wrapped) emitter.Emitnl("}");
      }

      void ICodeGenerator.GenerateSectionLudeStart(RW ludeType,Section section) => throw new NotImplementedException();
      void ICodeGenerator.GenerateSectionLudeEnd(RW ludeType,Section section) => throw new NotImplementedException();
      #endregion Prelude, Postlude, Root

      #region Import/Export
      void ICodeGenerator.GenerateImpExStart(Module module) { }
      void ICodeGenerator.GenerateImpExEnd(Module module) { }
      void ICodeGenerator.GenerateExport(IProvidable export) { }
      void ICodeGenerator.GenerateImport(IProvidable import) { }
      #endregion Import/Export

      #region Object Sections
      void ICodeGenerator.GenerateObjectSectionStart<T>(IEnumerable<NamedElement> items,string typeName) {
         int n = items.Count();
         if (n > 0) emitter.NlEmitnl($"\n// ##### {n} {typeName}{(n != 1 ? "s" : "")} #####\n");
      }

      void ICodeGenerator.GenerateObjectSectionEnd<T>(IEnumerable<NamedElement> items,string typeName) { }
      #endregion Object Sections

      #region Data Declarations
      void ICodeGenerator.GenerateConstantStart(Const c) => emitter.Emit("private const ",DataType," ",TargetName(c)," = ");
      void ICodeGenerator.GenerateConstElementString(string value) => ((ICodeGenerator)this).GenerateMacroElementString(value,false,false);
      void ICodeGenerator.GenerateConstElementFloat(double value) => ((ICodeGenerator)this).GenerateMacroElementFloat(value);
      void ICodeGenerator.GenerateConstElementInt(long value) => ((ICodeGenerator)this).GenerateMacroElementInt(value);
      void ICodeGenerator.GenerateConstElementConst(Const constant) => emitter.Emit(TargetName(constant));
      void ICodeGenerator.GenerateConstantEnd(Const c) => emitter.Emitnl(";");
      void ICodeGenerator.GenerateVar(Var var) => emitter.Emitnl("private static ",DataType," ",TargetName(var)," = ",InitialValue,";");
      void ICodeGenerator.GenerateList(LIST var,Const lwb,Const upb) => emitter.Emitnl("private static BoundedArray<",DataType,"> ",TargetName(var)," = new BoundedArray<",DataType,">(",TargetName(lwb),", ",TargetName(upb),");");

      void ICodeGenerator.GenerateListInitializers(IEnumerable<LIST> list) {}
      #endregion Data Declarations

      #region Algorithm Common
      void ICodeGenerator.GenerateAlgorithmHeaderStart(Algorithm proc) => emitter.Emit($"private static {(proc.CanFail ? "bool" : "void")} {TargetName(proc)}(");
      void ICodeGenerator.GenerateAlgorithmHeaderEnd(Algorithm proc) {
         emitter.Emitnl(") {");
         IncrementIndent();
      }

      void ICodeGenerator.GenerateAffixSeparator() => emitter.Emit(", ");

      void ICodeGenerator.GenerateLocal(Local local) => emitter.Emitnl(DataType," ",TargetName(local)," = ",InitialValue,";");


      void ICodeGenerator.GenerateAffix(Affix affix,AD dir,bool algorithmCanFail) {
         switch (dir) {
            case AD.input:
               emitter.Emit(DataType," ",TargetName(affix));
               break;
            case AD.NONE:
               emitter.Emit("string ",TargetName(affix));
               break;
            default:
               emitter.Emit("ref ",DataType," ",TargetName(affix));
               break;
         }
      }

      void ICodeGenerator.GenerateAffixAndVariableInitializer(Algorithm alg,IFailureProtected var,bool isVar) {
         switch (var is Affix affix ? affix.affixDir : AD.transput) {
            case AD.NONE:
            case AD.input:
               break;
            case AD.output:
               if (isVar) {
                  emitter.Emitnl(DataType," ",TargetName((Var)var,"_")," = ",InitialValue,";");
               } else {
                  emitter.Emitnl(DataType," ",TargetName((Affix)var,"_")," = ",InitialValue,";");
               }
               break;
            case AD.transput:
               if (isVar) {
                  emitter.Emitnl(DataType," ",TargetName((Var)var,"_")," = ",TargetName((Var)var),";");
               } else {
                  emitter.Emitnl(DataType," ",TargetName((Affix)var,"_")," = ",TargetName((Affix)var),";");
               }
               break;
         }
      }

      /// <summary>
      /// Generate the assigment of a value to the given actual argument. Used to implement builtin functions.
      /// </summary>
      /// <param name="arg"></param>
      /// <param name="value"></param>

      void ICodeGenerator.GenerateAffixAndVariableInitializationStart(Algorithm alg) { if (alg.NeedsFinalization) GenerateComment("Initialization"); }
      void ICodeGenerator.GenerateAffixAndVariableInitializationEnd(Algorithm alg) { if (alg.NeedsFinalization) GenerateComment("End Initialization"); }
      void ICodeGenerator.GenerateAffixAndVariableFinalizationStart(Algorithm algorithm) { if (algorithm.NeedsFinalization) GenerateComment("Finalization"); }
      void ICodeGenerator.GenerateAffixAndVariableFinalizationEnd(Algorithm algorithm) {
         if (algorithm.NeedsFinalization) {
            GenerateComment("End Finalization");
            emitter.Emitnl("return true;");
         }
      }

      void ICodeGenerator.GenerateAffixAndVariableFinalizer(Algorithm alg,IFailureProtected var,bool isVar) {
         switch (var is Affix affix ? affix.affixDir : AD.transput) {
            case AD.NONE:
            case AD.input:
               break;
            default:
               if (isVar) {
                  emitter.Emitnl(TargetName((Var)var)," = ",TargetName((Var)var,"_"),";");
               } else {
                  emitter.Emitnl(TargetName((Affix)var)," = ",TargetName((Affix)var,"_"),";");
               }
               break;
         }
      }
      #endregion Algorithm Common

      #region Macros
      void ICodeGenerator.GenerateMacroStart(Macro macro) { }
      void ICodeGenerator.GenerateMacroEnd(Macro macro) {
         DecrementIndent();
         emitter.NlEmitnl("}");
      }

      void ICodeGenerator.GenerateMacroElementInt(long value) => emitter.Emit(value);
      void ICodeGenerator.GenerateMacroElementFloat(double value) => emitter.Emit(value);
      void ICodeGenerator.GenerateMacroElementString(string value,bool firstElement,bool quoted) {
         if (quoted) {
            emitter.Emit("\"",value.Replace("\"","\\\""),"\"");
         } else {
            string[] lines = value.Split('\n');
            foreach (string line in lines.Skip(firstElement ? 1 : 0).SkipLast(1)) emitter.Emitnl(line);
            emitter.Emit(lines.Last());
         }
      }

      void ICodeGenerator.GenerateMacroElementVar(Var var,bool macroCanFail,bool inlined) => emitter.Emit(TargetName(var,macroCanFail ? "_" : ""));
      void ICodeGenerator.GenerateMacroElementList(LIST list) => emitter.Emit(TargetName(list));
      void ICodeGenerator.GenerateMacroElementConst(Const constant) => emitter.Emit(TargetName(constant));
      void ICodeGenerator.GenerateMacroElementAffix(Affix affix,bool macroCanFail) => emitter.Emit(TargetName(affix,macroCanFail && affix.IsOutput ? "_" : ""));
      void ICodeGenerator.GenerateMacroElementLocal(Local loc,Affix aff) => emitter.Emit(TargetName(loc));

      void ICodeGenerator.GenerateMacroBodyStart(Macro macro,bool inlining) { }

      void ICodeGenerator.GenerateMacroBodyEnd(Macro macro,bool inlining,bool lastCallInAlternative) { }

      void ICodeGenerator.GenerateReturnExpressionStart(Macro macro) {
         if (macro.CanFail) {
            if (macro.NeedsFinalization) {
               emitter.Emitnl("while (true) {");
               IncrementIndent();
               emitter.Emit("if (");
            } else {
               emitter.Emit("return ");
            }
         }
      }

      void ICodeGenerator.GenerateReturnExpressionEnd(Macro macro,int alternativeNumber) {
         if (macro.CanFail) {
            if (macro.NeedsFinalization) {
               emitter.Emitnl(") break;");
               emitter.Emitnl("return false;");
               DecrementIndent();
               emitter.Emitnl("}");
            } else {
               emitter.Emit(";");
            }
         }
      }

      void ICodeGenerator.GenerateMacroInlineStart(Macro macro) => ConditionalWrapperStart(macro);
      void ICodeGenerator.GenerateMacroInlineEnd(Macro macro,Procedure containingProc,int alternativeNumber,bool finalAlterantive) {
         ConditionalWrapperEnd(macro);
         Newline(optional: true);
      }
      #endregion Macros

      #region Procedures
      private ModifiableStack ifDepth = [];

      void ICodeGenerator.GenerateProcedureStart(Procedure code) => ifDepth.Push(0);

      void ICodeGenerator.GenerateProcedureEnd(Procedure proc) {
         ifDepth.Pop();
         emitter.Emitnl(proc.CanFail ? proc.NeedsFinalization ? "return true;" : "return false;" : "return;");
         DecrementIndent();
         emitter.NlEmitnl("}");
      }

      void ICodeGenerator.GenerateProcedureBodyStart(Procedure proc,PBT bodyType) {
         if (proc.NeedsWrapper) {
            emitter.Emitnl("while (true) {");
            IncrementIndent();
         }
      }

      void ICodeGenerator.GenerateProcedureBodyEnd(Procedure proc,PBT bodyType) {
         if (proc.NeedsWrapper) {
            emitter.Emitnl(proc.CanFail ? "return false;" : "return;");
            DecrementIndent();
            emitter.Emitnl("}");
         }
      }

      #region Alternatives
      void ICodeGenerator.GenerateAlternativeStart(Procedure proc,Group group,int alternativeNumber,bool suppressLabel) 
         => GenerateComment($"Alternative {alternativeNumber}");

      void ICodeGenerator.GenerateAlternativeEnd(Procedure proc,Group group,int i,Alternative alternative,bool removed,bool supressLabel) {
         if (proc.IsLude) return;
         if (alternative.LastCall.type != LCT.Group && alternative.LastCall.type != LCT.Repeat && !removed && !alternative.Terminates)
            emitter.Emitnl(proc.CanFail ? (proc.NeedsWrapper ? "break;" : "return true;") : "return;");
         while (ifDepth > 0) {
            DecrementIndent();
            ifDepth--;
            emitter.Emitnl("}");
         }
         GenerateComment($"End Alternative {i}");
      }
      #endregion Alternatives

      #region Groups
      void ICodeGenerator.GenerateGroupStart(Procedure proc,Group group) {
         GenerateComment($"Group {TargetName(group)}");
         if (proc.IsLude) return;
         if (!group.Id.IsAnonymousGroup && proc.ReferrencesGroup(group.Id,includeAnon:false)) emitter.Emitnl(TargetName(group) + ":");
         if (group.HasAnonymousRepeat || !group.IsSynthetic) emitter.Emitnl("while (true) {");
         ifDepth.Push(0);
         IncrementIndent();
      }
      void ICodeGenerator.GenerateGroupEnd(Procedure proc,Group group) {
         if (!proc.IsLude) {
            bool hasWhile = group.HasAnonymousRepeat || !group.IsSynthetic;
            if (hasWhile) emitter.Emitnl("break;");
            DecrementIndent();
            ifDepth.Pop();
            if (hasWhile) emitter.Emitnl("}");
         }
         GenerateComment($"End Group {TargetName(group)}");
      }
      #endregion Groups

      #region Calls
      void ICodeGenerator.GenerateActualArgSeparator() => emitter.Emit(", ");

      void ICodeGenerator.GenerateCallStart(Algorithm called,Procedure proc,bool canFail,bool onlyCallInAlternative,bool lastAlternative) {
         if (called.CanFail) {
            emitter.Emit("if (",TargetName(called),"(");
            ifDepth++;
            IncrementIndent();
         } else {
            emitter.Emit(TargetName(called),"(");
         }
      }

      void ICodeGenerator.GenerateCallEnd(Algorithm called,Procedure proc,Alternative alternative,bool canFail,bool onlyCallInAlternative,
            bool lastAlternative,int nextAlternative) {
         if (called.CanFail) {
            emitter.Emit(")) {");
         } else {
            emitter.Emit(");");
         }
         Newline();
      }

      void ICodeGenerator.GenerateCallArgString(string value) => emitter.Emit($"\"{value.Replace("\"","\\\"")}\"");

      void ICodeGenerator.GenerateCallArgReferenceAffix(Affix calledAffix,Affix arg,bool needFinalization) {
         Debug.Assert(!(arg.IsInputOnly && calledAffix.IsOutput),$"Illegal Affix {arg} in call to {calledAffix}");
         if (calledAffix.IsOutput) {
            emitter.Emit("ref ",TargetName(arg,needFinalization && arg.IsOutput ? "_" : ""));
         } else {
            emitter.Emit(TargetName(arg,needFinalization && arg.IsOutput ? "_" : ""));
         }
      }

      void ICodeGenerator.GenerateCallArgReferenceLocal(Affix calledAffix,Local lo) => emitter.Emit(calledAffix.IsOutput ? "ref " : "",TargetName(lo));
      void ICodeGenerator.GenerateCallArgReferenceConst(Affix calledAffix,Const c) => emitter.Emit(TargetName(c));
      void ICodeGenerator.GenerateCallArgReferenceVar(Affix calledAffix,Var v,bool needFinalization)
         => emitter.Emit(calledAffix.IsOutput ? "ref " : "",TargetName(v,needFinalization ? "_" : ""));

      void ICodeGenerator.GenerateRepeat(Procedure proc,Group group,ID label,bool canFail) {
         if (label.IsAnonymousGroup) {
            emitter.Emitnl("continue;");
         } else {
            emitter.Emitnl("goto ",label.CanonicalName,";");
         }
      }
      void ICodeGenerator.GenerateFail(Procedure proc,Group group) {
         if (!proc.IsVerySimple) emitter.Emitnl(proc.CanFail ? "return false;" : "return;");
      }

      void ICodeGenerator.GenerateSucceed(Procedure proc,Group group) { }
      void ICodeGenerator.GenerateAbort(Procedure proc,Group group,int _) => emitter.Emitnl("Environment.Exit(1);");
      #endregion Calls
      #endregion Procedures

      #region Support
      void ICodeGenerator.GenerateNewline() => Newline();
      void ICodeGenerator.GenerateComment(PrettyPrinter pp) => emitter.Emit(pp.Emitter.Content);
      void ICodeGenerator.GenerateSourceComment(bool nl) => emitter.NlEmit(nl ? "\n" : "",sourceEmitter.Content);
      string ICodeGenerator.FileExtension { get; } = ".cs";

      private readonly EmitterString sourceEmitter = new(prefix: "// ");
      Emitter ICodeGenerator.SourceEmitter => sourceEmitter;
      #endregion Support

      #region Helpers

      private void ConditionalWrapperStart(Algorithm called) {
         if (called.CanFail) {
            emitter.Emit("if (");
            ifDepth++;
            IncrementIndent();
         }
      }
      private void ConditionalWrapperEnd(Algorithm called) {
         if (called.CanFail) {
            emitter.Emit(") {");
         }
      }



      /// <summary>
      /// Generate the constant that will be assinged to an Affix, Local or Var.
      /// </summary>
      /// <param name="value"></param>
      /// <returns></returns>
      /// <exception cref="NotImplementedException"></exception>
      private string GenerateValueExpression(object value) => value switch {
         long l => l.ToString(),
         int i => i.ToString(),
         double d => d.ToString(System.Globalization.CultureInfo.InvariantCulture),
         string s => $"\"{s.Replace("\"","\\\"")}\"",
         _ => throw new NotImplementedException($"Value expression generation not implemented for type {value.GetType()}."),
      };
      #endregion Helpers
   }
}