// <auto-gen>
//=======================================================================
// <copyright file="CodeGeneratorC.cs" company="Peter Köves">RETURN
//     Copyright (c) Peter Köves, 2025. All rights reserved.
//     Licensed under the MIT License. See _LICENSE file in the project root
//     for full license information.
// </copyright>
//=======================================================================
// <author>Peter Köves</author>
// <creation-date>2025-12-18</creation-date>
// 
// <summary>
//   C code generator for CDL2.
//   Generates K&R C compatible code.
// </summary>
//=======================================================================
// </auto-gen>


using System.Diagnostics;

namespace CDL2v1 {
   internal partial class CodeGeneratorC : TargetCodeGenerator, ICodeGenerator {
      public string FileExtension => "c";
      public override bool RequiresPredeclaration => true;

      private readonly EmitterString sourceEmitter = new(prefix: "// ");
      public Emitter SourceEmitter => sourceEmitter;

      private readonly PrettyPrinter PPTrace = new(new EmitterAnsiString(),includeComments: false);

      private readonly string DataType;

      public CodeGeneratorC(string dataType) : base() => DataType = dataType;

      private CodeGenerator? cg = null;
      public void SetCodeGenerator(CodeGenerator cg) => this.cg = cg;

      public bool SupportsDebug => true;
      public bool SupportsSimpleDebug => true;

      public void GenerateProgramStart(Program program,Emitter emitter,string settings,bool isSeparate = false) {
         this.emitter = emitter;
         emitter.Emitnl("/*cspell:disable*/");
         emitter.Emitnl($"/*");
         emitter.Emitnl($" * C program generated by CDL2 v1.0.0 for PROGRAM {program.Id.Name} at {DateTime.Now:yyyy-MM-dd HH:mm:ss}.");
         emitter.Emitnl($" * Settings: {settings}");
         emitter.Emitnl($" */");
         emitter.Emitnl();
         emitter.Emitnl("#define _CRT_SECURE_NO_WARNINGS // Turn off deprecation warnings");
         GenerateComment("Must use 64 bit words to allow them to be used as address pointers. DataType is ignored.");
         emitter.Emitnl("#include <stdint.h>");
         emitter.Emitnl("#define VALUE int64_t");
         emitter.Emitnl("#define VALUE_MAX INT64_MAX");
         emitter.Emitnl("#define VALUE_MIN INT64_MIN");
         emitter.Emitnl("#define VALUE_UNDEFINED VALUE_MIN");
         emitter.Emitnl();
         emitter.Emitnl("#include \"CDL2.h\"");
         if (Settings.IsBacktrace || Settings.IsTrace) emitter.Emitnl("#include \"CDL2Trace.h\"");
         if (Settings.IsTrace) emitter.Emitnl("#define CDL2TRACE");
         emitter.Emitnl();
         emitter.Emitnl("int _argc;");
         emitter.Emitnl("char **_argv;");
         emitter.Emitnl();
         GenerateComment("===============================================================================");
         emitter.Emitnl();
         EmitUnitStartComment(program);
         emitter.Emitnl();
      }


      public void GenerateDebugInfoStart() {
         GenerateComment("##### Debug Information #####");
         emitter.Emitnl("C2DebugInfo c2_DebugInfo = {");
         IncrementIndent();
      }
      enum C2AlgType { C2_ALG_PREDICATE, C2_ALG_TEST, C2_ALG_ACTION, C2_ALG_FUNCTION };
      private static string AlgType(Algorithm proc) => (proc.AlgorithmType switch {
         RW.PREDICATE => C2AlgType.C2_ALG_PREDICATE.ToString(),
         RW.TEST => C2AlgType.C2_ALG_TEST.ToString(),
         RW.ACTION => C2AlgType.C2_ALG_ACTION.ToString(),
         RW.FUNCTION => C2AlgType.C2_ALG_FUNCTION.ToString(),
         _ => ""
      });
      private static string AffType(Algorithm proc,int i) => C2AffType(proc.Affixes[i]);
      public void GenerateDebugInfoEnd() {
         DecrementIndent();
         emitter.Emitnl("};");
         emitter.NlEmitnl($"\n{LineComment} ##### End Debug Information #####\n");
      }
      /// <summary>
      /// Generate the information that will be used by the debugger.
      /// </summary>
      /// <param name="procs"></param>
      public void GenerateDebugInfoProcsStart(IEnumerable<Algorithm> procs) {
         string procDesc(Algorithm proc) {      
            string container = proc.Section!.FQN(separator: ".",spaceReplacement: " ",quoted: true);
            string name = proc.Quoted();
            string type = AlgType(proc).ToString(); 
            int nargs = proc.Affixes.Count;
            string argnames = nargs == 0 ? "NULL" : "(char*[]){"+string.Join(",",proc.Affixes.Select(aff => aff.Id.Quoted()))+"}";
            string affTypes = nargs == 0 ? "NULL" : "(C2AffType[]){"+string.Join(",",proc.Affixes.Select(aff => C2AffType(aff)))+"}";
            int nlocals = proc.Locals.Count;
            string localnames = nlocals == 0 ? "NULL" : "(char*[]){" + string.Join(",",proc.Locals.Select(aff => aff.Id.Quoted()))+"}";
            PPTrace.Emitter.Clear();
            PPTrace.Print(proc, synthetics: true);
            string code = (Settings.IsTrace ? PPTrace.Emitter.Content : "").Quoted(escape:true); // Get the pretty printed code, but only if tracing
            return $"{{{container},{name},{type},{nargs},{argnames},{affTypes},{nlocals},{localnames},{code},FALSE,FALSE}}";
         }

         if (procs.Any()) {
            emitter.Emitnl($"{procs.Count()},(C2ProcInfo[]){{");
            IncrementIndent();
            emitter.Emit(procDesc(procs.First()!));
            foreach (Algorithm proc in procs.Skip(1)) emitter.Emit(",\n",procDesc(proc));
            DecrementIndent();
            emitter.NlEmit("},");
         } else {
            // This is impossible ...
            emitter.Emitnl("0,NULL,");
         }
      }
      /// <summary>
      /// Generates and emits debug information for a collection of variable definitions.
      /// </summary>
      /// <remarks>If the collection is empty, no output is generated. The variables are sorted by their
      /// names before emission, and the emitted format includes the fully qualified name, quoted representation, and a
      /// reference to the variable's C name.</remarks>
      /// <param name="vars">The collection of variables to generate debug information for. Each variable is represented by a Var object,
      /// which contains details necessary for the debug information.</param>
      public void GenerateDebugInfoVarsStart(IEnumerable<Var> vars) {
         string VarDesc(Var var) => $"{{{var.Section!.FQN(separator: ".",spaceReplacement: " ",quoted: true)},{var.Quoted()},&{TargetName(var)}}}";
         if (vars.Any()) {
            emitter.NlEmitnl($"{vars.Count()},(C2VarInfo[]){{");
            IncrementIndent();
            IOrderedEnumerable<Var> sortedVars = vars.OrderBy(v => v.Id.Name);
            emitter.Emit(VarDesc(sortedVars.First()!));
            foreach (Var var in sortedVars.Skip(1)) emitter.Emit(",\n",VarDesc(var));
            DecrementIndent();
            emitter.NlEmitnl("},");
         } else {
            emitter.NlEmitnl("0,NULL,  // No VARs");
         }
      }

      public void GenerateDebugInfoListsStart(IEnumerable<LIST> lists) {
         string ListDesc(LIST list) => $"{{{list.Section!.FQN(separator: ".",spaceReplacement: " ",quoted: true)},{list.Quoted()},{TargetName(list)}_array,"+
                           $"{TargetName(list.Section!.GetResolvedObject(list.lwb)!)},{TargetName(list.Section!.GetResolvedObject(list.upb)!)}}}";
         if (lists.Any()) {
            emitter.NlEmitnl($"{lists.Count()},(C2ListInfo[]){{");
            IncrementIndent();
            IOrderedEnumerable<LIST> sortedLists = lists.OrderBy(l => l.Id.Name);
            emitter.Emit(ListDesc(sortedLists.First()!));
            foreach (LIST list in sortedLists.Skip(1)) emitter.Emit(",\n",ListDesc(list));
            DecrementIndent();
            emitter.NlEmitnl("}");
         } else {
            emitter.Emitnl("0,NULL   // No LISTs");
         }
      }


      public void GenerateProgramLudesStart() {
         emitter.Emitnl();
         emitter.Emitnl("int main(int argc, char *argv[]) {");
         IncrementIndent();
         if (Settings.IsDebug) emitter.Emitnl("debug_pause();");
         emitter.Emitnl("_argc = argc;");
         emitter.Emitnl("_argv = argv;");
         if (Settings.IsBacktrace) emitter.Emitnl("\nc2DebugInfo = &c2_DebugInfo;");
         emitter.Emitnl();
      }

      public void GenerateProgramLudesEnd() { }

      public void GenerateProgramEnd(Program program,bool isSeparate = false) {
         emitter.Emitnl("return 0;");
         DecrementIndent();
         emitter.Emitnl("}");
         emitter.Emitnl();
         EmitUnitEndComment(program);
      }

      void ICodeGenerator.GenerateSourceComment(bool nl) {
         if (!Obfuscation) {
            emitter.NlEmit(nl ? "\n" : "",sourceEmitter.Content);
         } else {
            emitter.NlEmit(nl ? "\n" : "");
         }
      }


      public void GenerateComment(PrettyPrinter pp) { if (!Obfuscation) emitter.Emit(pp.Emitter.Content); }

      public void GenerateNewline() => emitter.Emitnl();

      public void GenerateObjectSectionStart<T>(IEnumerable<NamedElement> items,string typeName) where T : NamedElement {
         int n = items.Count();
         if (n > 0) GenerateComment($"\n##### {n} {typeName}{(n != 1 ? "s" : "")} #####\n");
      }

      public void GenerateObjectSectionEnd<T>(IEnumerable<NamedElement> items,string typeName) where T : NamedElement { }

      public void GenerateConstantStart(Const constant) => emitter.Emit("#define ",TargetName(constant)," ");
      public void GenerateConstElementInt(long value) => emitter.Emit(value);
      public void GenerateConstElementFloat(double value) => emitter.Emit(value);
      public void GenerateConstElementString(string value) => emitter.Emit(value);
      public void GenerateConstElementConst(Const c) => emitter.Emit(TArgName(c));

      public void GenerateConstantEnd(Const constant) => emitter.Emitnl();

      public void GenerateVar(Var v) => emitter.Emitnl("DECLARE_VAR(",TargetName(v),");");

      public void GenerateList(LIST list,Const lwb,Const upb) => emitter.Emitnl("DECLARE_LIST(",TargetName(list),",",TargetName(lwb),",",TargetName(upb),");");

      public void GenerateMacroStart(Macro macro) { if (!Obfuscation) emitter.NlEmit("\n",sourceEmitter.Content); else emitter.Emitnl(); }
      public void GenerateMacroEnd(Macro macro) {
         if (!macro.CanFail) emitter.NlEmitnl("RETURN; // macro end");
         DecrementIndent();
         emitter.Emitnl("}");
      }

      public void GenerateMacroBodyStart(Macro macro,bool inlining) { }

      public void GenerateMacroBodyEnd(Macro macro,bool inlining) { }

      public void GenerateReturnExpressionStart(Macro macro) {
         if (macro.CanFail) emitter.Emit(macro.NeedsFinalization ? "if (" : "RETURNV(");
      }

      public void GenerateReturnExpressionEnd(Macro macro,int alternativeNumber) {
         if (macro.CanFail) emitter.Emitnl(macro.NeedsFinalization ? ") goto Finalization; " : $");    {Comment("expression end")}");
      }

      private readonly Stack<int> FinalizationLabels = [];
      public void GenerateMacroInlineStart(Macro macro) {
         // if (macro.NeedsFinalization) FinalizationLabels.Push(NextLabel);
         if (macro.CanFail) emitter.Emit("if (!(");
      }
      public void GenerateMacroInlineEnd(Macro macro,int alternativeNumber,bool callerCanfail) {
         if (macro.CanFail) {
            if (alternativeNumber == Alternative.ALTERNATIVES_END) {
               if (callerCanfail) {
                  emitter.Emitnl($")) RETURNV(FALSE);  {Comment("macro inline end")}");
               } else {
                  emitter.Emitnl($")) RETURN;  {Comment("macro inline end")}");
               }
            } else {
               emitter.Emitnl($")) goto {ReferencedLabel(alternativeNumber)};");
            }
         } else {
            emitter.Emitnl();
         }
      }

      public void GenerateMacroElementInt(long value) => emitter.Emit(value);
      public void GenerateMacroElementFloat(double value) => emitter.Emit(value);

      public void GenerateMacroElementString(string value,bool firstElement,bool quoted) {
         if (quoted) {
            emitter.Emit("\"",value.Replace("\"","\\\""),"\"");
         } else {
            string[] lines = value.Split('\n');
            foreach (string line in lines.Skip(firstElement ? 1 : 0).SkipLast(1)) emitter.Emitnl(line);
            emitter.Emit(lines.Last());
         }
      }

      public void GenerateMacroElementConst(Const c) => emitter.Emit(TargetName(c));
      public void GenerateMacroElementVar(Var v,bool canFail,bool inlined = false) => emitter.Emit(TargetName(v,canFail && !inlined ? "_" : ""));
      public void GenerateMacroElementList(LIST l) => emitter.Emit(TargetName(l));
      public void GenerateMacroElementLocal(Local local,Affix calledAffix) => emitter.Emit(TargetName(local));
      /// <summary>
      /// ALways generate *a as (*a) to ensure ++ and -- work correctly.
      /// </summary>
      /// <param name="affix"></param>
      /// <param name="canFail"></param>
      public void GenerateMacroElementAffix(Affix affix,bool canFail) {
         if (affix.IsOutput) {
            if (canFail) {
               emitter.Emit(TargetName(affix,"_"));
            } else {
               emitter.Emit("(*" + TargetName(affix),")");
            }
         } else {
            emitter.Emit(TargetName(affix));
         }
      }

      #region Procedures
      public void GenerateProcedureStart(Procedure proc) {
         ResetLableReferences();
         emitter.Emitnl();
      }

      public void GenerateProcedureEnd(Procedure proc) {
         //emitter.Emitnl(proc.CanFail ? proc.NeedsFinalization 
         //   ? $"RETURNV(TRUE); {Comment("proc end can fail w. finalization")}"
         //   : $"RETURNV(FALSE); {Comment("proc end can fail w. finalization")}"
         //   : $"RETURN; {Comment("proc end")}");
         DecrementIndent();
         emitter.NlEmitnl("}");
      }

      private const string LabelPrefix = "L";
      private void GenerateLabel(int altNumber) { if (ReferencedLabels.Contains(altNumber)) emitter.Emitnl(LabelPrefix + altNumber +   ":"); }

      private readonly Set<int> ReferencedLabels = [];
      private void ResetLableReferences() => ReferencedLabels.Clear();
      private string ReferencedLabel(int altNumber) {
         string label = LabelPrefix + altNumber;
         ReferencedLabels.Add(altNumber);
         return label;
      }
      public void GenerateProcedureBodyStart(Procedure proc,ProcedureBodyType bodyType) { }

      public void GenerateProcedureBodyEnd(Procedure proc,ProcedureBodyType bodyType) { }

      public void GenerateAlternativeStart(Procedure proc,Group group,int alternativeNumber,bool supressLabel) {
         GenerateComment($"{group.Alternatives[alternativeNumber-1]}");
         if (!supressLabel) GenerateLabel(group.Alternatives[alternativeNumber-1].AlternativeNumber);
         IncrementIndent();
      }

      public void GenerateAlternativeEnd(Procedure proc,Group group,int alternativeNumber,Alternative alternative,bool removed,bool supressLabel) {
         if (!proc.IsLude && alternative.LastCall.type != LCT.Group && alternative.LastCall.type != LCT.Repeat && !removed && !alternative.Terminates) {
            emitter.Emitnl(proc.CanFail ? proc.NeedsFinalization
               ? $"goto Finalization;  {Comment("alt end")}"
               : $"RETURNV(TRUE); {Comment("alt end")}"
               : $"RETURN;  {Comment("alt end")}");
         }

         DecrementIndent();
         GenerateComment($"End {group.Alternatives[alternativeNumber-1]}");
      }

      public void GenerateGroupStart(Procedure proc,Group group) {
         if (proc.ReferrencesGroup(group.Id)) {
            GenerateComment($"Group ",block:true);
            emitter.Emitnl(TargetName(group),":");
         } else {
            GenerateComment($"Group {TargetName(group)}");
         }
         IncrementIndent();
      }

      public void GenerateGroupEnd(Procedure proc,Group group) {
         DecrementIndent();
         GenerateComment($"End Group {TargetName(group)}");
      }

      public void GenerateCallStart(Algorithm called,Procedure calling,bool canFail,bool onlyCallInAlternative,bool lastAlternative) {
         if (called.CanFail) emitter.Emit("if (! ");
         emitter.Emit(TargetName(called),"(");
      }

      public void GenerateCallEnd(Algorithm called,Procedure calling,Alternative alternative,bool canFail,bool onlyCallInAlternative,bool lastAlternative) {
         if (called.CanFail) {
            if (alternative.NextAlternativeNumber == Alternative.ALTERNATIVES_END) {
               emitter.Emit($")) RETURNV(FALSE); {Comment("call end")}");
            } else {
               emitter.Emit($")) goto {ReferencedLabel(alternative.NextAlternativeNumber)};");
            }
         } else {
            emitter.Emit(");");
         }
         Newline();
      }

      public void GenerateFail(Procedure proc,Group group) => emitter.Emitnl($"RETURNV(FALSE);  {Comment("fail")}");
      public void GenerateSucceed(Procedure proc,Group group) => emitter.Emitnl(proc.CanFail 
         ? $"RETURNV(TRUE); {Comment("succeed")}" 
         : $"RETURN; {Comment("succeed")}");
      public void GenerateAbort(Procedure proc,Group group,int algId) => emitter.Emitnl($"ABORT({proc.FQDN().Quoted()},{proc.AlgId});");
      public void GenerateRepeat(Procedure proc,Group group,ID label,bool canFail)
         => emitter.Emitnl("goto " + (label.IsAnonymous ? TargetName(group) : TargetName(label)) + ";");

      public void GenerateActualArgSeparator() => emitter.Emit(", ");
      public void GenerateCallArgString(string value) => emitter.Emit("\"",value.Replace("\"","\\\""),"\"");
      public void GenerateCallArgReferenceConst(Affix affix,Const c) => emitter.Emit(TargetName(c));

      public void GenerateCallArgReferenceVar(Affix affix,Var v,bool needFinalization) {
         if (affix.IsOutput) emitter.Emit("&",TargetName(v,needFinalization ? "_" : ""));
         else emitter.Emit(TargetName(v,needFinalization ? "_" : ""));
      }

      public void GenerateCallArgReferenceAffix(Affix affix,Affix actualArg,bool needsFinalization) {
         if (affix.IsOutput) {
            if (actualArg.IsOutput) {                          // output -> output
               if (needsFinalization) {
                  emitter.Emit("&",TargetName(actualArg,"_"));
               } else {
                  emitter.Emit(TargetName(actualArg));
               }
            } else {                                           // input -> output
               throw new UnreachableException($"Requested to genrate code for passing {actualArg} -> {affix}");
            }
         } else { // affix.IsInput
            if (actualArg.IsInputOnly) {                       // input -> input
               emitter.Emit(TargetName(actualArg));
            } else {                                           // output -> input
               if (needsFinalization) {
                  emitter.Emit(TargetName(actualArg,"_"));
               } else {
                  emitter.Emit("*(VALUE*)",TargetName(actualArg));
               }
            }
         }
      }

      public void GenerateCallArgReferenceLocal(Affix affix,Local local) => emitter.Emit(affix.IsOutput ? "&" : "",TargetName(local));
      #endregion Procedures

      public override void GenerateDeclaration(Algorithm alg) {
         GenerateAlgorithmHeaderStart(alg);
         CodeGenerator.GenerateAlgorithmAffixes(this,alg);
         emitter.Emitnl(");");
      }

      //public void GenerateAlgorithmHeaderStart(Algorithm alg) => emitter.Emit($"{(alg.CanFail ? "BOOL" : "void")} {TName(alg)}(");
      public void GenerateAlgorithmHeaderStart(Algorithm alg)
         => emitter.Emit($"{alg.BodyType switch { TT.PROCBODY or TT.PROCINLINEBODY => "PROC", _ => "MACRO" }} {alg.AlgorithmType} {TargetName(alg)}(");

      private static string C2AffType(Affix aff) => aff.affixDir switch {
         AD.input => "C2_AFF_INPUT",
         AD.output => "C2_AFF_OUTPUT",
         AD.transput => "C2_AFF_TRANSPUT",
         AD.NONE => "C2_AFF_STRING",
         _ => ""
      };
      public void GenerateAlgorithmHeaderEnd(Algorithm alg) {
         emitter.Emitnl(") {");
         IncrementIndent();

         EmitAffixesTraceData(alg);
      }
      private void EmitAffixesTraceData(Algorithm _) { }

      public void GenerateTraceEnter(Algorithm alg,IEnumerable<Local> locals,int algIndex) {  
         if (Settings.IsBacktrace) {
            static string affDiscriminator(Affix aff) => aff.IsOutput ? "PTR" : aff.IsString ? "STR" : "VAL";

            string affValues = "NULL";
            if (alg.Affixes.Count > 0) {
               affValues = "(C2DataValue[]){"+string.Join(",",alg.Affixes.Select(aff => $"{affDiscriminator(aff)}({TargetName(aff)})"))+"}";
            }
            string localValues = "NULL";
            if (locals.Any()) {
               localValues = "(VALUE*[]){" + string.Join(",",alg.Locals.Select(loc => $"&{TargetName(loc)}")) + "}";
            }
            string affRefs = $"{alg.Affixes.Count},C2AffValues,C2AffNames,C2AffTypes";
            string localsRefs = $"{locals.Count()},C2Locals,C2LocalNames";
            string id = alg.Id.Name;
            if (alg.IsSynthetic) {
               id = alg.FQN();
            }
            emitter.Emitnl($"c2push_callstack_frame({algIndex},{affValues},{localValues});");
            if (Settings.IsTrace) emitter.Emitnl("c2TraceEnter();");
         }
      }

      public void GenerateAffix(Affix affix,AffixDir dir,bool canFail) {
         switch (dir) {
            case AD.input:
               emitter.Emit("VALUE ",TargetName(affix));
               break;
            case AD.NONE:
               emitter.Emit("char *",TargetName(affix));
               break;
            default:
               emitter.Emit("VALUE *",TargetName(affix));
               break;
         }
      }

      public void GenerateAffixSeparator() => emitter.Emit(", ");

      public void GenerateLocal(Local local) => emitter.Emitnl("VALUE ",TargetName(local)," = ",InitialValue,";");

      public void GenerateAffixAndVariableInitializationStart(Algorithm alg) {
         if (alg.NeedsFinalization) GenerateComment("Initialization");
      }

      public void GenerateAffixAndVariableInitializationEnd(Algorithm alg) {
         if (alg.NeedsFinalization) GenerateComment("End Initialization");
      }

      public void GenerateAffixAndVariableInitializer(Algorithm alg,IFailureProtected item,bool isVar) {
         switch (item is Affix affix ? affix.affixDir : AD.transput) {
            case AD.NONE:
            case AD.input:
               break;
            case AD.output:
               if (isVar) {
                  emitter.Emitnl("VALUE ",TargetName((Var)item,"_")," = ",InitialValue,";");
               } else {
                  emitter.Emitnl("VALUE ",TargetName((Affix)item,"_")," = ",InitialValue,";");
               }
               break;
            case AD.transput:
               if (isVar) {
                  emitter.Emitnl("VALUE ",TargetName((Var)item,"_")," = ",TargetName((Var)item),";");
               } else {
                  emitter.Emitnl("VALUE ",TargetName((Affix)item,"_")," = *",TargetName((Affix)item),";");
               }
               break;
         }
      }

      public void GenerateAffixAndVariableFinalizationStart(Algorithm algorithm) {
         if (algorithm.NeedsFinalization) {
            // emitter.Emitnl("RETURNV(FALSE);");
            emitter.Emitnl("Finalization:");
         }
      }

      public void GenerateAffixAndVariableFinalizationEnd(Algorithm algorithm) {
         if (algorithm.NeedsFinalization) {
            GenerateComment("End Finalization");
            emitter.Emitnl($"RETURNV(TRUE);     {Comment("finalization end")}");
         }
      }

      public void GenerateAffixAndVariableFinalizer(Algorithm alg,IFailureProtected item,bool isVar) {
         switch (item is Affix affix ? affix.affixDir : AD.transput) {
            case AD.NONE:
            case AD.input:
               break;
            default:
               if (isVar) {
                  emitter.Emitnl(TargetName((Var)item)," = ",TargetName((Var)item,"_"),";");
               } else {
                  emitter.Emitnl("*",TargetName((Affix)item)," = ",TargetName((Affix)item,"_"),";");
               }
               break;
         }
      }

      public void GenerateProgramPart(Program program,ID moduleId,bool isSeparate) { }

      public void GenerateProgramLudeStart(RW ludeType,Program program) => emitter.Emitnl("/* Program ",ludeType," */");

      public void GenerateProgramLudeEnd(RW ludeType,Program program) { }

      public void GenerateProgramLude(RW ludeType,Program program,Module module) =>
            emitter.Emitnl($"{module.TypeShortName}_{module.Id.Name.AsIdentifier(camelCase: false)}__{ludeType}();");

      public void GenerateModuleStart(Module module,bool isSeparate,string? headerFileName = null) {
         emitter.Emitnl();
         EmitUnitStartComment(module);
      }

      public void GenerateModuleEnd(Module module,bool isSeparate) => EmitUnitEndComment(module);

      public void GenerateImpExStart(Module module) { }
      public void GenerateImpExEnd(Module module) { }
      public void GenerateExport(IProvidable exportedItem) { }
      public void GenerateImport(IProvidable importedItem) { }

      public void GenerateModuleLudeStart(RW ludeType,Module module,bool wrapped) {
         GenerateComment($"MOD {module.Id.Name} {ludeType}");
         if (wrapped) {
            string returnType = ludeType == RW.ROOT || ludeType == RW.PRELUDE || ludeType == RW.POSTLUDE ? "void" : "VALUE";
            string moduleName = $"{module.TypeShortName}_{module.Id.Name.AsIdentifier(camelCase: false)}__{ludeType}";

            emitter.Emitnl(returnType," ",moduleName,"__",ludeType,"()");
            emitter.Emitnl("{");
            IncrementIndent();
         }
         IncrementIndent();
      }

      public void GenerateModuleLudeEnd(RW ludeType,Module module,bool wrapped) {
         if (wrapped) {
            DecrementIndent();
            emitter.Emitnl("}");
         }
         DecrementIndent();
      }

      public void GenerateModuleLude(RW ludeType,Module module,Section section) {
         Guid ludeGuid = section.LudeProcs[ludeType] ?? Guid.Empty;
         if (ludeGuid != Guid.Empty && ludeGuid.ToCDL2Object<Procedure>() is Procedure lude) {
            GenerateComment($"{section} {ludeType}");
            emitter.Emitnl(TargetName(lude),"();");
         }
      }

      public void GenerateLayerStart(Layer layer) { }
      public void GenerateLayerEnd(Layer layer) { }
      public void GenerateSectionStart(Section section) { }
      public void GenerateSectionEnd(Section section) { }
      public void GenerateSectionLudeStart(RW ludeType,Section section) { }
      public void GenerateSectionLudeEnd(RW ludeType,Section section) { }
      public void GenerateSectionLude(RW ludeType,Section section,Procedure proc) => emitter.Emitnl(TargetName(proc),"();");


      #region Helpers
      /// <summary>
      /// Generate the constant that will be assinged to an Affix, Local or Var.
      /// </summary>
      /// <param name="value"></param>
      /// <returns></returns>
      /// <exception cref="NotImplementedException"></exception>
      private string GenerateValueExpression(object value) => value switch {
         long l => l.ToString(),
         int i => i.ToString(),
         double d => d.ToString(System.Globalization.CultureInfo.InvariantCulture),
         string s => $"\"{s.Replace("\"","`\"")}\"",
         _ => throw new NotImplementedException($"Value expression generation not implemented for type {value.GetType()}."),
      };

      protected override string InitialValue => "VALUE_UNDEFINED";


      #endregion Helpers
   }
}