// Ignore Spelling: Finalizer lwb upb CDL

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Diagnostics.Eventing.Reader;
using System.IO;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace CDL2v1 {
   [Serializable]
   internal class CodeGeneratorPowerShell : ICodeGenerator {
      EmitterBase emitter = new EmitterSink();
      private readonly string DataType;
      private readonly string DT;

      /// <summary>
      /// Constructor for the PowerShell proc generator.
      /// </summary>
      /// <param name="dataType">This can be used to change the word size, e.g., to Int32.</param>
      /// <remarks>No explicit references to this class. The instance is constructed via reflection.</remarks>
      CodeGeneratorPowerShell(string dataType) {
         DataType = dataType;
         DT       = $"[{DataType}]";
      }

      string ICodeGenerator.FileExtension { get; } = ".ps1";
      private static readonly string ProgramHeaderPattern = @"
<#
.SYNOPSIS
   PowerShell proc generated by CDL2 notLastAlternativeOfProc<%0%> for Program <%1%> at <%2:yyyy-MM-dd HH:mm:ss%>.
#>
class BoundedArray {
   [int]$LowerBound
   [int]$UpperBound
   [Array]$Array
   

   BoundedArray([int]$lowerBound, [int]$upperBound) {
       if ($upperBound - $lowerBound -lt 0) {
           throw [System.ArgumentException]::new(""Upper bound $($this.UpperBound) must be greater than or equal to lower bound $($this.LowerBound)."")
       }
       $this.LowerBound = $lowerBound
       $this.UpperBound = $upperBound
       $this.Array = [<%3%>[]]::new($upperBound - $lowerBound + 1)
   }
   [void]CheckIndex([int]$index) {
      if ($index - $this.LowerBound -ge 0 -and $index - $this.LowerBound -le $this.UpperBound - $this.LowerBound) {
         return
      } else {
         throw [System.IndexOutOfRangeException]::new(""Index: $index, LowerBound: $($this.LowerBound), UpperBound: $($this.UpperBound)"")
       }
   }
   # These do NOT create a [] indexer
   [<%3%>]Item([int]$index) {
      $this.CheckIndex($index)
      return $this.Array[$index - $this.LowerBound]
   }

   [void]Item([int]$index, [<%3%>]$value) {
      $this.CheckIndex($index)
      $this.Array[$index - $this.LowerBound] = $value
   }
}

#===============================================================================
";
      private static readonly string ProgramHeader;

      static CodeGeneratorPowerShell() => ProgramHeader = ProgramHeaderPattern.Replace("{","{{").Replace("}","}}").Replace("<%","{").Replace("%>","}");


      void ICodeGenerator.GenerateProgramStart(Program program,EmitterBase emitter,bool isSeparate) {
         this.emitter = emitter;
         emitter.Emitnl(string.Format(ProgramHeader,CDL2.Version,program.id.Name,DateTime.Now,DataType));
         if (program != null) EmitUnitStartComment(program);
      }

      void ICodeGenerator.GenerateProgramEnd(Program program,bool isSeparate) {
         if (program != null) EmitUnitEndComment(program);
      }
      void ICodeGenerator.GenerateModuleStart(Module module,bool isSeparate,string? target) {
         if (isSeparate) {
            // Changes the target file name to be the module name with the extension. Ignored by emitters except for the file emitter.
            // This causes the file emitter to close the current file and switch to the new file.
            emitter.Target = Path.Combine(Path.GetDirectoryName(emitter.Target)??"",module.id.InternalName+((ICodeGenerator)this).FileExtension);
         }
         EmitUnitStartComment(module);
      }
      void ICodeGenerator.GenerateModuleEnd(Module module,bool isSeparate) => EmitUnitEndComment(module);
      void ICodeGenerator.GenerateLayerStart(Layer layer) => EmitUnitStartComment(layer);
      void ICodeGenerator.GenerateLayerEnd(Layer layer) => EmitUnitEndComment(layer);
      void ICodeGenerator.GenerateSectionStart(Section section) => EmitUnitStartComment(section);
      void ICodeGenerator.GenerateSectionEnd(Section section) => EmitUnitEndComment(section);

      void ICodeGenerator.GenerateRequiringUnitLudesStart(IRequiringUnit unit) { }
      void ICodeGenerator.GenerateRequiringUnitLude(RW ludeType,IRequiringUnit requiring,IProviderUnit provider) => throw new NotImplementedException();
      void ICodeGenerator.GenerateRequiringUnitLudesEnd(IRequiringUnit requiring) { }
      void ICodeGenerator.GenerateProgramPart(Program program,ID mod,bool isSeparate) { }
      void ICodeGenerator.GenerateImpExStart(Module module) { }
      void ICodeGenerator.GenerateImpExEnd(Module module) { }

      enum PSVarType { Var, List, Const, Affix, Local }



      void ICodeGenerator.GenerateExport(IProvidedElement export) { }
      void ICodeGenerator.GenerateImport(IProvidedElement import) { }

      void ICodeGenerator.GenerateAlgorithmHeaderStart(Algorithm proc) => emitter.Emit($"function {PSName(proc)} (");
      void ICodeGenerator.GenerateAlgorithmHeaderEnd(Algorithm proc) {
         emitter.Emitnl(") {");
         emitter.IndentLevel++;
      }

      void ICodeGenerator.GenerateProcedureStart(Procedure code) { }
      void ICodeGenerator.GenerateProcedureEnd(Procedure proc) {
         if (proc.CanFail) emitter.Emitnl("return $__b");
         emitter.IndentLevel--;
         emitter.NlEmitnl("}");
      }

      void ICodeGenerator.GenerateCallEnd(Call call) => throw new NotImplementedException();


      void ICodeGenerator.GenerateCallStart(Call call) => throw new NotImplementedException();



      void ICodeGenerator.GenerateSectionLudeStart(RW ludeType,Section section) => throw new NotImplementedException();
      void ICodeGenerator.GenerateSectionLudeEnd(RW ludeType,Section section) => throw new NotImplementedException();
      void ICodeGenerator.GenerateMacroStart(Macro macro) { }
      void ICodeGenerator.GenerateMacroEnd(Macro macro) {
         emitter.IndentLevel--;
         emitter.NlEmitnl("}");
      }

      void ICodeGenerator.GenerateAffixSeparator() => emitter.Emit(",");

      void ICodeGenerator.GenerateMacroElementInt(long value) => emitter.Emit(value);
      void ICodeGenerator.GenerateMacroElementFloat(double value) => emitter.Emit(value);
      void ICodeGenerator.GenerateMacroElementString(string value) {
         string[] lines = value.Split('\n');
         foreach (string line in lines.SkipLast(1)) emitter.Emitnl(line);
         emitter.Emit(lines.Last());
      }
      void ICodeGenerator.GenerateMacroElementVar(Var var) => emitter.Emit(PSVar(var,"_"));
      void ICodeGenerator.GenerateMacroElementList(LIST list) => emitter.Emit(PSVar(list));
      void ICodeGenerator.GenerateMacroElementConst(Const constant) => emitter.Emit(PSVar(constant));
      void ICodeGenerator.GenerateMacroElementAffix(Affix affix) => emitter.Emit(PSVar(affix,"_"));
      void ICodeGenerator.GenerateMacroElementLocal(Local local) => emitter.Emit(PSVar(local));
      void ICodeGenerator.GenerateLocal(Local local) => emitter.Emitnl(DT,PSVar(local)," = 0");
      void ICodeGenerator.GenerateAffix(Affix affix,AD dir) {
         switch (dir) {
            case AD.input:
               emitter.Emit(DT,PSVar(affix,"_"));
               break;
            case AD.NONE:
               // String (given as AD.NONE)
               emitter.Emit("[string]",PSVar(affix,"_"));
               break;
            default:
               emitter.Emit("[ref]",PSVar(affix));
               break;
         }
      }
      void ICodeGenerator.GenerateVar(Var var) => emitter.Emitnl(DT,PSVar(var)," = 0");
      void ICodeGenerator.GenerateList(LIST var,Const lwb,Const upb) => emitter.Emitnl(PSVar(var),$" = [BoundArray]::new({PSVar(lwb)},{PSVar(upb)})");
      void ICodeGenerator.GenerateInitializer(IFailureProtected var,AD affixDir,bool isVar) {
         switch (affixDir) {
            case AD.NONE:               
            case AD.input:
               break;
            case AD.output:
               if (isVar) {
                  emitter.Emitnl(DT,PSVar((Var)var,"_")," = 0");
               } else {
                  emitter.Emitnl(DT,PSVar((Affix)var,"_")," = 0");
               }
               break;
            case AD.transput:
               if (isVar) { 
                  emitter.Emitnl(DT,PSVar((Var)var,"_")," = ",PSVar((Var)var)); 
               } else {
                  emitter.Emitnl(DT,PSVar((Affix)var,"_")," = ",PSVar((Affix)var,suffix:".Value"));
               }
               break;
         }
      }

      void ICodeGenerator.GenerateFinalizer(IFailureProtected var,AD affixDir,bool isVar) {
         switch (affixDir) {
            case AD.NONE:
            case AD.input:
               break;
            default:
               if (isVar) {
                  emitter.Emitnl(PSVar((Var)var)," = ",PSVar((Var)var,"_"));
               } else {
                  emitter.Emitnl(PSVar((Affix)var,suffix:".Value")," = ",PSVar((Affix)var,"_"));
               }
               break;
         }
      }


      void ICodeGenerator.GenerateMacroBodyStart(Macro macro) {
         if (macro.CanFail) emitter.Emitnl("$__b = (");
         emitter.IndentLevel++;
      }
      void ICodeGenerator.GenerateMacroBodyEnd(Macro macro) {
         emitter.Emitnl();
         emitter.IndentLevel--;
         if (macro.CanFail) emitter.Emitnl(")");
      }

      void ICodeGenerator.GenerateProcedureBodyStart(Procedure proc,PBT bodyType) {
         if (proc.repeatsProcedure) emitter.Emit(":",proc.id.InternalName," ");
         //TODO: The needs finalization test for enclosing do { } while ($true) is likely wrong.
         if (!proc.IsVerySimple || proc.NeedsFinalization) emitter.Emitnl("do {");
         emitter.IndentLevel++;
      }
      void ICodeGenerator.GenerateProcedureBodyEnd(Procedure proc,PBT bodyType) {
         if (proc.NeedsFinalization) emitter.Emitnl("break");
         emitter.IndentLevel--;
         if (!proc.IsVerySimple || proc.NeedsFinalization) emitter.Emitnl("} while ($true)");
      }

      void ICodeGenerator.GenerateFinalizationStart(Algorithm algorithm,bool IsNeeded) {
         if (IsNeeded && algorithm.CanFail) {
            emitter.Emitnl("if ($__b) {");
            emitter.IndentLevel++;
         }
      }
      void ICodeGenerator.GenerateFinalizationEnd(Algorithm algorithm,bool IsNeeded) {
         if (IsNeeded && algorithm.CanFail) {
            emitter.IndentLevel--;
            emitter.Emitnl("}");
         }
      }

      void ICodeGenerator.GenerateConstantStart(Const c) => emitter.Emit(PSVar(c)," = ");
      void ICodeGenerator.GenerateConstElementString(string value) => ((ICodeGenerator)this).GenerateMacroElementString(value);
      void ICodeGenerator.GenerateConstElementFloat(double value)  => ((ICodeGenerator)this).GenerateMacroElementFloat(value);
      void ICodeGenerator.GenerateConstElementInt(long value)      => ((ICodeGenerator)this).GenerateMacroElementInt(value);
      void ICodeGenerator.GenerateConstantEnd(Const c) => emitter.Emitnl();
      void ICodeGenerator.GenerateObjectSectionStart(Func<int> count,string v) {
         int n = count();
         if (n > 0) emitter.NlEmitnl($"\n##### {n} {v}{(n != 1 ? "s" : "")} #####\n");
      }

      void ICodeGenerator.GenerateActualArgSeparator() => emitter.Emit(" ");
      void ICodeGenerator.GenerateCallStart(Algorithm called,Procedure proc,bool canFail) {
         if (!proc.IsVerySimple) {
            if (canFail) emitter.Emit("if ($__b) { ");
            if (called.CanFail) emitter.Emit("[bool]$__b = ");
         }
         emitter.Emit(PSName(called)," ");
      }
      void ICodeGenerator.GenerateCallEnd(Algorithm call,Procedure proc,bool canFail) {
         if (canFail && !proc.IsVerySimple) {
            emitter.Emit(" }");
         }
         Newline();
      }

      void ICodeGenerator.GenerateCallArgString(string value) => emitter.Emit($"\"{value}\"");
      void ICodeGenerator.GenerateCallArgReferenceAffix(Affix calledAffix,Affix a) => emitter.Emit(PSVar(a,"_",isRef:calledAffix.IsOutput));
      void ICodeGenerator.GenerateCallArgReferenceLocal(Affix calledAffix,Local lo) => emitter.Emit(PSVar(lo,isRef: calledAffix.IsOutput));
      void ICodeGenerator.GenerateCallArgReferenceConst(Affix calledAffix,Const c) => emitter.Emit(PSVar(c));
      void ICodeGenerator.GenerateCallArgReferenceVar(Affix calledAffix,Var v) => emitter.Emit(PSVar(v,"_",isRef: calledAffix.IsOutput));
      void ICodeGenerator.GenerateAlternativeStart(Procedure proc,Group group,int i) {
         GenerateComment($"Alternative {i+1}");
         emitter.IndentLevel++;
      }
      void ICodeGenerator.GenerateAlternativeEnd(Procedure proc,Group group,int i) {
         bool notLastAlternativeOfProc = group != proc.group || group.alternatives.Count != i + 1;
         if (proc.NeedsFinalization && notLastAlternativeOfProc) {
            emitter.Emitnl("if ($__b) { break }");
         } else if (notLastAlternativeOfProc && group.alternatives[i].lastCall.type != LCT.Repeat) { 
            emitter.Emitnl("if ($__b) { ",proc.CanFail ? "return $__b }" : "return }");
         } else if (proc.NeedsFinalization && !group.alternatives[i].CanFail) {
            emitter.Emitnl("$__b = $true");
         }
            emitter.IndentLevel--;
      }
      void ICodeGenerator.GenerateRepeat(Procedure proc,Group group,ID label) {
         // TODO: Needs more work to ensure labels are unique within a proc
         if (label == ID.AnonID) {
            emitter.Emitnl("if ($__b) { continue }");
         } else {
            emitter.Emitnl("if ($__b) { continue ",label.InternalName," }");
         }
      }
      void ICodeGenerator.GenerateFail(Procedure proc,Group group) {
         if (! proc.IsVerySimple) {
            emitter.Emitnl(proc.CanFail ? "return $false" : "return");
         }
      }
      void ICodeGenerator.GenerateSucceed(Procedure proc,Group group) { }
      void ICodeGenerator.GenerateAbort(Procedure proc,Group group) => emitter.Emitnl("exit 1");
      void ICodeGenerator.GenerateGroupStart(Procedure proc,Group group) {
         if (!group.IsSynthetic) emitter.Emit(":",group.id.InternalName," ");
         emitter.Emitnl("do {");
         emitter.IndentLevel++;
      }
      void ICodeGenerator.GenerateGroupEnd(Procedure proc,Group group) {
         emitter.IndentLevel--;
         emitter.Emitnl("} while ($true)");
      }

      void ICodeGenerator.GenerateObjectSectionEnd(Func<int> count,string name) { }

      void ICodeGenerator.GenerateConstElementConst(Const constant) => emitter.Emit(PSVar(constant));
      void ICodeGenerator.Newline() => Newline();
      void ICodeGenerator.GenerateComment(string comment) => GenerateComment(comment);

      #region Helpers
      void Newline() => emitter.Emitnl();
      private void EmitUnitStartComment(Container unit) => emitter.Emitnl($"# Begin {unit.ContainerName}");
      private void EmitUnitEndComment(Container unit) => emitter.Emitnl($"# End {unit.ContainerName}");
      private void GenerateComment(string comment) {
         foreach (string line in comment.Split('\n')) emitter.Emitnl("# ",line);
      }

      private static string PSVarPrefix(PSVarType type) => type switch {
         PSVarType.Var => "V_",
         PSVarType.List => "LL_",
         PSVarType.Const => "C_",
         PSVarType.Affix => "A_",
         PSVarType.Local => "L_",
         _ => throw new NotImplementedException(),
      };
      private static PSVarType PSVarTypeOf(DeclaredCDL2Object obj) => obj switch {
         Var => PSVarType.Var,
         LIST => PSVarType.List,
         Const => PSVarType.Const,
         _ => throw new NotImplementedException(),
      };

      private static string PS_Var(string name,PSVarType type,string prefix = "",string suffix = "",bool isRef = false) => $"{(isRef ? "[ref]" : "")}${prefix}{PSVarPrefix(type)}{name}{suffix}";
      private static string PSVar(DeclaredCDL2Object obj,string prefix = "",string suffix = "",bool isRef = false) => PS_Var(PSName(obj),PSVarTypeOf(obj),prefix,suffix,isRef);
      private static string PSVar(Affix affix,string prefix = "",string suffix = "",bool isRef = false) => PS_Var(PSName(affix),PSVarType.Affix,prefix,suffix,isRef);
      private static string PSVar(Local local,string prefix = "",string suffix = "",bool isRef = false) => PS_Var(PSName(local),PSVarType.Local,prefix,suffix,isRef);

      private static string PSName(DeclaredCDL2Object obj) => obj.FQN(camelCase: true,literalObjectName: obj.IsSynthetic);
      private static string PSName(Affix affix) => affix.id.Name.AsIdentifier(camelCase: true);
      private static string PSName(Local local) => local.id.Name.AsIdentifier(camelCase: true);

      #endregion Helpers
   }
}
