// <auto-gen>
//=======================================================================
// <copyright file="CodeGeneratorC.cs" company="Peter Köves">
//     Copyright (c) Peter Köves, 2025. All rights reserved.
//     Licensed under the MIT License. See _LICENSE file in the project root
//     for full license information.
// </copyright>
//=======================================================================
// <author>Peter Köves</author>
// <creation-date>2025-12-18</creation-date>
// 
// <summary>
//   C code generator for CDL2.
//   Generates K&R C compatible code.
// </summary>
//=======================================================================
// </auto-gen>

using Microsoft.VisualBasic;

using System.ComponentModel;
using System.Diagnostics;
using System.Reflection;
using System.Reflection.Emit;
using System.Reflection.Metadata;
using System.Text.RegularExpressions;

namespace CDL2v1 {
   internal partial class CodeGeneratorC : TargetCodeGenerator, ICodeGenerator {
      public string FileExtension => "c";
      public override bool RequiresPredeclaration => true;

      private readonly EmitterString sourceEmitter = new(prefix: "// ");
      public Emitter SourceEmitter => sourceEmitter;

      private PrettyPrinter PPTrace = new(new EmitterAnsiString(),includeComments: false);

      private readonly string DataType;

      public CodeGeneratorC(string dataType) : base() => DataType = dataType;

      private CodeGenerator? cg = null;
      public void SetCodeGenerator(CodeGenerator cg) => this.cg = cg;

      public bool SupportsDebug => true;
      public bool SupportsSimpleDebug => true;

      public void GenerateProgramStart(Program program,Emitter emitter,string settings,bool isSeparate = false) {
         this.emitter = emitter;
         emitter.Emitnl("/*cspell:disable*/");
         emitter.Emitnl($"/*");
         emitter.Emitnl($" * C program generated by CDL2 v1.0.0 for PROGRAM {program.Id.Name} at {DateTime.Now:yyyy-MM-dd HH:mm:ss}.");
         emitter.Emitnl($" * Settings: {settings}");
         emitter.Emitnl($" */");
         emitter.Emitnl();
         emitter.Emitnl($"#define VALUE {DataType}");
         emitter.Emitnl();
         emitter.Emitnl("#include \"CDL2.h\"");
         if (Settings.SettingValue<bool>("backtrace") || Settings.SettingValue<bool>("trace")) emitter.Emitnl("#include \"CDL2Trace.h\"");
         emitter.Emitnl();
         emitter.Emitnl("int _argc;");
         emitter.Emitnl("char **_argv;");
         emitter.Emitnl();
         base.GenerateComment("===============================================================================");
         emitter.Emitnl();
         EmitUnitStartComment(program);
         emitter.Emitnl();
         LabelCounter = 0;
      }


      public void GenerateDebugInfoStart() {
         emitter.NlEmitnl($"\n{BlockComment.Start} ##### Debug Information ##### {BlockComment.End}\n");
         emitter.Emitnl("C2DebugInfo c2_DebugInfo = {");
         IncrementIndent();
      }
      enum C2AlgType { C2_ALG_PREDICATE, C2_ALG_TEST, C2_ALG_ACTION, C2_ALG_FUNCTION };
      private static string AlgType(Algorithm proc) => (proc.AlgorithmType switch {
         RW.PREDICATE => C2AlgType.C2_ALG_PREDICATE.ToString(),
         RW.TEST => C2AlgType.C2_ALG_TEST.ToString(),
         RW.ACTION => C2AlgType.C2_ALG_ACTION.ToString(),
         RW.FUNCTION => C2AlgType.C2_ALG_FUNCTION.ToString(),
         _ => ""
      });
      private static string AffType(Algorithm proc,int i) => C2AffType(proc.Affixes[i]);
      public void GenerateDebugInfoEnd() {
         DecrementIndent();
         emitter.Emitnl("};");
         emitter.NlEmitnl($"\n{BlockComment.Start} ##### End Debug Information ##### {BlockComment.End}\n");
      }
      /// <summary>
      /// Generate the information that will be used by the debugger. Note that the information is sorted on the ID of the objects
      /// to allow binary search to be used to look up names. by ID.
      /// </summary>
      /// <param name="procs"></param>
      public void GenerateDebugInfoProcsStart(IEnumerable<Algorithm> procs) {
         string procDesc(Algorithm proc) {      
            string container = proc.Section!.FQN(separator: ".",replacement: " ",quoted: true);
            string name = proc.Quoted();
            string type = AlgType(proc).ToString(); 
            int nargs = proc.Affixes.Count;
            //string argnames = "{" +(nargs == 0 ? "\"\"" : string.Join(",",proc.Affixes.Select(aff => aff.Id.Quoted()))) + "}";
            //string affTypes = nargs == 0 ? "C2_AFF_INPUT" : "{"+string.Join(",",proc.Affixes.Select(aff => C2AffType(aff)))+"}";
            string argnames = nargs == 0 ? "NULL" : "(char*[]){"+string.Join(",",proc.Affixes.Select(aff => aff.Id.Quoted()))+"}";
            string affTypes = nargs == 0 ? "NULL" : "(C2AffType[]){"+string.Join(",",proc.Affixes.Select(aff => C2AffType(aff)))+"}";
            int nlocals = proc.Locals.Count;
            //string localnames = "{" + (nlocals == 0 ? "\"\"" : string.Join(",",proc.Locals.Select(aff => aff.Id.Quoted()))) + "}";
            string localnames = nlocals == 0 ? "NULL" : "(char*[]){" + string.Join(",",proc.Locals.Select(aff => aff.Id.Quoted()))+"}";
            PPTrace.Emitter.Clear();
            PPTrace.Print(proc);
            string code = PPTrace.Emitter.Content.Quoted(escape:true); // Get the pretty printed code here
            return $"{{{container},{name},{type},{nargs},{argnames},{affTypes},{nlocals},{localnames},{code},FALSE,FALSE}}";
         }

         if (procs.Any()) {
            emitter.Emitnl($"{procs.Count()},(C2ProcInfo[]){{");
            IncrementIndent();
            emitter.Emit(procDesc(procs.First()!));
            foreach (Algorithm proc in procs.Skip(1)) emitter.Emit(",\n",procDesc(proc));
            DecrementIndent();
            emitter.NlEmit("},");
         } else {
            emitter.Emitnl("NULL,");
         }
      }
      /// <summary>
      /// Generates and emits debug information for a collection of variable definitions.
      /// </summary>
      /// <remarks>If the collection is empty, no output is generated. The variables are sorted by their
      /// names before emission, and the emitted format includes the fully qualified name, quoted representation, and a
      /// reference to the variable's C name.</remarks>
      /// <param name="vars">The collection of variables to generate debug information for. Each variable is represented by a Var object,
      /// which contains details necessary for the debug information.</param>
      public void GenerateDebugInfoVarsStart(IEnumerable<Var> vars) {
         static string VarDesc(Var var) => $"{{{var.Section!.FQN(separator: ".",replacement: " ",quoted: true)},{var.Quoted()},&{CName(var)}}}";
         if (vars.Any()) {
            emitter.NlEmitnl($"{vars.Count()},(C2VarInfo[]){{");
            IncrementIndent();
            IOrderedEnumerable<Var> sortedVars = vars.OrderBy(v => v.Id.Name);
            emitter.Emit(VarDesc(sortedVars.First()!));
            foreach (Var var in sortedVars.Skip(1)) emitter.Emit(",\n",VarDesc(var));
            DecrementIndent();
            emitter.NlEmitnl("},");
         } else {
            emitter.NlEmitnl("NULL,");
         }
      }

      public void GenerateDebugInfoListsStart(IEnumerable<LIST> lists) {
         static string ListDesc(LIST list) => $"{{{list.Section!.FQN(separator: ".",replacement: " ",quoted: true)},{list.Quoted()},{CName(list)}_array,"+
                           $"{CName(list.Section!.GetResolvedObject(list.lwb)!)},{CName(list.Section!.GetResolvedObject(list.upb)!)}}}";
         if (lists.Any()) {
            emitter.NlEmitnl($"{lists.Count()},(C2ListInfo[]){{");
            IncrementIndent();
            IOrderedEnumerable<LIST> sortedLists = lists.OrderBy(l => l.Id.Name);
            emitter.Emit(ListDesc(sortedLists.First()!));
            foreach (LIST list in sortedLists.Skip(1)) emitter.Emit(",\n",ListDesc(list));
            DecrementIndent();
            emitter.NlEmitnl("}");
         } else {
            emitter.Emitnl("NULL");
         }
      }


      public void GenerateProgramLudesStart() {
         emitter.Emitnl();
         emitter.Emitnl("int main(int argc, char *argv[]) {");
         IncrementIndent();
         if (Settings.Debug) emitter.Emitnl("debug_pause();");
         emitter.Emitnl("_argc = argc;");
         emitter.Emitnl("_argv = argv;");
         if (Settings.IsBacktrace) emitter.Emitnl("\nc2DebugInfo = &c2_DebugInfo;");
         emitter.Emitnl();
      }

      public void GenerateProgramLudesEnd() { }

      public void GenerateProgramEnd(Program program,bool isSeparate = false) {
         emitter.Emitnl("return 0;");
         DecrementIndent();
         emitter.Emitnl("}");
         emitter.Emitnl();
         EmitUnitEndComment(program);
      }

      void ICodeGenerator.GenerateSourceComment(bool nl) => emitter.NlEmit(nl ? "\n" : "",sourceEmitter.Content);

      public new void GenerateComment(string comment) {
         foreach (string line in comment.Split('\n')) emitter.Emitnl($"{LineComment} ",line);
      }

      public void GenerateComment(PrettyPrinter pp) => emitter.Emit(pp.Emitter.Content);

      public void GenerateNewline() => emitter.Emitnl();

      public void GenerateObjectSectionStart<T>(IEnumerable<NamedElement> items,string typeName) where T : NamedElement {
         int n = items.Count();
         if (n > 0) emitter.NlEmitnl($"\n{BlockComment.Start} ##### {n} {typeName}{(n != 1 ? "s" : "")} ##### {BlockComment.End}\n");
      }

      public void GenerateObjectSectionEnd<T>(IEnumerable<NamedElement> items,string typeName) where T : NamedElement { }

      public void GenerateConstantStart(Const constant) => emitter.Emit("#define ",CName(constant)," ");
      public void GenerateConstElementInt(long value) => emitter.Emit(value);
      public void GenerateConstElementFloat(double value) => emitter.Emit(value);
      public void GenerateConstElementString(string value) => emitter.Emit("\"",value,"\"");
      public void GenerateConstElementConst(Const c) => emitter.Emit(CArgName(c));

      public void GenerateConstantEnd(Const constant) => emitter.Emitnl();

      public void GenerateVar(Var v) => emitter.Emitnl("DECLARE_VAR(",CName(v),",",Random.Next(0,int.MaxValue),");");

      public void GenerateList(LIST list,Const lwb,Const upb) => emitter.Emitnl("DECLARE_LIST(",CName(list),",",CName(lwb),",",CName(upb),");");

      public void GenerateMacroStart(Macro macro) => emitter.NlEmit("\n",sourceEmitter.Content);
      public void GenerateMacroEnd(Macro macro) {
         if (!macro.CanFail) emitter.NlEmitnl("RETURN;");
         DecrementIndent();
         emitter.Emitnl("}");
      }

      public void GenerateMacroBodyStart(Macro macro,bool inlining) { }

      public void GenerateMacroBodyEnd(Macro macro,bool inlining) { }

      public void GenerateReturnExpressionStart(Macro macro) {
         if (macro.CanFail) emitter.Emit(macro.NeedsFinalization ? "if (" : "RETURNV(");
      }

      public void GenerateReturnExpressionEnd(Macro macro) {
         if (macro.CanFail) emitter.Emitnl(macro.NeedsFinalization ? ") goto Finalization; " : ");");
      }

      private readonly Stack<int> FinalizationLabels = [];
      public void GenerateMacroInlineStart(Macro macro) {
         // if (macro.NeedsFinalization) FinalizationLabels.Push(NextLabel);
         if (macro.CanFail) emitter.Emit("if (!(");
      }
      public void GenerateMacroInlineEnd(Macro macro) {
         if (macro.CanFail) {
            ReferencedLabels.Add(Label);
            emitter.Emitnl($")) goto {Label};");
         } else {
            emitter.Emitnl();
         }
      }

      public void GenerateMacroElementInt(long value) => emitter.Emit(value);
      public void GenerateMacroElementFloat(double value) => emitter.Emit(value);

      public void GenerateMacroElementString(string value,bool firstElement,bool quoted) {
         if (quoted) {
            emitter.Emit("\"",value.Replace("\"","\\\""),"\"");
         } else {
            string[] lines = value.Split('\n');
            foreach (string line in lines.Skip(firstElement ? 1 : 0).SkipLast(1)) emitter.Emitnl(line);
            emitter.Emit(lines.Last());
         }
      }

      public void GenerateMacroElementConst(Const c) => emitter.Emit(CName(c));
      public void GenerateMacroElementVar(Var v,bool canFail,bool inlined = false) => emitter.Emit(CName(v,canFail && !inlined ? "_" : ""));
      public void GenerateMacroElementList(LIST l) => emitter.Emit(CName(l));
      public void GenerateMacroElementLocal(Local local,Affix calledAffix) => emitter.Emit(CName(local));
      /// <summary>
      /// ALways generate *a as (*a) to ensure ++ and -- work correctly.
      /// </summary>
      /// <param name="affix"></param>
      /// <param name="canFail"></param>
      public void GenerateMacroElementAffix(Affix affix,bool canFail) {
         if (affix.IsOutput) {
            if (canFail) {
               emitter.Emit(CName(affix,"_"));
            } else {
               emitter.Emit("(*" + CName(affix),")");
            }
         } else {
            emitter.Emit(CName(affix));
         }
      }

      #region Procedures
      public void GenerateProcedureStart(Procedure proc) {
         emitter.Emitnl();
      }

      public void GenerateProcedureEnd(Procedure proc) {
         emitter.Emitnl(proc.CanFail ? proc.NeedsFinalization ? "RETURNV(TRUE);" : "RETURNV(FALSE);" : "RETURN;");
         DecrementIndent();
         emitter.NlEmitnl("}");
      }

      private int LabelCounter = 0;
      private const string labelPrefix = "L";
      private void GenerateLabel() { if (ReferencedLabels.Contains(Label)) emitter.Emitnl(labelPrefix + NextLabel + ":"); }
      private string Label => labelPrefix + LabelCounter;
      private Set<string> ReferencedLabels = [];
      private int NextLabel => LabelCounter++;
      public void GenerateProcedureBodyStart(Procedure proc,ProcedureBodyType bodyType) { }

      public void GenerateProcedureBodyEnd(Procedure proc,ProcedureBodyType bodyType) { }

      public void GenerateAlternativeStart(Procedure proc,Group group,int alternativeNumber,bool supressLabel) {
         GenerateComment($"Alternative {alternativeNumber}");
         if (!supressLabel && alternativeNumber > 1) GenerateLabel();
         IncrementIndent();
      }

      public void GenerateAlternativeEnd(Procedure proc,Group group,int alternativeNumber,Alternative alternative,bool removed) {
         if (alternative.lastCall.type != LCT.Group && alternative.lastCall.type != LCT.Repeat && !removed && !alternative.Terminates)
            emitter.Emitnl(proc.CanFail ? proc.NeedsFinalization ? "goto Finalization;" : "RETURNV(TRUE);" : "RETURN;");
         DecrementIndent();
         GenerateComment($"End Alternative {alternativeNumber}");
         if (group.LiveAlternatives == 1 && proc.CanFail) GenerateLabel();
      }

      public void GenerateGroupStart(Procedure proc,Group group) {
         GenerateComment($"Group {CName(group.Id)}");
         if (proc.ReferrencesGroup(group.Id)) emitter.Emitnl(CName(group.Id) + ":");
         IncrementIndent();
      }

      public void GenerateGroupEnd(Procedure proc,Group group) {
         DecrementIndent();
         GenerateComment($"End Group {CName(group.Id)}");
      }

      public void GenerateCallStart(Algorithm called,Procedure calling,bool canFail,bool onlyCallInAlternative,bool lastAlternative) {
         if (called.CanFail) emitter.Emit("if (! ");
         emitter.Emit(CName(called),"(");
      }

      public void GenerateCallEnd(Algorithm called,Procedure calling,bool canFail,bool onlyCallInAlternative,bool lastAlternative) {
         if (called.CanFail) {
            if (lastAlternative) {
               emitter.Emit(")) RETURNV(FALSE);");
            } else {
               ReferencedLabels.Add(Label);
               emitter.Emit($")) goto {Label};");
            }
         } else {
            emitter.Emit(");");
         }
         Newline();
      }

      public void GenerateFail(Procedure proc,Group group) => emitter.Emitnl("RETURNV(FALSE);");
      public void GenerateSucceed(Procedure proc,Group group) => emitter.Emitnl(proc.CanFail ? "RETURNV(TRUE);" : "RETURN;");
      public void GenerateAbort(Procedure proc,Group group) => emitter.Emitnl("exit(1);");
      public void GenerateRepeat(Procedure proc,Group group,ID label,bool canFail)
         => emitter.Emitnl("goto " + (label.IsAnonymous ? CName(group.Id) : CName(label)) + ";");

      public void GenerateActualArgSeparator() => emitter.Emit(", ");
      public void GenerateCallArgString(string value) => emitter.Emit("\"",value.Replace("\"","\\\""),"\"");
      public void GenerateCallArgReferenceConst(Affix affix,Const c) => emitter.Emit(CName(c));

      public void GenerateCallArgReferenceVar(Affix affix,Var v,bool needFinalization) {
         if (affix.IsOutput) emitter.Emit("&",CName(v,needFinalization ? "_" : ""));
         else emitter.Emit(CName(v,needFinalization ? "_" : ""));
      }

      public void GenerateCallArgReferenceAffix(Affix calledAffix,Affix callingAffix,bool needFinalization) {
         if (calledAffix.IsOutput) {
            if (callingAffix.IsOutput) emitter.Emit(needFinalization ? "&" : "",CName(callingAffix,needFinalization ? "_" : ""));
            else emitter.Emit(CName(callingAffix));
         } else {
            emitter.Emit(callingAffix.IsOutput ? "*" : "",CName(callingAffix,needFinalization && callingAffix.IsOutput ? "_" : ""));
         }
      }

      public void GenerateCallArgReferenceLocal(Affix affix,Local local) => emitter.Emit(affix.IsOutput ? "&" : "",CName(local));
      #endregion Procedures

      public override void GenerateDeclaration(Algorithm alg) {
         GenerateAlgorithmHeaderStart(alg);
         CodeGenerator.GenerateAlgorithmAffixes(this,alg);
         emitter.Emitnl(");");
      }

      //public void GenerateAlgorithmHeaderStart(Algorithm alg) => emitter.Emit($"{(alg.CanFail ? "BOOL" : "void")} {CName(alg)}(");
      public void GenerateAlgorithmHeaderStart(Algorithm alg)
         => emitter.Emit($"{alg.BodyType switch { TT.PROCBODY or TT.PROCINLINEBODY => "PROC", _ => "MACRO" }} {alg.AlgorithmType} {CName(alg)}(");

      private static string C2AffType(Affix aff) => aff.affixDir switch {
         AD.input => "C2_AFF_INPUT",
         AD.output => "C2_AFF_OUTPUT",
         AD.transput => "C2_AFF_TRANSPUT",
         AD.NONE => "C2_AFF_STRING",
         _ => ""
      };
      public void GenerateAlgorithmHeaderEnd(Algorithm alg) {
         emitter.Emitnl(") {");
         IncrementIndent();

         EmitAffixesTraceData(alg);
      }
      private void EmitAffixesTraceData(Algorithm alg) { }

      public void GenerateTraceEnter(Algorithm alg,IEnumerable<Local> locals,int algIndex) {  
         if (Settings.IsBacktrace) {
            void emitComma() => emitter.Emit(",");
            void emitArrayEnd() => emitter.Emitnl("};");
            string affDiscriminator(Affix aff) => aff.IsOutput ? "PTR" : aff.IsString ? "STR" : "VAL";

            string affValues = "NULL";
            if (alg.Affixes.Count > 0) {
               affValues = "(C2DataValue[]){"+string.Join(",",alg.Affixes.Select(aff => $"{affDiscriminator(aff)}({CName(aff)})"))+"}";
               //emitter.Emit("C2DataValue C2AffValues[] = {");
               //alg.Affixes.GenerateJoinedSequence(aff => emitter.Emit($"{affDiscriminator(aff)}({CName(aff)})"),emitComma,emitArrayEnd);
            //} else {
            //   emitter.Emitnl("C2DataValue C2AffValues[]={PTR(0)};");
            }
            string localValues = "NULL";
            if (locals.Any()) {
               localValues = "(VALUE[]){" + string.Join(",",alg.Locals.Select(loc => $"{CName(loc)}")) + "}";
            //   emitter.Emit("VALUE* C2Locals[] = {");
            //   locals.GenerateJoinedSequence(local => emitter.Emit("&" + CName(local)),emitComma,emitArrayEnd);
            //} else {
            //   emitter.Emitnl("VALUE* C2Locals[1];");
            }
            string affRefs = $"{alg.Affixes.Count},C2AffValues,C2AffNames,C2AffTypes";
            string localsRefs = $"{locals.Count()},C2Locals,C2LocalNames";
            string id = alg.Id.Name;
            if (alg.IsSynthetic) {
               id = alg.FQN();
            }
            emitter.Emitnl($"c2push_callstack_frame({algIndex},{affValues},{localValues});");
            if (Settings.IsTrace) emitter.Emitnl("c2TraceEnter();");
         }
      }

      public void GenerateAffix(Affix affix,AffixDir dir,bool canFail) {
         switch (dir) {
            case AD.input:
               emitter.Emit("VALUE ",CName(affix));
               break;
            case AD.NONE:
               emitter.Emit("char *",CName(affix));
               break;
            default:
               emitter.Emit("VALUE *",CName(affix));
               break;
         }
      }

      public void GenerateAffixSeparator() => emitter.Emit(", ");

      public void GenerateLocal(Local local) => emitter.Emitnl("VALUE ",CName(local)," = ",RandomInitialValue,";");

      public void GenerateAffixAndVariableInitializationStart(Algorithm alg) {
         if (alg.NeedsFinalization) GenerateComment("Initialization");
      }

      public void GenerateAffixAndVariableInitializationEnd(Algorithm alg) {
         if (alg.NeedsFinalization) GenerateComment("End Initialization");
      }

      public void GenerateAffixAndVariableInitializer(Algorithm alg,IFailureProtected item,bool isVar) {
         switch (item is Affix affix ? affix.affixDir : AD.transput) {
            case AD.NONE:
            case AD.input:
               break;
            case AD.output:
               if (isVar) {
                  emitter.Emitnl("VALUE ",CName((Var)item,"_")," = ",RandomInitialValue,";");
               } else {
                  emitter.Emitnl("VALUE ",CName((Affix)item,"_")," = ",RandomInitialValue,";");
               }
               break;
            case AD.transput:
               if (isVar) {
                  emitter.Emitnl("VALUE ",CName((Var)item,"_")," = ",CName((Var)item),";");
               } else {
                  emitter.Emitnl("VALUE ",CName((Affix)item,"_")," = *",CName((Affix)item),";");
               }
               break;
         }
      }

      public void GenerateAffixAndVariableFinalizationStart(Algorithm algorithm) {
         if (algorithm.NeedsFinalization) {
            emitter.Emitnl("RETURNV(FALSE);");
            emitter.Emitnl("Finalization:");
         }
      }

      public void GenerateAffixAndVariableFinalizationEnd(Algorithm algorithm) {
         if (algorithm.NeedsFinalization) {
            GenerateComment("End Finalization");
            emitter.Emitnl("RETURNV(TRUE);");
         }
      }

      public void GenerateAffixAndVariableFinalizer(Algorithm alg,IFailureProtected item,bool isVar) {
         switch (item is Affix affix ? affix.affixDir : AD.transput) {
            case AD.NONE:
            case AD.input:
               break;
            default:
               if (isVar) {
                  emitter.Emitnl(CName((Var)item)," = ",CName((Var)item,"_"),";");
               } else {
                  emitter.Emitnl("*",CName((Affix)item)," = ",CName((Affix)item,"_"),";");
               }
               break;
         }
      }

      public void GenerateProgramPart(Program program,ID moduleId,bool isSeparate) { }

      public void GenerateProgramLudeStart(RW ludeType,Program program) => emitter.Emitnl("/* Program ",ludeType," */");

      public void GenerateProgramLudeEnd(RW ludeType,Program program) { }

      public void GenerateProgramLude(RW ludeType,Program program,Module module) =>
            emitter.Emitnl($"{module.TypeShortName}_{module.Id.Name.AsIdentifier(camelCase: false)}__{ludeType}();");

      public void GenerateModuleStart(Module module,bool isSeparate,string? headerFileName = null) {
         emitter.Emitnl();
         EmitUnitStartComment(module);
      }

      public void GenerateModuleEnd(Module module,bool isSeparate) => EmitUnitEndComment(module);

      public void GenerateImpExStart(Module module) { }
      public void GenerateImpExEnd(Module module) { }
      public void GenerateExport(IProvidable exportedItem) { }
      public void GenerateImport(IProvidable importedItem) { }

      public void GenerateModuleLudeStart(RW ludeType,Module module,bool wrapped) {
         emitter.Emitnl($"{LineComment} MOD ",module.Id.Name," ",ludeType);
         if (wrapped) {
            string returnType = ludeType == RW.ROOT || ludeType == RW.PRELUDE || ludeType == RW.POSTLUDE ? "void" : "VALUE";
            string moduleName = $"{module.TypeShortName}_{module.Id.Name.AsIdentifier(camelCase: false)}__{ludeType}";

            emitter.Emitnl(returnType," ",moduleName,"__",ludeType,"()");
            emitter.Emitnl("{");
            IncrementIndent();
         }
         IncrementIndent();
      }

      public void GenerateModuleLudeEnd(RW ludeType,Module module,bool wrapped) {
         if (wrapped) {
            DecrementIndent();
            emitter.Emitnl("}");
         }
         DecrementIndent();
      }

      public void GenerateModuleLude(RW ludeType,Module module,Section section) {
         Guid ludeGuid = section.LudeProcs[ludeType] ?? Guid.Empty;
         if (ludeGuid != Guid.Empty && ludeGuid.ToCDL2Object<Procedure>() is Procedure lude) {
            emitter.Emitnl($"{LineComment} {section} {ludeType}");
            emitter.Emitnl(lude.FQN(camelCase: false,literalObjectName: true),"();");
         }
      }

      public void GenerateLayerStart(Layer layer) { }
      public void GenerateLayerEnd(Layer layer) { }
      public void GenerateSectionStart(Section section) { }
      public void GenerateSectionEnd(Section section) { }
      public void GenerateSectionLudeStart(RW ludeType,Section section) { }
      public void GenerateSectionLudeEnd(RW ludeType,Section section) { }
      public void GenerateSectionLude(RW ludeType,Section section,Procedure proc) => emitter.Emitnl(CName(proc),"();");


      #region Helpers
      private static string CName(CDL2Object obj,string suffix = "") => obj.FQN(camelCase: false,literalObjectName: obj.IsSynthetic) + suffix;
      private static string CName(Affix affix,string suffix = "") => "a_" + affix.Id.Name.AsIdentifier(camelCase: false) + suffix;
      private static string CName(Local local,string suffix = "") => "l_" + local.Id.Name.AsIdentifier(camelCase: false) + suffix;
      private static string CName(Var var,string suffix = "") => "v_" + var.FQN(camelCase: false,literalObjectName: var.IsSynthetic) + suffix;
      private static string CName(ID id) => id.Name.AsIdentifier(camelCase: false);
      private static string CArgName(IActualArg arg,string suffix = "") => arg switch {
         Affix a => CName(a,suffix),
         Local l => CName(l,suffix),
         Var v => CName(v,suffix),
         _ => throw new NotImplementedException($"CName not implemented for type {arg.GetType()}."),
      };
      /// <summary>
      /// Generate the constant that will be assinged to an Affix, Local or Var.
      /// </summary>
      /// <param name="value"></param>
      /// <returns></returns>
      /// <exception cref="NotImplementedException"></exception>
      private string GenerateValueExpression(object value) => value switch {
         long l => l.ToString(),
         int i => i.ToString(),
         double d => d.ToString(System.Globalization.CultureInfo.InvariantCulture),
         string s => $"\"{s.Replace("\"","`\"")}\"",
         _ => throw new NotImplementedException($"Value expression generation not implemented for type {value.GetType()}."),
      };


      #endregion Helpers
   }
}