// Ignore Spelling: Finalizer lwb upb CDL

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using System.Reflection.Emit;
using System.Text;
using System.Threading.Tasks;

namespace CDL2v1 {
   internal class CodeGeneratorPowerShell : ICodeGenerator {
      EmitterBase emitter = new EmitterSink();

      /// <summary>
      /// Constructor for the PowerShell proc generator.
      /// </summary>
      /// <param name="dataType">This can be used to change the word size, e.g., to Int32.</param>
      public CodeGeneratorPowerShell(string dataType) {
         DataType = dataType;
         DT = $"[{DataType}]";
      }
      private readonly string DataType;
      private readonly string DT;

      public string FileExtension => ".ps1";
      private static readonly string ProgramHeaderPattern = @"
<#
.SYNOPSIS
   PowerShell proc generated by CDL2 notLastAlternativeOfProc<%0%> for Program <%1%> at <%2:yyyy-MM-dd HH:mm:ss%>.
#>
class BoundedArray {
   [int]$LowerBound
   [int]$UpperBound
   [Array]$Array
   

   BoundedArray([int]$lowerBound, [int]$upperBound) {
       if ($upperBound - $lowerBound -lt 0) {
           throw [System.ArgumentException]::new(""Upper bound $($this.UpperBound) must be greater than or equal to lower bound $($this.LowerBound)."")
       }
       $this.LowerBound = $lowerBound
       $this.UpperBound = $upperBound
       $this.Array = [<%3%>[]]::new($upperBound - $lowerBound + 1)
   }
   [void]CheckIndex([int]$index) {
      if ($index - $this.LowerBound -ge 0 -and $index - $this.LowerBound -le $this.UpperBound - $this.LowerBound) {
         return
      } else {
         throw [System.IndexOutOfRangeException]::new(""Index: $index, LowerBound: $($this.LowerBound), UpperBound: $($this.UpperBound)"")
       }
   }
   # These do NOT create a [] indexer
   [<%3%>]Item([int]$index) {
      $this.CheckIndex($index)
      return $this.Array[$index - $this.LowerBound]
   }

   [void]Item([int]$index, [<%3%>]$value) {
      $this.CheckIndex($index)
      $this.Array[$index - $this.LowerBound] = $value
   }
}

#===============================================================================
";
      private static readonly string ProgramHeader;

      static CodeGeneratorPowerShell() => ProgramHeader = ProgramHeaderPattern.Replace("{","{{").Replace("}","}}").Replace("<%","{").Replace("%>","}");

      public void GenerateComment(string comment) {
         foreach (string line in comment.Split('\n')) emitter.Emitnl("# ",line);
      }

      public void GenerateStart(Program program,EmitterBase emitter) {
         this.emitter = emitter;
         emitter.Emitnl(string.Format(ProgramHeader,CDL2.Version,program.id.Name,DateTime.Now,DataType));


         if (program != null) EmitUnitStartComment(program);
      }

      public void GenerateEnd(Program program) {
         if (program != null) EmitUnitEndComment(program);
      }
      public void GenerateStart(Module module) => EmitUnitStartComment(module);
      public void GenerateEnd(Module module) => EmitUnitEndComment(module);
      public void GenerateStart(Layer layer) => EmitUnitStartComment(layer);
      public void GenerateEnd(Layer layer) => EmitUnitEndComment(layer);
      public void GenerateStart(Section section) => EmitUnitStartComment(section);
      public void GenerateEnd(Section section) => EmitUnitEndComment(section);

      enum PSVarType { Var, List, Const, Affix, Local }

      private static string PSVarPrefix(PSVarType type) => type switch {
         PSVarType.Var => "V_",
         PSVarType.List => "LL_",
         PSVarType.Const => "C_",
         PSVarType.Affix => "A_",
         PSVarType.Local => "L_",
         _ => throw new NotImplementedException(),
      };
      private static PSVarType PSVarTypeOf(DeclaredCDL2Object obj) => obj switch {
         Var => PSVarType.Var,
         LIST => PSVarType.List,
         Const => PSVarType.Const,
         _ => throw new NotImplementedException(),
      };

      private static string _PSVar(string name,PSVarType type,string prefix = "",string suffix = "") => $"${prefix}{PSVarPrefix(type)}{name}{suffix}";
      private static string PSVar(DeclaredCDL2Object obj,string prefix = "",string suffix = "") => _PSVar(PSName(obj),PSVarTypeOf(obj),prefix,suffix);
      private static string PSVar(Affix affix,string prefix = "",string suffix = "") => _PSVar(PSName(affix),PSVarType.Affix,prefix,suffix);
      private static string PSVar(Local local,string prefix = "",string suffix = "") => _PSVar(PSName(local),PSVarType.Local,prefix,suffix);

      private static string PSName(DeclaredCDL2Object obj) => obj.FQN(camelCase: true,literalObjectName:obj.IsSynthetic);
      private static string PSName(Affix affix) => affix.id.Name.AsIdentifier(camelCase:true);
      private static string PSName(Local local) => local.id.Name.AsIdentifier(camelCase: true);
      //private static string PSName(NamedElement name) => name.AsName();

      public void GenerateCode(Const c) {
         string value = $"{PSVar(c)} = ";
         foreach (IConstElement e in c.elements) {
            value += e switch {
               STRING s => $"\"{s.value}\"",
               INT n => n.value,
               FLOAT f => f.value,
               Const ce => PSVar(ce),
               //ID id    => PSVar(id),
               _ => throw new NotImplementedException(),
            };
         }
         emitter.Emitnl(value);
      }
      public void GenerateCode(Var v) => emitter.Emitnl($"{PSVar(v)}");
      public void GenerateCode(LIST l,string lwb,string upb) => emitter.Emitnl($"{PSVar(l)} = New-Object BoundedArray {lwb} {upb}");

      public void GenerateCodeExport(ID id) { }
      public void GenerateCodeImport(ID id) { }

      public void GenerateAlgorithmHeaderStart(Algorithm proc) => emitter.Emit($"function {PSName(proc)} (");
      public void GenerateAlgorithmHeaderEnd(Algorithm proc) {
         emitter.Emitnl(") {");
         emitter.IndentLevel++;
      }

      public void GenerateStart(Procedure code) { }
      public void GenerateEnd(Procedure proc) {
         if (proc.CanFail) emitter.Emitnl("return $__b");
         emitter.IndentLevel--;
         emitter.NlEmitnl("}");
      }

      public void GenerateEnd(Alternative alternative) => throw new NotImplementedException();
      public void GenerateEnd(Group group) => throw new NotImplementedException();
      public void GenerateEnd(Call call) => throw new NotImplementedException();

      public void GenerateStart(Alternative alternative) => throw new NotImplementedException();
      public void GenerateStart(Group group) => throw new NotImplementedException();
      public void GenerateStart(Call call) => throw new NotImplementedException();


      public void generateLudeStart(RW ludeType,Container section) {

      }
      public void generateLudeEnd(RW ludeType,Container section) => throw new NotImplementedException();
      public void GenerateStart(Program program,string target) => throw new NotImplementedException();

      public void GenerateLudeStart(RW ludeType,Container section) => throw new NotImplementedException();
      public void GenerateLudeEnd(RW ludeType,Container section) => throw new NotImplementedException();
      public void GenerateStart(Macro macro) { }
      public void GenerateEnd(Macro macro) {
         emitter.IndentLevel--;
         emitter.NlEmitnl("}");
      }
      public void GenerateCode(LIST l) => throw new NotImplementedException();
      public void GenerateExport(Module module,ID expId) => throw new NotImplementedException();
      public void GenerateLudeStart(RW ludeType,Section section) => throw new NotImplementedException();
      public void GenerateLudeEnd(RW ludeType,Section section) => throw new NotImplementedException();
      public void GenerateParamSeparator() => emitter.Emit(",");


      private void EmitUnitStartComment(Container unit) => emitter.Emitnl($"# Begin {unit.ContainerName}");
      private void EmitUnitEndComment(Container unit) => emitter.Emitnl($"# End {unit.ContainerName}");
      //public void GenerateLocalDeclaration(ID affix) => emitter.Emitnl($"   {PSVar(affix)} = $null");
      public void GenerateMacroElemInt(long value) => emitter.Emit(value);
      public void GenerateMacroElemFloat(double value) => emitter.Emit(value);
      public void GenerateMacroElemString(string value) {
         string[] lines = value.Split('\n');
         foreach (string line in lines.SkipLast(1)) emitter.Emitnl(line);
         emitter.Emit(lines.Last());
      }
      public void GenerateReference(Var var) => emitter.Emit(PSVar(var,"_"));
      public void GenerateReference(LIST list) => emitter.Emit(PSVar(list));
      public void GenerateReference(Const constant) => emitter.Emit(PSVar(constant));
      public void GenerateReference(Affix affix) => emitter.Emit(PSVar(affix,"_"));
      public void GenerateReferenceLocal(Local local) => emitter.Emit(PSVar(local));
      public void GenerateDeclareLocal(Local local) => emitter.Emitnl(DT,PSVar(local)," = 0");
      public void GenerateDeclareAffix(Affix affix,AD dir) {
         switch (dir) {
            case AD.input:
               emitter.Emit(DT,PSVar(affix,"_"));
               break;
            case AD.NONE:
               // String (given as AD.NONE)
               emitter.Emit("[string]",PSVar(affix,"_"));
               break;
            default:
               emitter.Emit("[ref]",PSVar(affix));
               break;
         }
      }
      public void GenerateCodeConst(Const c) => throw new NotImplementedException();
      public void GenerateCodeDeclareVar(Var var) => emitter.Emitnl(DT,PSVar(var)," = 0");
      public void GenerateCodeDeclareList(LIST var,Const lwb,Const upb) => emitter.Emitnl(PSVar(var),$" = [BoundArray]::new({PSVar(lwb)},{PSVar(upb)})");
      public void GenerateInitializer(IFailureProtected var,AD affixDir = AD.transput,bool isVar = false) {
         PSVarType type = isVar ? PSVarType.Var : PSVarType.Affix;
         switch (affixDir) {
            case AD.NONE:               
            case AD.input:
               break;
            case AD.output:
               if (isVar) {
                  emitter.Emitnl(DT,PSVar((Var)var,"_")," = 0");
               } else {
                  emitter.Emitnl(DT,PSVar((Affix)var,"_")," = 0");
               }
               break;
            case AD.transput:
               if (isVar) { 
                  emitter.Emitnl(DT,PSVar((Var)var,"_")," = ",PSVar((Var)var)); 
               } else {
                  emitter.Emitnl(DT,PSVar((Affix)var,"_")," = ",PSVar((Affix)var,suffix:".Value"));
               }
               break;

         }
      }

      public void GenerateFinalizer(IFailureProtected var,AD affixDir = AD.transput,bool isVar = false) {
         PSVarType type = isVar ? PSVarType.Var : PSVarType.Affix;
         switch (affixDir) {
            case AD.NONE:
            case AD.input:
               break;
            default:
               if (isVar) {
                  emitter.Emitnl(PSVar((Var)var)," = ",PSVar((Var)var,"_"));
               } else {
                  emitter.Emitnl(PSVar((Affix)var,suffix:".Value")," = ",PSVar((Affix)var,"_"));
               }
               break;
         }
      }

      public void Newline() => emitter.Emitnl();
      public void GenerateMacroBodyStart(Macro macro) {
         if (macro.CanFail) emitter.Emitnl("$__b = (");
         emitter.IndentLevel++;
      }
      public void GenerateMacroBodyEnd(Macro macro) {
         emitter.Emitnl();
         emitter.IndentLevel--;
         if (macro.CanFail) emitter.Emitnl(")");
      }

      public void GenerateProcedureBodyStart(Procedure proc) {
         if (proc.NeedsFinalization) emitter.Emitnl("do {");
         emitter.IndentLevel++;
      }
      public void GenerateProcedureBodyEnd(Procedure proc) {
         if (proc.NeedsFinalization) emitter.Emitnl("break");
         emitter.IndentLevel--;
         if (proc.NeedsFinalization) emitter.Emitnl("} while ($true)");
      }

      public void FinalizationStart(Algorithm algorithm,bool IsNeeded) {
         if (IsNeeded && algorithm.CanFail) {
            emitter.Emitnl("if ($__b) {");
            emitter.IndentLevel++;
         }
      }
      public void FinalizationEnd(Algorithm algorithm,bool IsNeeded) {
         if (algorithm.CanFail) {
            if (IsNeeded) {
               emitter.IndentLevel--;
               emitter.Emitnl("}");
            }
         }
      }

      public void GenerateConstantStart(Const c) => emitter.Emit(PSVar(c)," = ");
      public void GenerateConstElemString(string value) => GenerateMacroElemString(value);
      public void GenerateConstElemFloat(double value) => GenerateMacroElemFloat(value);
      public void GenerateConstElemInt(long value) => GenerateMacroElemInt(value);
      public void GenerateConstantEnd(Const c) => emitter.Emitnl();
      public void GenerateDataSectionStart(Func<int> count,string v) {
         int n = count();
         if (n > 0) emitter.NlEmitnl($"\n##### {n} {v}{(n != 1 ? "s" : "")} #####\n");
      }

      public void GenerateActualArgSeparator() => emitter.Emit(" ");
      public void GenerateCallStart(Algorithm called,Procedure proc,bool canFail = false) {
         if (!proc.IsVerySimple) {
            if (canFail) emitter.Emit("if ($__b) { ");
            if (called.CanFail) emitter.Emit("[bool]$__b = ");
         }
         emitter.Emit(PSName(called)," ");
      }
      public void GenerateCallEnd(Algorithm call,Procedure proc,bool canFail = false) {
         if (canFail && !proc.IsVerySimple) {
            emitter.Emit(" }");
         }
         Newline();
      }

      private string AffixRef(Affix calledAffix,string prefix = "") => (calledAffix.IsOutput ? "[ref]" : "") + prefix;
      public void GenerateCallArgString(string value) => emitter.Emit($"\"{value}\"");
      public void GenerateCallArgReferenceAffix(Affix calledAffix,Affix a) => emitter.Emit(PSVar(a,AffixRef(calledAffix,"_")));
      public void GenerateCallArgReferenceLocal(Affix calledAffix,Local lo) => emitter.Emit(PSVar(lo,AffixRef(calledAffix)));
      public void GenerateCallArgReferenceConst(Affix calledAffix,Const c) => emitter.Emit(PSVar(c));
      public void GenerateCallArgReferenceVar(Affix calledAffix,Var v) => emitter.Emit(PSVar(v,AffixRef(calledAffix,"_")));
      void ICodeGenerator.GenerateAlternativeStart(Procedure proc,Group group,int i) {
         GenerateComment($"Alternative {i+1}");
         emitter.IndentLevel++;
      }
      void ICodeGenerator.GenerateAlternativeEnd(Procedure proc,Group group,int i) {
         bool notLastAlternativeOfProc = group != proc.group || group.alternatives.Count != i + 1;
         if (proc.NeedsFinalization && notLastAlternativeOfProc) {
            emitter.Emitnl("if ($__b) { break }");
         } else if (notLastAlternativeOfProc) { 
            emitter.Emitnl("if ($__b) { return $__b }");
         } else if (proc.NeedsFinalization && !group.alternatives[i].CanFail) {
            emitter.Emitnl("$__b = $true");
         }
            emitter.IndentLevel--;
      }
      void ICodeGenerator.GenerateRepeat(Procedure proc,Group group) => throw new NotImplementedException();
      void ICodeGenerator.GenerateFail(Procedure proc,Group group) {
         if (! proc.IsVerySimple) {
            emitter.Emitnl("return $false");
         }
      }
      void ICodeGenerator.GenerateSucceed(Procedure proc,Group group) { }
      void ICodeGenerator.GenerateAbort(Procedure proc,Group group) => emitter.Emitnl("exit 1");
   }
}
